<?php
namespace Delnavazan\Platform\Core\Application;

use Delnavazan\Platform\Core\Infrastructure\Repository\CanonicalLessonAuthorityRepository;
use Delnavazan\Platform\Core\Support\Identifier;

/** Explicit canonical Lesson issuance and lifecycle; it has no schedule, attendance or provider authority. */
final class CanonicalLessonAuthorityService {
    private const CAPABILITY='dzn_manage_canonical_lessons';
    private const CHANNELS=array('staff_record','authenticated_platform','document_reference');
    public function __construct(private ?CanonicalLessonAuthorityRepository $repository=null){$this->repository??=new CanonicalLessonAuthorityRepository();}
    public function createStandard(int $termId,int $expectedAssignment,array $evidence,string $key):array{return $this->create('standard',$termId,$expectedAssignment,null,$evidence,$key);}
    public function createReplacement(int $termId,int $expectedAssignment,int $originId,array $evidence,string $key):array{return $this->create('replacement',$termId,$expectedAssignment,$originId,$evidence,$key);}
    public function complete(int $lessonId,string $expectedState,array $evidence,string $key):array{return $this->transition('complete',$lessonId,$expectedState,$evidence,$key);}
    public function cancel(int $lessonId,string $expectedState,array $evidence,string $key):array{return $this->transition('cancel',$lessonId,$expectedState,$evidence,$key);}
    private function create(string $type,int $termId,int $expectedAssignment,?int $originId,array $evidence,string $rawKey):array{
        $this->cap();$actor=$this->actor();if($termId<1||$expectedAssignment<1)throw new \InvalidArgumentException('Canonical Term and expected Teacher Assignment required');if($type==='replacement'&&(!$originId||$originId<1))throw new \InvalidArgumentException('Replacement origin required');if($type==='standard'&&$originId!==null)throw new \InvalidArgumentException('Standard Lesson has no replacement origin');$hint=$this->repository->term($termId);if(!$hint||$hint->record_model!=='canonical_enrolment_term_v1')throw new \InvalidArgumentException('canonical_term_required');$proof=$this->evidence($type==='replacement'?'canonical_replacement_issued':'canonical_standard_issued',$evidence);$facts=array('term_id'=>$termId,'expected_teacher_assignment_id'=>$expectedAssignment,'classification'=>$type,'replacement_origin_lesson_id'=>$originId)+$proof;
        return $this->execute('create_'.$type,(int)$hint->enrolment_id,$termId,$facts,$rawKey,function($digest,$payload)use($type,$termId,$expectedAssignment,$originId,$proof,$actor,$facts){$termHint=$this->repository->term($termId);if(!$termHint)throw new \InvalidArgumentException('canonical_term_required');$enrolmentId=(int)$termHint->enrolment_id;$enrolmentHint=$this->repository->enrolment($enrolmentId);if(!$enrolmentHint)throw new \InvalidArgumentException('canonical_enrolment_required');$this->repository->lockRoot($enrolmentHint);$e=$this->repository->enrolment($enrolmentId,true);$term=$this->repository->term($termId,true);$lessons=$this->repository->lessons($termId,true);$this->validLessons($lessons);do_action('dzn_phase_2a2m_lesson_locks_held','create_'.$type,$enrolmentId,$termId);if($winner=$this->repository->command($digest))return $this->replay($winner,$payload,'create_'.$type,$enrolmentId,$termId,$facts);$this->valid($e,$term);$assignmentHint=$this->repository->assignment($enrolmentId,false);if(!$assignmentHint||(int)$assignmentHint->id!==$expectedAssignment||(string)$assignmentHint->state!=='assigned')throw new \InvalidArgumentException('stale_teacher_assignment');$teacher=$this->repository->teacher((int)$assignmentHint->teacher_id);if(!$teacher||$teacher->archived_at!==null)throw new \InvalidArgumentException('teacher_not_available');$assignment=$this->repository->assignment($enrolmentId,true);if(!$assignment||(int)$assignment->id!==$expectedAssignment||(int)$assignment->teacher_id!==(int)$assignmentHint->teacher_id||(string)$assignment->state!=='assigned')throw new \InvalidArgumentException('stale_teacher_assignment');do_action('dzn_phase_2a2m_lesson_authority_locks_held','create_'.$type,$enrolmentId,$termId,(int)$assignment->id,(int)$assignment->teacher_id);if($type==='standard'&&count(array_filter($lessons,fn($l)=>$l->lesson_type==='standard'))>=12)throw new \InvalidArgumentException('standard_allocation_exhausted');if($type==='replacement'){$origin=$this->repository->lesson($originId,true);if(!$origin||$origin->record_model!=='canonical_term_lesson_v1'||$origin->lesson_type!=='standard'||(int)$origin->term_id!==$termId||(string)$origin->lifecycle_state!=='cancelled'||!$this->eligible($origin))throw new \InvalidArgumentException('replacement_origin_not_eligible');foreach($lessons as$l)if((int)$l->canonical_replacement_origin_lesson_id===$originId)throw new \InvalidArgumentException('replacement_origin_already_claimed');if(count(array_filter($lessons,fn($l)=>$l->lesson_type==='replacement'))>=2)throw new \InvalidArgumentException('replacement_allocation_exhausted');}
            $now=gmdate('Y-m-d H:i:s');$sequence=count($lessons)+1;$id=$this->repository->insertLesson(array('uid'=>Identifier::uid(),'reference_code'=>null,'student_id'=>(int)$e->student_id,'teacher_id'=>(int)$teacher->id,'course_id'=>(int)$e->course_id,'enrolment_id'=>$enrolmentId,'term_id'=>$termId,'lesson_type'=>$type,'status'=>'canonical','sequence_number'=>null,'current_schedule_version_id'=>null,'replacement_for_lesson_id'=>null,'created_at'=>$now,'updated_at'=>$now,'created_by'=>$actor,'updated_by'=>$actor,'archived_at'=>null,'archived_by'=>null,'record_model'=>'canonical_term_lesson_v1','lifecycle_state'=>'authorised','canonical_sequence'=>$sequence,'teacher_assignment_id'=>(int)$assignment->id,'canonical_replacement_origin_lesson_id'=>$originId));do_action('dzn_phase_2a2m_after_lesson_insert',$type);$this->event($id,1,null,'authorised',$proof,$now,$actor);do_action('dzn_phase_2a2m_after_lifecycle_event_insert',$type);$this->command($digest,$payload,'create_'.$type,$enrolmentId,$termId,$expectedAssignment,null,null,$originId,$id,'authorised',$now,$actor);do_action('dzn_phase_2a2m_after_command_insert',$type);return array('lesson_id'=>$id,'created'=>true,'operation'=>'create_'.$type);});
    }
    private function transition(string $operation,int $lessonId,string $expected,array $evidence,string $key):array{$this->cap();$actor=$this->actor();if($expected!=='authorised')throw new \InvalidArgumentException('transition_not_allowed');$hint=$this->repository->lesson($lessonId);if(!$hint||$hint->record_model!=='canonical_term_lesson_v1')throw new \InvalidArgumentException('canonical_lesson_required');$reason=$operation==='cancel'?(($evidence['reason_code']??'')==='attested_non_delivery'?'canonical_lesson_cancelled_replacement_eligible':'canonical_lesson_cancelled'):'canonical_lesson_completed';$proof=$this->evidence($reason,$evidence);$facts=array('lesson_id'=>$lessonId,'expected_state'=>$expected,'target_state'=>$operation==='complete'?'completed':'cancelled')+$proof;return $this->execute($operation,(int)$hint->enrolment_id,(int)$hint->term_id,$facts,$key,function($digest,$payload)use($operation,$lessonId,$expected,$proof,$facts,$actor,$hint){$enrolmentHint=$this->repository->enrolment((int)$hint->enrolment_id);if(!$enrolmentHint)throw new \InvalidArgumentException('canonical_enrolment_required');$this->repository->lockRoot($enrolmentHint);$e=$this->repository->enrolment((int)$hint->enrolment_id,true);$t=$this->repository->term((int)$hint->term_id,true);$l=$this->repository->lesson($lessonId,true);if($winner=$this->repository->command($digest))return $this->replay($winner,$payload,$operation,(int)$hint->enrolment_id,(int)$hint->term_id,$facts);$this->validTransitionContext($e,$t);if(!$l||(string)$l->lifecycle_state!==$expected)throw new \InvalidArgumentException('stale_lesson_state');$history=$this->repository->events($lessonId,true);if(!CanonicalLessonAuthorityValidator::valid($l,$history))throw new \InvalidArgumentException('canonical_lesson_integrity_conflict');$now=gmdate('Y-m-d H:i:s');$to=$operation==='complete'?'completed':'cancelled';$this->repository->transition($l,$expected,$to,$now,$actor);do_action('dzn_phase_2a2m_after_lesson_transition',$operation);$this->event($lessonId,count($this->repository->events($lessonId,true))+1,$expected,$to,$proof,$now,$actor);do_action('dzn_phase_2a2m_after_lifecycle_event_insert',$operation);$this->command($digest,$payload,$operation,(int)$hint->enrolment_id,(int)$hint->term_id,null,$lessonId,$expected,null,$lessonId,$to,$now,$actor);do_action('dzn_phase_2a2m_after_command_insert',$operation);return array('lesson_id'=>$lessonId,'created'=>false,'operation'=>$operation);});}
    private function execute(string $operation,int $enrolmentId,int $termId,array $facts,string $raw,callable $work):array{$digest=CanonicalLessonIdempotency::key($raw);$payload=CanonicalLessonIdempotency::payload(array('domain'=>'canonical_lesson_v1','operation'=>$operation,'enrolment_id'=>$enrolmentId,'term_id'=>$termId,'facts'=>$facts));$this->repository->begin();try{$r=$work($digest,$payload);$this->repository->commit();return$r;}catch(\Throwable$e){$this->repository->rollback();if($this->repository->duplicate($e)==='command_key_digest'&&($winner=$this->repository->command($digest)))return $this->replay($winner,$payload,$operation,$enrolmentId,$termId,$facts);throw$e;}}
    /**
     * Replay revalidates the complete recorded intent, the durable result evidence and the
     * result aggregate itself. A corrupted command, result or history may never replay as success.
     */
    private function replay(object $c,string $payload,string $op,int $enrolment,int $term,array $facts):array{
        if(!hash_equals((string)$c->command_payload_digest,$payload))throw new IdempotencyConflictException('Idempotency conflict');
        if((string)$c->command_domain!=='canonical_lesson_v1'||(string)$c->operation!==$op||(int)$c->enrolment_id!==$enrolment||(int)$c->term_id!==$term)throw new \RuntimeException('Contaminated canonical Lesson command');
        $creating=$op==='create_standard'||$op==='create_replacement';
        $target=$creating?'authorised':(string)($facts['target_state']??'');
        $expectedAssignment=$creating?(int)($facts['expected_teacher_assignment_id']??0):null;
        $expectedLesson=$creating?null:(int)($facts['lesson_id']??0);
        $expectedFrom=$creating?null:(string)($facts['expected_state']??'');
        $expectedOrigin=$op==='create_replacement'?(int)($facts['replacement_origin_lesson_id']??0):null;
        if(!in_array($target,array('authorised','completed','cancelled'),true)||($expectedAssignment!==null&&$expectedAssignment<1)||($expectedLesson!==null&&$expectedLesson<1)||($expectedFrom!==null&&$expectedFrom!=='authorised')||($expectedOrigin!==null&&$expectedOrigin<1))throw new \RuntimeException('Contaminated canonical Lesson command');
        if(self::nullableInt($c->expected_teacher_assignment_id)!==$expectedAssignment||self::nullableInt($c->expected_lesson_id)!==$expectedLesson||self::nullableInt($c->replacement_origin_lesson_id)!==$expectedOrigin||self::nullableString($c->expected_from_state)!==$expectedFrom||(string)$c->result_state!==$target)throw new \RuntimeException('Contaminated canonical Lesson command');
        $resultId=self::nullableInt($c->result_lesson_id);
        if(!$resultId||$resultId<1)throw new \RuntimeException('Contaminated canonical Lesson result');
        $lesson=$this->repository->lesson($resultId);
        if(!$lesson||$lesson->record_model!=='canonical_term_lesson_v1')throw new \RuntimeException('Contaminated canonical Lesson result');
        $history=$this->repository->events($resultId);
        if(!CanonicalLessonAuthorityValidator::valid($lesson,$history,$this->repository))throw new \RuntimeException('Contaminated canonical Lesson result');
        if($creating){
            if((int)$lesson->id!==$resultId||(int)$lesson->term_id!==$term||(int)$lesson->enrolment_id!==$enrolment||(string)$lesson->lesson_type!==($op==='create_replacement'?'replacement':'standard')||(int)$lesson->teacher_assignment_id!==$expectedAssignment)throw new \RuntimeException('Contaminated canonical Lesson result');
            if($expectedOrigin!==null&&(int)$lesson->canonical_replacement_origin_lesson_id!==$expectedOrigin)throw new \RuntimeException('Contaminated canonical Lesson result');
        }elseif($resultId!==$expectedLesson||(string)$lesson->lifecycle_state!==$target)throw new \RuntimeException('Contaminated canonical Lesson result');
        $edge=$creating?array(null,'authorised'):array($expectedFrom,$target);
        if(!self::replayEvidence($history,(string)($facts['reason']??''),(string)($facts['channel']??''),(string)($facts['digest']??''),(string)($c->created_at??''),$edge))throw new \RuntimeException('Contaminated canonical Lesson result');
        return array('lesson_id'=>$resultId,'created'=>false,'operation'=>$op,'idempotent'=>true);
    }

    /** A successful replay requires the durable lifecycle evidence the command recorded. */
    private static function replayEvidence(array $events,string $reason,string $channel,string $digest,string $recordedAt,array $edge):bool{
        if($reason===''||$channel===''||$digest===''||$recordedAt==='')return false;
        foreach($events as$event){
            if(self::nullableString($event->from_state??null)!==$edge[0])continue;
            if((string)($event->to_state??'')!==(string)$edge[1])continue;
            if((string)($event->reason_code??'')!==$reason)continue;
            if((string)($event->evidence_channel??'')!==$channel)continue;
            if((string)($event->recorded_at??'')!==$recordedAt)continue;
            if(!hash_equals((string)($event->evidence_reference_digest??''),$digest))continue;
            return true;
        }
        return false;
    }

    private static function nullableInt(mixed $value):?int{return $value===null?null:(int)$value;}
    private static function nullableString(mixed $value):?string{return $value===null?null:(string)$value;}
    private function valid(?object $e,?object $t):void{if(!$e||$e->record_model!=='canonical_student_course_v1'||$e->lifecycle_state!=='current'||(int)$e->applicable_slot!==1||$e->archived_at!==null)throw new \InvalidArgumentException('enrolment_not_current');if(!$t||$t->record_model!=='canonical_enrolment_term_v1'||$t->lifecycle_state!=='current'||(int)$t->applicable_slot!==1||$t->archived_at!==null||(int)$t->enrolment_id!==(int)$e->id)throw new \InvalidArgumentException('term_not_current');}
    private function validTransitionContext(?object $e,?object $t):void{if(!$e||$e->record_model!=='canonical_student_course_v1'||!in_array((string)$e->lifecycle_state,array('current','paused'),true)||(int)$e->applicable_slot!==1||$e->archived_at!==null)throw new \InvalidArgumentException('enrolment_not_lesson_terminalisable');if(!$t||$t->record_model!=='canonical_enrolment_term_v1'||$t->lifecycle_state!=='current'||(int)$t->applicable_slot!==1||$t->archived_at!==null||(int)$t->enrolment_id!==(int)$e->id)throw new \InvalidArgumentException('term_not_current');}
    private function validLessons(array $lessons):void{foreach($lessons as$lesson){$history=$this->repository->events((int)$lesson->id,true);if(!CanonicalLessonAuthorityValidator::valid($lesson,$history,$this->repository,true))throw new \InvalidArgumentException('canonical_lesson_integrity_conflict');}}
    /** The controlled replacement rule lives in the canonical aggregate validator only. */
    private function eligible(object $origin):bool{return CanonicalLessonAuthorityValidator::replacementEligible($origin,$this->repository->events((int)$origin->id,true));}
    private function evidence(string $reason,array $e):array{$channel=(string)($e['evidence_channel']??'');if(!in_array($channel,self::CHANNELS,true))throw new \InvalidArgumentException('Controlled evidence channel required');$at=(string)($e['evidence_at']??'');if(!preg_match('/^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$/D',$at)||strtotime($at.' UTC')===false||$at>gmdate('Y-m-d H:i:s'))throw new \InvalidArgumentException('Valid past-or-present UTC evidence time required');return array('reason'=>$reason,'channel'=>$channel,'digest'=>CanonicalLessonIdempotency::evidence((string)($e['evidence_reference']??'')),'at'=>$at);}
    private function event(int $id,int $sequence,?string $from,string $to,array $p,string $now,int $actor):void{$this->repository->insertEvent(array('uid'=>Identifier::uid(),'lesson_id'=>$id,'event_sequence'=>$sequence,'from_state'=>$from,'to_state'=>$to,'reason_code'=>$p['reason'],'evidence_channel'=>$p['channel'],'evidence_reference_digest'=>$p['digest'],'occurred_at'=>$p['at'],'recorded_at'=>$now,'recorded_by'=>$actor,'created_at'=>$now,'created_by'=>$actor));}
    private function command(string $key,string $payload,string $op,int $enrolment,int $term,?int $assignment,?int $lesson,?string $from,?int $origin,int $result,string $state,string $now,int $actor):void{$this->repository->insertCommand(array('uid'=>Identifier::uid(),'command_domain'=>'canonical_lesson_v1','operation'=>$op,'command_key_digest'=>$key,'command_payload_digest'=>$payload,'enrolment_id'=>$enrolment,'term_id'=>$term,'expected_teacher_assignment_id'=>$assignment,'expected_lesson_id'=>$lesson,'expected_from_state'=>$from,'replacement_origin_lesson_id'=>$origin,'result_lesson_id'=>$result,'result_state'=>$state,'created_at'=>$now,'created_by'=>$actor));}
    private function cap():void{if(!current_user_can(self::CAPABILITY))throw new \RuntimeException('Unauthorized');}
    private function actor():int{$id=get_current_user_id();if($id<1)throw new \RuntimeException('Canonical Lesson actor unavailable');return$id;}
}
