<?php
namespace Delnavazan\Platform\Core\Application;
use Delnavazan\Platform\Core\Infrastructure\Repository\EntityRepository; use Delnavazan\Platform\Core\Support\Identifier;
final class EntityService {
	private const PREFIX=array('teacher'=>'DZN-TCH-','student'=>'DZN-STU-','instrument'=>'DZN-INS-','course'=>'DZN-CRS-','enrolment'=>'DZN-ENR-','term'=>'DZN-TRM-','lesson'=>'DZN-LSN-');
	public function create(string $entity,array $data): int { $this->authorize($entity); $data=$this->normalise($entity,$data); global $wpdb; $repo=new EntityRepository($wpdb->prefix.'dzn_'.$entity.'s'); for($attempt=0;$attempt<3;$attempt++){ $wpdb->query('START TRANSACTION'); try{$data['uid']=Identifier::uid();$data['reference_code']=null;$data['created_at']=$data['updated_at']=gmdate('Y-m-d H:i:s');$data['created_by']=$data['updated_by']=get_current_user_id()?:null;$id=$repo->create($data);$repo->set_reference($id,Identifier::reference(self::PREFIX[$entity],$id));$wpdb->query('COMMIT');return $id;}catch(\Throwable $e){$wpdb->query('ROLLBACK');if(!str_contains($e->getMessage(),'uid'))throw $e;} } throw new \RuntimeException('UID collision retry limit reached.'); }
	private function authorize(string $entity):void { $cap='dzn_manage_'.($entity==='instrument'?'courses':$entity.'s');if(!is_user_logged_in()||!current_user_can($cap))throw new \RuntimeException('Unauthorized'); }
	private function normalise(string $entity,array $d):array { $states=array('teacher'=>array('active','inactive','archived'),'student'=>array('active','inactive','archived'),'instrument'=>array('active','inactive','archived'),'course'=>array('active','inactive','archived'),'enrolment'=>array('draft','active','paused','ending','completed','cancelled','archived'),'term'=>array('draft','awaiting_payment','active','completed','cancelled','archived'),'lesson'=>array('draft','scheduled','cancelled','completed','archived')); if(!in_array($d['status']??'', $states[$entity],true))throw new \InvalidArgumentException('Invalid lifecycle state'); foreach(array('student_id','teacher_id','course_id','enrolment_id','term_id','replacement_for_lesson_id')as$f)if(isset($d[$f]))$d[$f]=absint($d[$f])?:null; if(isset($d['schedule_timezone'])&&$d['schedule_timezone']&&!in_array($d['schedule_timezone'],timezone_identifiers_list(),true))throw new \InvalidArgumentException('Invalid IANA timezone'); if($entity==='lesson'){ $type=$d['lesson_type']??'';if(!in_array($type,array('introductory','standard','replacement'),true))throw new \InvalidArgumentException('Invalid Lesson type');if($type!=='introductory'&&(!$d['enrolment_id']||!$d['term_id']))throw new \InvalidArgumentException('Enrolment and Term required');if($type==='replacement'&&(!$d['replacement_for_lesson_id']||$d['replacement_for_lesson_id']===($d['id']??null)))throw new \InvalidArgumentException('Invalid replacement link'); }return $d; }
}
