<?php
namespace Delnavazan\Platform\Core\Application;

use Delnavazan\Platform\Portals\{AuthenticatedPortalReadSubject,PublicCapabilityReadSubject,TeacherAssignmentPortalReadPort,CanonicalLessonSchedulePortalReadPort,CanonicalLessonDeliveryPortalReadPort,CanonicalAttendancePortalReadPort};
use Delnavazan\Platform\Core\Infrastructure\Repository\{CanonicalLessonAuthorityRepository,CanonicalLessonScheduleRepository,CanonicalLessonDeliveryRepository,CanonicalAttendanceRepository,CanonicalTermAuthorityRepository,TeacherAssignmentRepository,EnrolmentRepository,TeacherRepository,StudentRepository,CourseRepository};

/** Core-owned, read-only portal seams. They deliberately return projections, never repository rows. */
final class CanonicalTeacherAssignmentPortalReadPort implements TeacherAssignmentPortalReadPort {
    public function forSubject(AuthenticatedPortalReadSubject|PublicCapabilityReadSubject $subject,int $enrolmentId):array { if($enrolmentId<1)throw new \InvalidArgumentException('portal_object_not_found');$assignmentRepository=new TeacherAssignmentRepository();$enrolmentRepository=new EnrolmentRepository();$enrolment=(new CanonicalLessonAuthorityRepository())->enrolment($enrolmentId);$history=$enrolment?(new EnrolmentRepository())->lifecycleHistory($enrolmentId):array();if(!$enrolment||!CanonicalEnrolmentLifecycleValidator::valid($enrolment,$history)||!TeacherAssignmentAssessment::applicableEnrolment($enrolment))throw new \InvalidArgumentException('portal_upstream_aggregate_invalid');$assignments=$assignmentRepository->assignmentsForEnrolment($enrolmentId);if(!TeacherAssignmentAssessment::validHistory($assignmentRepository,$enrolmentId,$assignments))throw new \InvalidArgumentException('portal_upstream_aggregate_invalid');$row=$assignmentRepository->currentForEnrolment($enrolmentId);if(!$row||(!$this->isTeacher($subject,$row) && !$this->isStudentOrGuardian($subject,$enrolment)))throw new \InvalidArgumentException('portal_object_not_owned');return $this->projection($row,$enrolment,$assignmentRepository); }
    public function pageForSubject(AuthenticatedPortalReadSubject|PublicCapabilityReadSubject $subject,?string $cursor,int $limit):array { $teacher=$this->teacher($subject);$repository=new TeacherAssignmentRepository();$rows=$repository->currentForTeacher($teacher,max(0,(int)$cursor),$limit);$out=array();foreach($rows as $row){$out[]=$this->forSubject($subject,(int)$row->enrolment_id);}return$out; }
    private function projection(object $row,object $enrolment,TeacherAssignmentRepository $repository):array { $source=$repository->initialSource((int)$enrolment->id);$termInspection=(new TermApplicabilityAssessment())->inspectForAuthority((int)$enrolment->id);$term=null;foreach((array)$termInspection['terms'] as $candidate)if((int)$candidate->applicable_slot===1)$term=$candidate;if(!$source||$termInspection['classification']!==TermApplicabilityAssessment::CANONICAL_APPLICABLE||!$term){throw new \InvalidArgumentException('portal_upstream_aggregate_invalid');}$course=(new CourseRepository())->find((int)$enrolment->course_id);$teacher=(new TeacherRepository())->find((int)$row->teacher_id);$student=(new StudentRepository())->find((int)$enrolment->student_id);if(!$course||!$teacher||!$student||$course->archived_at!==null||$teacher->archived_at!==null||$student->archived_at!==null||trim((string)$course->reference_code)===''||trim((string)$teacher->reference_code)===''||trim((string)$student->reference_code)===''||trim((string)$enrolment->reference_code)===''||trim((string)$term->reference_code)==='')throw new \InvalidArgumentException('portal_upstream_aggregate_invalid');return array('assignment_uid'=>(string)$row->uid,'enrolment_uid'=>(string)$enrolment->uid,'course_reference'=>(string)$course->reference_code,'term_reference'=>(string)$term->reference_code,'assignment_state'=>(string)$row->state,'accepted_at'=>(string)$source['arrangement']->accepted_at,'student_display_reference'=>(string)$student->reference_code,'enrolment_reference'=>(string)$enrolment->reference_code,'lifecycle_state'=>(string)$enrolment->lifecycle_state,'assigned_teacher_display_reference'=>(string)$teacher->reference_code,'schedule_summary'=>array('frequency_per_week'=>(int)$source['arrangement']->frequency_per_week,'timezone'=>(string)$source['arrangement']->timezone)); }
    private function isTeacher($subject,object $row):bool{return $subject instanceof AuthenticatedPortalReadSubject&&$subject->kind==='teacher'&&$this->teacher($subject)===(int)$row->teacher_id;}
    private function isStudentOrGuardian($subject,object $enrolment):bool{if(!($subject instanceof AuthenticatedPortalReadSubject)||(int)$subject->principalId!==(int)$enrolment->student_id)return false;if($subject->kind==='student')return $this->studentLink($subject->principalId,$subject->wordpressUserId);return $subject->kind==='guardian'&&$this->guardianGrant($subject,(int)$enrolment->student_id);}
    private function studentLink(int $student,int $user):bool{global $wpdb;return(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}dzn_student_principal_links WHERE student_id=%d AND wordpress_user_id=%d AND status='active' AND revoked_at IS NULL AND active_slot=1 LIMIT 1",$student,$user));}
    private function guardianGrant(AuthenticatedPortalReadSubject $subject,int $student):bool{global $wpdb;return(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}dzn_student_acceptance_authority_grants WHERE id=%d AND student_id=%d AND acting_wordpress_user_id=%d AND authority_type='guardian_representative' AND authority_scope=%s AND state='active' AND active_slot=1 AND effective_from<=UTC_TIMESTAMP() AND (effective_until IS NULL OR effective_until>UTC_TIMESTAMP()) LIMIT 1",$subject->guardianGrantId,$student,$subject->wordpressUserId,$subject->guardianGrantScope));}
    private function teacher($s):int{if($s instanceof PublicCapabilityReadSubject||!($s instanceof AuthenticatedPortalReadSubject)||$s->kind!=='teacher')throw new \InvalidArgumentException('portal_principal_kind_not_permitted');$repository=new TeacherAssignmentRepository();if(!$repository->teacherPrincipalHasAuthority($s->wordpressUserId,$s->principalId))throw new \InvalidArgumentException('portal_object_not_owned');return$s->principalId;}
}

final class CanonicalLessonSchedulePortalReadPortImpl implements CanonicalLessonSchedulePortalReadPort {
    public function forSubject(AuthenticatedPortalReadSubject|PublicCapabilityReadSubject $subject,int $lessonId):array { $lesson=$this->lesson($subject,$lessonId); $authority=new CanonicalLessonAuthorityRepository(); if(!CanonicalLessonAuthorityValidator::valid($lesson,$authority->events($lessonId),$authority))throw new \InvalidArgumentException('portal_upstream_aggregate_invalid'); $schedule=new CanonicalLessonScheduleRepository(); if(!CanonicalLessonScheduleValidator::validForLesson($lessonId,$schedule,$authority))throw new \InvalidArgumentException('portal_upstream_aggregate_invalid'); $this->assertProjectionContext($lesson);$v=$schedule->applicableVersion($lessonId); if(!$v)throw new \InvalidArgumentException('portal_upstream_aggregate_invalid'); return $this->projection($lesson,$v); }
    public function pageForSubject(AuthenticatedPortalReadSubject|PublicCapabilityReadSubject $subject,?string $cursor,int $limit):array { $limit=max(1,min(50,$limit)); return array_slice(array($this->forSubject($subject,(int)$cursor),),0,$limit); }
    private function lesson($s,int $id):object { $r=(new CanonicalLessonAuthorityRepository())->lesson($id); if(!$r||!in_array((string)$r->lifecycle_state,array('authorised','completed','cancelled'),true)||($s instanceof PublicCapabilityReadSubject&&(string)$r->lifecycle_state!=='authorised'))throw new \InvalidArgumentException('portal_object_not_portal_visible'); global $wpdb; if($s instanceof PublicCapabilityReadSubject){$cap=$wpdb->get_row($wpdb->prepare("SELECT id FROM {$wpdb->prefix}dzn_portal_public_capabilities WHERE id=%d AND lesson_id=%d AND schedule_version_id=%d AND purpose=%s AND generation=%d AND (subject_student_id IS NULL OR subject_student_id=%d) AND state IN ('active','consumed') AND expires_at>UTC_TIMESTAMP() LIMIT 1",$s->capabilityId,$id,$s->scheduleVersionId,$s->purpose,$s->generation,$s->studentId)); if(!$cap||$s->lessonId!==$id||($s->studentId!==null&&(int)$r->student_id!==$s->studentId))throw new \InvalidArgumentException('portal_capability_binding_mismatch');} elseif(in_array($s->kind,array('student','guardian'),true)){if((int)$r->student_id!==$s->principalId||!$this->studentAuthority($s,(int)$r->student_id))throw new \InvalidArgumentException('portal_object_not_owned');} elseif($s->kind!=='teacher'||(int)$r->teacher_id!==$s->principalId||!(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}dzn_teacher_principal_links WHERE teacher_id=%d AND wordpress_user_id=%d AND status='active' AND revoked_at IS NULL LIMIT 1",$s->principalId,$s->wordpressUserId)))throw new \InvalidArgumentException('portal_object_not_owned'); return $r; }
    private function studentAuthority(AuthenticatedPortalReadSubject $subject,int $student):bool{global $wpdb;if($subject->kind==='student')return(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}dzn_student_principal_links WHERE student_id=%d AND wordpress_user_id=%d AND status='active' AND revoked_at IS NULL AND active_slot=1 LIMIT 1",$student,$subject->wordpressUserId));return $subject->kind==='guardian'&&(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}dzn_student_acceptance_authority_grants WHERE id=%d AND student_id=%d AND acting_wordpress_user_id=%d AND authority_type='guardian_representative' AND authority_scope=%s AND state='active' AND active_slot=1 AND effective_from<=UTC_TIMESTAMP() AND (effective_until IS NULL OR effective_until>UTC_TIMESTAMP()) LIMIT 1",$subject->guardianGrantId,$student,$subject->wordpressUserId,$subject->guardianGrantScope));}
    /** Every field in the schedule projection is re-proved through its owning integrity gate. */
    private function assertProjectionContext(object $lesson):void {
        $enrolment=(new CanonicalLessonAuthorityRepository())->enrolment((int)$lesson->enrolment_id);
        $history=$enrolment?(new EnrolmentRepository())->lifecycleHistory((int)$lesson->enrolment_id):array();
        if(!$enrolment||!CanonicalEnrolmentLifecycleValidator::valid($enrolment,$history))throw new \InvalidArgumentException('portal_upstream_aggregate_invalid');
        $inspection=(new TermApplicabilityAssessment())->inspectForAuthority((int)$lesson->enrolment_id);
        if(!in_array((string)$inspection['classification'],array(TermApplicabilityAssessment::CANONICAL_APPLICABLE,TermApplicabilityAssessment::CANONICAL_TERMINAL_HISTORY),true))throw new \InvalidArgumentException('portal_upstream_aggregate_invalid');
        foreach((array)$inspection['terms'] as $term)if((int)$term->id===(int)$lesson->term_id)return;
        throw new \InvalidArgumentException('portal_upstream_aggregate_invalid');
    }
    private function projection($l,$v):array { $enrolment=(new CanonicalLessonAuthorityRepository())->enrolment((int)$l->enrolment_id);$terms=(new CanonicalTermAuthorityRepository())->termsForEnrolment((int)$l->enrolment_id);$term=null;foreach($terms as$candidate)if((int)$candidate->id===(int)$l->term_id)$term=$candidate;$course=$enrolment?(new CourseRepository())->find((int)$enrolment->course_id):null;if(!$enrolment||!$term||!$course||trim((string)$l->uid)===''||trim((string)$l->reference_code)===''||trim((string)$l->lesson_type)===''||trim((string)$enrolment->uid)===''||trim((string)$course->reference_code)===''||trim((string)$term->reference_code)===''||trim((string)$v->uid)===''||trim((string)$v->schedule_timezone)==='')throw new \InvalidArgumentException('portal_upstream_aggregate_invalid');return array('lesson_uid'=>(string)$l->uid,'lesson_reference'=>(string)$l->reference_code,'lesson_kind'=>(string)$l->lesson_type,'lifecycle_state'=>(string)$l->lifecycle_state,'schedule_version_uid'=>(string)$v->uid,'lesson_id'=>(int)$l->id,'schedule_version_id'=>(int)$v->id,'enrolment_id'=>(int)$l->enrolment_id,'enrolment_uid'=>(string)$enrolment->uid,'course_reference'=>(string)$course->reference_code,'term_reference'=>(string)$term->reference_code,'student_id'=>(int)$l->student_id,'teacher_id'=>(int)$l->teacher_id,'starts_at_utc'=>(string)$v->starts_at_utc,'ends_at_utc'=>(string)$v->ends_at_utc,'schedule_timezone'=>(string)$v->schedule_timezone); }
}

final class CanonicalLessonDeliveryPortalReadPortImpl implements CanonicalLessonDeliveryPortalReadPort {
    public function summaryForSubject(AuthenticatedPortalReadSubject|PublicCapabilityReadSubject $subject,int $lessonId):array { $schedule=new CanonicalLessonSchedulePortalReadPortImpl(); $schedule->forSubject($subject,$lessonId); $repo=new CanonicalLessonDeliveryRepository(); if(!CanonicalLessonDeliveryValidator::validForLesson($lessonId,$repo))throw new \InvalidArgumentException('portal_upstream_aggregate_invalid'); $o=$repo->applicableOutcome($lessonId); return array('lesson_id'=>$lessonId,'delivery_state_summary'=>$o?(string)($o->outcome_code??$o->state??'recorded'):'not_recorded'); }
}

final class CanonicalAttendancePortalReadPortImpl implements CanonicalAttendancePortalReadPort {
    public function assertCapabilityClaimAdmissible(PublicCapabilityReadSubject $subject):void { (new CanonicalAttendanceIntakeService())->assertCapabilityClaimAdmissible($subject); }
    public function summaryForSubject(AuthenticatedPortalReadSubject|PublicCapabilityReadSubject $subject,int $lessonId,int $scheduleVersionId):array { $schedule=(new CanonicalLessonSchedulePortalReadPortImpl())->forSubject($subject,$lessonId);if((int)$schedule['schedule_version_id']!==$scheduleVersionId)throw new \InvalidArgumentException('portal_capability_stale_schedule');$repository=new CanonicalAttendanceRepository();$case=$repository->caseFor($lessonId,$scheduleVersionId);if($case&&!CanonicalAttendanceValidator::validForCase((int)$case->id,$repository,new CanonicalLessonAuthorityRepository(),new CanonicalLessonScheduleRepository()))throw new \InvalidArgumentException('portal_upstream_aggregate_invalid');return array('lesson_id'=>$lessonId,'schedule_version_id'=>$scheduleVersionId,'attendance_state_summary'=>$case?(string)$case->state:'not_recorded','absence_available'=>$case?(string)$case->state==='open':false,'absence_final'=>$case?(string)$case->state==='settled':false); }
    public function submitCapabilityClaim(PublicCapabilityReadSubject $subject,string $redemptionReference):array { if($subject->purpose!=='lesson_absence')throw new \InvalidArgumentException('portal_capability_purpose_mismatch'); if(trim($redemptionReference)==='')throw new \InvalidArgumentException('portal_confirmation_invalid'); return (new CanonicalAttendanceIntakeService())->submitCapabilityClaim($subject,$redemptionReference); }
}
