<?php
namespace Delnavazan\Platform\Core\Application;

use Delnavazan\Platform\Core\Infrastructure\Repository\PrincipalInvitationRepository;

/**
 * 2A.0 owns Core-side invitation authority. WordPress account provisioning is
 * intentionally outside its transaction; finalisation is never attempted on
 * an uncertain external result.
 */
final class PrincipalInvitationService {
    public function __construct(private ?PrincipalInvitationRepository $repo=null){$this->repo??=new PrincipalInvitationRepository();}
    /**
     * Queues a generation and its delivery intent. Issuance deliberately
     * neither creates nor returns a reusable invitation secret.
     */
    public function issue(int $teacherId,string $recipient,int $ttl=604800,?string $command=null):array{
        $this->admin('dzn_issue_teacher_invitations');$recipient=$this->recipient($recipient);$command=$this->key($command??'issue:'.$teacherId.':'.$recipient);$now=current_time('mysql',true);
        $this->repo->begin();try{if($this->repo->eventExists($command)){$this->repo->commit();return['idempotent'=>true];}$teacher=$this->repo->teacherForUpdate($teacherId);if(!$teacher||$teacher->archived_at!==null||$teacher->status!=='active')throw new \InvalidArgumentException('Teacher is not onboarding eligible');$parent=$this->repo->invitationForTeacher($teacherId);if(!$parent){$parentId=$this->repo->insert('teacher_invitations',['teacher_id'=>$teacherId,'recipient_digest'=>hash('sha256',$recipient),'current_generation_number'=>0,'status'=>'active','version'=>1,'created_at'=>$now,'updated_at'=>$now,'created_by'=>get_current_user_id(),'updated_by'=>get_current_user_id()]);$parent=$this->repo->invitationForTeacher($teacherId);}else{$parentId=(int)$parent->id;$this->repo->supersedeUnclaimedGenerations($parentId,$now);$this->repo->cancelPendingDeliveryOutboxes($parentId,$now);}
            $number=(int)$parent->current_generation_number+1;$recipientDigest=hash('sha256',$recipient);$generation=$this->repo->insert('teacher_invitation_generations',['invitation_id'=>$parentId,'generation_number'=>$number,'recipient_snapshot'=>$recipient,'recipient_digest'=>$recipientDigest,'secret_digest'=>null,'status'=>'queued_for_delivery','expires_at'=>gmdate('Y-m-d H:i:s',time()+max(300,$ttl)),'delivery_key'=>$this->key('delivery:'.$parentId.':'.$number),'created_at'=>$now,'created_by'=>get_current_user_id()]);$this->repo->update('teacher_invitations',['recipient_digest'=>$recipientDigest,'current_generation_number'=>$number,'status'=>'active','version'=>(int)$parent->version+1,'updated_at'=>$now,'updated_by'=>get_current_user_id()],['id'=>$parentId]);$this->repo->audit('teacher_invitation',$parentId,'teacher_invitation.queued',get_current_user_id(),$command);$this->repo->outbox($parentId,$generation,'teacher_invitation.delivery_requested',$this->key('outbox:'.$command));$this->repo->commit();return['invitation_id'=>$parentId,'generation_id'=>$generation,'status'=>'queued_for_delivery'];}catch(\Throwable $e){$this->repo->rollback();throw$e;}}

    /**
     * Internal delivery-boundary contract. No route or admin action invokes
     * this method. The recipient is resolved only from the frozen Core-owned
     * generation snapshot; the worker receives it only in the ephemeral send
     * payload. A lost payload is recovered by a replacement generation, never
     * reuse.
     */
    public function prepareDelivery(int $generationId):array{$now=current_time('mysql',true);$this->repo->begin();try{$generation=$this->repo->generationForUpdate($generationId);if(!$generation)throw new \InvalidArgumentException('Invitation generation not found');$parent=$this->repo->invitationForIdForUpdate((int)$generation->invitation_id);$teacher=$parent?$this->repo->teacherForUpdate((int)$parent->teacher_id):null;$outbox=$this->repo->deliveryOutboxForGenerationForUpdate($generationId);$recipient=$generation->recipient_snapshot===null?null:$this->recipient((string)$generation->recipient_snapshot);if(!$parent||!$teacher||$recipient===null||$teacher->archived_at!==null||$teacher->status!=='active'||$parent->status!=='active'||(int)$parent->current_generation_number!==(int)$generation->generation_number||$generation->status!=='queued_for_delivery'||$generation->secret_digest!==null||strtotime($generation->expires_at)<=time()||!$outbox||$outbox->status!=='pending'||$generation->recipient_digest===null||!hash_equals($generation->recipient_digest,hash('sha256',$recipient))||!hash_equals($parent->recipient_digest,hash('sha256',$recipient)))throw new \InvalidArgumentException('Invitation generation is not deliverable');$secret=bin2hex(random_bytes(32));$digest=hash_hmac('sha256',$secret,wp_salt('auth'));if($this->repo->activateQueuedGeneration($generationId,$digest,$now)!==1)throw new \RuntimeException('Invitation generation changed during delivery preparation');if($this->repo->markDeliveryPrepared((int)$outbox->id,$now)!==1)throw new \RuntimeException('Delivery intent changed during preparation');$this->repo->commit();return['invitation_id'=>(int)$parent->id,'generation_id'=>$generationId,'recipient'=>$recipient,'secret'=>$secret,'delivery_key'=>$generation->delivery_key];}catch(\Throwable $e){$this->repo->rollback();throw$e;}}
    public function revoke(int $teacherId,string $reason,?string $command=null):void{$this->admin('dzn_revoke_teacher_invitations');$command=$this->key($command??'revoke:'.$teacherId.':'.$reason);$now=current_time('mysql',true);$this->repo->begin();try{$parent=$this->repo->invitationForTeacher($teacherId);if(!$parent){$this->repo->commit();return;}$this->repo->revokeUnclaimedGenerations((int)$parent->id,$now);$this->repo->cancelPendingDeliveryOutboxes((int)$parent->id,$now);$this->repo->update('teacher_invitations',['status'=>'revoked','version'=>(int)$parent->version+1,'updated_at'=>$now,'updated_by'=>get_current_user_id()],['id'=>$parent->id]);$this->repo->audit('teacher_invitation',(int)$parent->id,'teacher_invitation.revoked',get_current_user_id(),$command,$this->safeReason($reason));$this->repo->commit();}catch(\Throwable$e){$this->repo->rollback();throw$e;}}
    public function beginExistingClaim(string $secret,int $wordpressUserId,string $command):int{$principal=get_userdata($wordpressUserId);if($wordpressUserId<1||get_current_user_id()!==$wordpressUserId||!$principal)throw new \InvalidArgumentException('Authenticated principal ownership and recipient binding required');$claim=$this->beginClaim($secret,$wordpressUserId,$command,'authenticated_principal_pending',null,$this->recipient((string)$principal->user_email));return$claim['attempt_id'];}
    public function beginProvisioning(string $secret,string $command):array{$claim=$this->beginClaim($secret,null,$command,'provisioning_pending',bin2hex(random_bytes(16)));return['attempt_id'=>$claim['attempt_id'],'provisioning_marker'=>$claim['provisioning_marker'],'recipient'=>$claim['recipient']];}
    public function recordProvisioningResult(string $command,?int $wordpressUserId,bool $certain):void{$attempt=$this->repo->attemptForCommand($this->key($command));if(!$attempt)throw new \InvalidArgumentException('Claim attempt not found');$state=$certain&&$wordpressUserId?'principal_ready':'recovery_required';$this->repo->update('account_claim_attempts',['wordpress_user_id'=>$wordpressUserId,'state'=>$state,'recovery_reason'=>$certain?null:'uncertain_wordpress_result','updated_at'=>current_time('mysql',true)],['id'=>$attempt->id]);}
    public function finalizeClaim(string $command,int $wordpressUserId):void{$command=$this->key($command);$this->repo->begin();try{$attempt=$this->repo->attemptForCommand($command);if(!$attempt)throw new \InvalidArgumentException('Claim attempt not found');if($attempt->state==='finalized'){$this->repo->commit();return;}if(!in_array($attempt->state,['authenticated_principal_pending','principal_ready','finalization_pending'],true)||$wordpressUserId<1)throw new \InvalidArgumentException('Claim is not finalisable');$generation=$this->repo->generationForUpdate((int)$attempt->generation_id);if(!$generation||$generation->status!=='active'||strtotime($generation->expires_at)<time())throw new \InvalidArgumentException('Invitation generation is no longer claimable');$parent=$this->repo->invitationForIdForUpdate((int)$attempt->invitation_id);if(!$parent||$parent->status!=='active'||(int)$parent->current_generation_number!==(int)$generation->generation_number)throw new \InvalidArgumentException('Invitation has been superseded');$teacher=$this->repo->teacherForUpdate((int)$parent->teacher_id);if(!$teacher||$teacher->status!=='active'||$teacher->archived_at!==null)throw new \InvalidArgumentException('Teacher is no longer eligible');if($this->repo->activeTeacherLinkForUser($wordpressUserId)||$this->repo->activeTeacherLinkForTeacher((int)$teacher->id))throw new \InvalidArgumentException('Teacher principal link already exists');$now=current_time('mysql',true);$this->repo->insert('teacher_principal_links',['teacher_id'=>$teacher->id,'wordpress_user_id'=>$wordpressUserId,'status'=>'active','linked_at'=>$now,'linked_by'=>get_current_user_id()?:null]);$onboarding=$this->repo->onboardingForTeacher((int)$teacher->id);if($onboarding)$this->repo->update('teacher_onboarding_states',['state'=>'active','readiness_state'=>'ready','version'=>(int)$onboarding->version+1,'updated_at'=>$now],['id'=>$onboarding->id]);else$this->repo->insert('teacher_onboarding_states',['teacher_id'=>$teacher->id,'state'=>'active','readiness_state'=>'ready','version'=>1,'created_at'=>$now,'updated_at'=>$now]);$this->repo->update('teacher_invitation_generations',['status'=>'claimed','claimed_at'=>$now],['id'=>$generation->id,'status'=>'active']);$this->repo->update('account_claim_attempts',['wordpress_user_id'=>$wordpressUserId,'state'=>'finalized','finalized_at'=>$now,'updated_at'=>$now],['id'=>$attempt->id]);$this->repo->audit('teacher',(int)$teacher->id,'teacher_principal.claim_finalized',get_current_user_id()?:null,$this->key('audit:'.$command));$this->repo->commit();}catch(\Throwable$e){$this->repo->rollback();throw$e;}}
    public function offboard(int $teacherId,string $reason):void{$this->admin('dzn_relink_teacher_principal');$this->repo->begin();try{$teacher=$this->repo->teacherForUpdate($teacherId);if(!$teacher)throw new \InvalidArgumentException('Teacher not found');$now=current_time('mysql',true);$parent=$this->repo->invitationForTeacher($teacherId);if($parent){$this->repo->revokeUnclaimedGenerations((int)$parent->id,$now);$this->repo->cancelPendingDeliveryOutboxes((int)$parent->id,$now);$this->repo->update('teacher_invitations',['status'=>'revoked','version'=>(int)$parent->version+1,'updated_at'=>$now,'updated_by'=>get_current_user_id()],['id'=>$parent->id]);}$this->repo->update('teacher_principal_links',['status'=>'revoked','revoked_at'=>$now,'revoked_by'=>get_current_user_id(),'reason_code'=>$this->safeReason($reason)],['teacher_id'=>$teacherId,'status'=>'active']);$state=$this->repo->onboardingForTeacher($teacherId);if($state)$this->repo->update('teacher_onboarding_states',['state'=>'offboarded','readiness_state'=>'not_ready','version'=>(int)$state->version+1,'updated_at'=>$now],['id'=>$state->id]);$this->repo->audit('teacher',$teacherId,'teacher_principal.offboarded',get_current_user_id(),$this->key('offboard:'.$teacherId.':'.$reason),$this->safeReason($reason));$this->repo->commit();}catch(\Throwable$e){$this->repo->rollback();throw$e;}}
    public function anonymizeTerminalInvitationRecipient(int $teacherId,string $reason):void{$this->admin('dzn_relink_teacher_principal');$this->repo->begin();try{$parent=$this->repo->invitationForTeacher($teacherId);if(!$parent){$this->repo->commit();return;}if($this->repo->hasNonterminalGeneration((int)$parent->id))throw new \InvalidArgumentException('Nonterminal invitation recipient cannot be anonymized');$this->repo->anonymizeTerminalRecipientSnapshots((int)$parent->id);$this->repo->anonymizeInvitationRecipientDigest((int)$parent->id);$this->repo->audit('teacher_invitation',(int)$parent->id,'teacher_invitation.recipient_anonymized',get_current_user_id(),$this->key('recipient-anonymized:'.$teacherId.':'.$reason),$this->safeReason($reason));$this->repo->commit();}catch(\Throwable$e){$this->repo->rollback();throw$e;}}
    private function beginClaim(string $secret,?int $user,string $command,string $state,?string $marker,?string $authenticatedRecipient=null):array{$command=$this->key($command);$digest=hash_hmac('sha256',$secret,wp_salt('auth'));$this->repo->begin();try{$existing=$this->repo->attemptForCommand($command);if($existing){$this->repo->commit();return['attempt_id'=>(int)$existing->id,'provisioning_marker'=>$existing->provisioning_marker,'recipient'=>null];}$generation=$this->repo->generationForSecretForUpdate($digest);$recipient=$generation&&$generation->recipient_snapshot!==null?$this->recipient((string)$generation->recipient_snapshot):null;if(!$generation||$recipient===null||$generation->recipient_digest===null||$generation->status!=='active'||$generation->parent_status!=='active'||(int)$generation->current_generation_number!==(int)$generation->generation_number||strtotime($generation->expires_at)<time()||!hash_equals($generation->recipient_digest,hash('sha256',$recipient))||!hash_equals($generation->parent_recipient_digest,hash('sha256',$recipient))||($authenticatedRecipient!==null&&!hash_equals($recipient,$authenticatedRecipient)))throw new \InvalidArgumentException('Invitation is invalid or unavailable');$id=$this->repo->insert('account_claim_attempts',['invitation_id'=>$generation->invitation_id,'generation_id'=>$generation->id,'domain'=>'teacher','command_key'=>$command,'wordpress_user_id'=>$user,'state'=>$state,'provisioning_marker'=>$marker,'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)]);$this->repo->commit();return['attempt_id'=>$id,'provisioning_marker'=>$marker,'recipient'=>$recipient];}catch(\Throwable$e){$this->repo->rollback();throw$e;}}
    private function teacherForInvitation(int $id):object{global$wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}dzn_teacher_invitations WHERE id=%d FOR UPDATE",$id));if(!$row)throw new \InvalidArgumentException('Invitation not found');return$row;}
    private function admin(string $cap):void{if(!current_user_can($cap))throw new \RuntimeException('Unauthorized');}
    private function recipient(string $value):string{$value=strtolower(trim($value));if(!is_email($value))throw new \InvalidArgumentException('Valid recipient email required');return$value;}
    private function key(string $value):string{return hash('sha256',$value);}
    private function safeReason(string $reason):string{return substr(sanitize_key($reason),0,64);}
}
