<?php
namespace Delnavazan\Platform\Core\Application;
use Delnavazan\Platform\Core\Infrastructure\Repository\{BookingRequestRepository,StudentIdentityAuthorityRepository};
use Delnavazan\Platform\Core\Support\Identifier;

/** Writes only reviewed capacity and authority facts; it never accepts a service arrangement. */
final class StudentAcceptanceAuthorityService {
    public function __construct(private ?BookingRequestRepository $transactions=null,private ?StudentIdentityAuthorityRepository $records=null){$this->transactions??=new BookingRequestRepository();$this->records??=new StudentIdentityAuthorityRepository();}
    public function classify(int $studentId,string $classification,string $basis,string $channel,string $evidenceAt,int $actor):int{if(!in_array($classification,array('adult','minor','unknown'),true))throw new \InvalidArgumentException('Invalid capacity classification');[$basis,$channel,$evidenceAt]=$this->evidence($basis,$channel,$evidenceAt);return $this->transaction(function()use($studentId,$classification,$basis,$channel,$evidenceAt,$actor){$student=$this->records->studentForUpdate($studentId);if(!$student||$student->status!=='active'||$student->archived_at!==null)throw new \InvalidArgumentException('Student is not active');$now=gmdate('Y-m-d H:i:s');$prior=$this->records->currentCapacityForUpdate($studentId);do_action('dzn_phase_2a2f_capacity_locks_held');$id=$this->records->insertCapacity(array('uid'=>Identifier::uid(),'student_id'=>$studentId,'classification'=>$classification,'verification_basis'=>$basis,'evidence_channel'=>$channel,'evidence_reference'=>'capacity-classification-'.Identifier::uid(),'evidence_at'=>$evidenceAt,'classified_at'=>$now,'classified_by'=>$actor,'supersedes_classification_id'=>$prior?->id,'created_at'=>$now,'created_by'=>$actor));$this->records->setCapacityProjection($studentId,$id,$actor,$now);return $id;});}
    public function establishPrincipal(int $studentId,int $userId,string $basis,string $channel,string $evidenceAt,int $actor):int{[$basis,$channel,$evidenceAt]=$this->evidence($basis,$channel,$evidenceAt);return $this->transaction(function()use($studentId,$userId,$basis,$channel,$evidenceAt,$actor){$this->activeStudent($studentId);$this->assertUser($userId);if($this->records->activePrincipalForStudentForUpdate($studentId)||$this->records->activePrincipalForUserForUpdate($userId)||$this->records->activeGuardianForUserForUpdate($userId))throw new \InvalidArgumentException('A current Student principal or guardian authority already exists');do_action('dzn_phase_2a2f_authority_locks_held');$now=gmdate('Y-m-d H:i:s');return $this->records->insertPrincipal(array('student_id'=>$studentId,'wordpress_user_id'=>$userId,'status'=>'active','link_sequence'=>$this->records->nextPrincipalSequence($studentId),'active_slot'=>1,'version'=>1,'verification_basis'=>$basis,'evidence_channel'=>$channel,'evidence_reference'=>'student-principal-link-'.Identifier::uid(),'evidence_at'=>$evidenceAt,'linked_at'=>$now,'linked_by'=>$actor,'updated_at'=>$now,'updated_by'=>$actor,'revoked_at'=>null,'revoked_by'=>null,'reason_code'=>null));});}
    public function revokePrincipal(int $linkId,int $version,string $reason,int $actor):void{if(!preg_match('/^[a-z0-9_]{3,64}$/D',$reason))throw new \InvalidArgumentException('Invalid reason code');$this->transaction(function()use($linkId,$version,$reason,$actor){$this->records->revokePrincipal($linkId,$version,$actor,$reason,gmdate('Y-m-d H:i:s'));});}
    public function grantGuardian(int $studentId,int $userId,string $basis,string $channel,string $evidenceAt,?string $effectiveUntil,int $actor):int{[$basis,$channel,$evidenceAt]=$this->evidence($basis,$channel,$evidenceAt);if($effectiveUntil!==null&&!preg_match('/^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$/D',$effectiveUntil))throw new \InvalidArgumentException('Invalid authority end date');return $this->transaction(function()use($studentId,$userId,$basis,$channel,$evidenceAt,$effectiveUntil,$actor){$this->activeStudent($studentId);$this->assertUser($userId);if($this->records->activePrincipalForUserForUpdate($userId))throw new \InvalidArgumentException('Student principal cannot be guardian authority');if($this->records->activeGrantForUpdate($studentId,$userId))throw new \InvalidArgumentException('A current guardian grant already exists');do_action('dzn_phase_2a2f_authority_locks_held');$now=gmdate('Y-m-d H:i:s');return $this->records->insertGrant(array('uid'=>Identifier::uid(),'reference_code'=>null,'student_id'=>$studentId,'acting_wordpress_user_id'=>$userId,'authority_type'=>'guardian_representative','authority_scope'=>'service_acceptance','state'=>'active','active_slot'=>1,'effective_from'=>$now,'effective_until'=>$effectiveUntil,'verification_basis'=>$basis,'evidence_channel'=>$channel,'evidence_reference'=>'guardian-authority-grant-'.Identifier::uid(),'evidence_at'=>$evidenceAt,'version'=>1,'granted_at'=>$now,'granted_by'=>$actor,'revoked_at'=>null,'revoked_by'=>null,'superseded_at'=>null,'superseded_by_grant_id'=>null,'reason_code'=>null,'created_at'=>$now,'updated_at'=>$now,'created_by'=>$actor,'updated_by'=>$actor));});}
    public function revokeGuardian(int $grantId,int $version,string $reason,int $actor):void{if(!preg_match('/^[a-z0-9_]{3,64}$/D',$reason))throw new \InvalidArgumentException('Invalid reason code');$this->transaction(function()use($grantId,$version,$reason,$actor){$this->records->revokeGrant($grantId,$version,$actor,$reason,gmdate('Y-m-d H:i:s'));});}
    public function supersedeGuardian(int $grantId,int $version,int $nextUserId,string $basis,string $channel,string $evidenceAt,?string $effectiveUntil,string $reason,int $actor):int{if(!preg_match('/^[a-z0-9_]{3,64}$/D',$reason))throw new \InvalidArgumentException('Invalid reason code');[$basis,$channel,$evidenceAt]=$this->evidence($basis,$channel,$evidenceAt);if($effectiveUntil!==null&&!preg_match('/^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$/D',$effectiveUntil))throw new \InvalidArgumentException('Invalid authority end date');return $this->transaction(function()use($grantId,$version,$nextUserId,$basis,$channel,$evidenceAt,$effectiveUntil,$reason,$actor){$current=$this->records->grantForUpdate($grantId);if(!$current||$current->state!=='active'||(int)$current->active_slot!==1||$current->authority_type!=='guardian_representative'||$current->authority_scope!=='service_acceptance'||(int)$current->version!==$version)throw new \InvalidArgumentException('Acceptance authority grant is no longer current');$this->activeStudent((int)$current->student_id);$this->assertUser($nextUserId);if((int)$current->acting_wordpress_user_id===$nextUserId||$this->records->activePrincipalForUserForUpdate($nextUserId)||$this->records->activeGrantForUpdate((int)$current->student_id,$nextUserId))throw new \InvalidArgumentException('Replacement guardian authority is unavailable');$now=gmdate('Y-m-d H:i:s');$this->records->markGrantSuperseded($grantId,$version,$actor,$reason,$now);$next=$this->records->insertGrant(array('uid'=>Identifier::uid(),'reference_code'=>null,'student_id'=>$current->student_id,'acting_wordpress_user_id'=>$nextUserId,'authority_type'=>'guardian_representative','authority_scope'=>'service_acceptance','state'=>'active','active_slot'=>1,'effective_from'=>$now,'effective_until'=>$effectiveUntil,'verification_basis'=>$basis,'evidence_channel'=>$channel,'evidence_reference'=>'guardian-authority-grant-'.Identifier::uid(),'evidence_at'=>$evidenceAt,'version'=>1,'granted_at'=>$now,'granted_by'=>$actor,'revoked_at'=>null,'revoked_by'=>null,'superseded_at'=>null,'superseded_by_grant_id'=>null,'reason_code'=>null,'created_at'=>$now,'updated_at'=>$now,'created_by'=>$actor,'updated_by'=>$actor));$this->records->setSupersedingGrant($grantId,$next);return $next;});}
    private function transaction(callable $operation):mixed{$this->transactions->begin();try{$result=$operation();$this->transactions->commit();return$result;}catch(\Throwable $e){$this->transactions->rollback();throw$e;}}
    private function activeStudent(int $studentId):void{$student=$this->records->studentForUpdate($studentId);if(!$student||$student->status!=='active'||$student->archived_at!==null)throw new \InvalidArgumentException('Student is not active');}
    private function assertUser(int $userId):void{if($userId<1||!$this->records->wordpressUserForUpdate($userId))throw new \InvalidArgumentException('WordPress user does not exist');}
    private function evidence(string $basis,string $channel,string $at):array{if(!in_array($basis,array('human_review','verified_internal_record','legal_representative_review','synthetic_fixture'),true)||!in_array($channel,array('internal_case','reviewer_attestation','verified_internal_record','synthetic_fixture'),true)||!preg_match('/^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$/D',$at))throw new \InvalidArgumentException('Invalid reviewed evidence metadata');return array($basis,$channel,$at);}
}
