<?php
namespace Delnavazan\Platform\Core\Application;
use Delnavazan\Platform\Core\Infrastructure\Repository\{BookingRequestRepository,StudentIdentityAuthorityRepository};
use Delnavazan\Platform\Core\Support\Identifier;

/** Human-reviewed only: this service never derives a Student from request contacts or a WordPress account. */
final class StudentIdentityResolutionService {
    public function __construct(private ?BookingRequestRepository $transactions=null,private ?StudentIdentityAuthorityRepository $records=null){$this->transactions??=new BookingRequestRepository();$this->records??=new StudentIdentityAuthorityRepository();}
    public function resolveExisting(int $requestId,int $studentId,string $basis,string $channel,string $evidenceAt,int $actor):int{return $this->record($requestId,'resolved',$studentId,$basis,$channel,$evidenceAt,$actor);}
    public function createAndResolve(int $requestId,array $student,string $basis,string $channel,string $evidenceAt,int $actor):int{[$basis,$channel,$evidenceAt]=$this->evidence($basis,$channel,$evidenceAt);$name=trim((string)($student['display_name']??''));if($name==='')throw new \InvalidArgumentException('Student display name is required');$this->transactions->begin();try{$request=$this->eligibleRequest($requestId);do_action('dzn_phase_2a2f_identity_resolution_locks_held');$now=gmdate('Y-m-d H:i:s');$newId=$this->records->createStudent(array('uid'=>Identifier::uid(),'reference_code'=>null,'status'=>'active','display_name'=>$name,'created_at'=>$now,'updated_at'=>$now,'created_by'=>$actor,'updated_by'=>$actor));$event=$this->append($request,$newId,'resolved',$basis,$channel,$evidenceAt,$actor,$now);$this->transactions->commit();return $event;}catch(\Throwable $e){$this->transactions->rollback();throw $e;}}
    public function recordOutcome(int $requestId,string $outcome,string $basis,string $channel,string $evidenceAt,int $actor):int{if(!in_array($outcome,array('unresolved','ambiguous','rejected'),true))throw new \InvalidArgumentException('Invalid identity outcome');return $this->record($requestId,$outcome,null,$basis,$channel,$evidenceAt,$actor);}
    private function record(int $requestId,string $outcome,?int $studentId,string $basis,string $channel,string $evidenceAt,int $actor):int{[$basis,$channel,$evidenceAt]=$this->evidence($basis,$channel,$evidenceAt);$this->transactions->begin();try{$request=$this->eligibleRequest($requestId);if($outcome==='resolved'){if(!$studentId||!$this->records->studentForUpdate($studentId))throw new \InvalidArgumentException('Student does not exist');}do_action('dzn_phase_2a2f_identity_resolution_locks_held');$event=$this->append($request,$studentId,$outcome,$basis,$channel,$evidenceAt,$actor,gmdate('Y-m-d H:i:s'));$this->transactions->commit();return $event;}catch(\Throwable $e){$this->transactions->rollback();throw $e;}}
    private function eligibleRequest(int $requestId):object{$request=$this->records->requestForUpdate($requestId);if(!$request||$request->lifecycle_status!=='submitted'||$request->resolution_state!=='unresolved'||$request->privacy_erased_at!==null)throw new \InvalidArgumentException('Booking Request identity cannot be resolved');$current=$this->records->currentResolutionForUpdate($requestId);if($request->student_id!==null||($current&&$current->outcome==='resolved'))throw new \InvalidArgumentException('Booking Request identity is already resolved');return $request;}
    private function append(object $request,?int $studentId,string $outcome,string $basis,string $channel,string $evidenceAt,int $actor,string $now):int{$previous=$this->records->currentResolutionForUpdate((int)$request->id);$event=$this->records->insertResolution(array('uid'=>Identifier::uid(),'reference_code'=>null,'booking_request_id'=>$request->id,'prospective_subject_ref'=>$request->prospective_subject_ref,'resolution_sequence'=>$this->records->nextResolutionSequence($request->id),'outcome'=>$outcome,'student_id'=>$studentId,'verification_basis'=>$basis,'evidence_channel'=>$channel,'evidence_reference'=>'identity-resolution-'.Identifier::uid(),'evidence_at'=>$evidenceAt,'verified_at'=>$now,'verified_by'=>$actor,'supersedes_resolution_event_id'=>$previous?->id,'created_at'=>$now,'created_by'=>$actor));$this->records->setResolutionProjection($request->id,$event,$studentId,$actor,$now);return $event;}
    private function evidence(string $basis,string $channel,string $at):array{if(!in_array($basis,array('human_review','verified_internal_record','legal_representative_review','synthetic_fixture'),true)||!in_array($channel,array('internal_case','reviewer_attestation','verified_internal_record','synthetic_fixture'),true)||!preg_match('/^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$/D',$at))throw new \InvalidArgumentException('Invalid reviewed evidence metadata');return array($basis,$channel,$at);}
}
