<?php
namespace Delnavazan\Platform\Core\Application;
use Delnavazan\Platform\Core\Infrastructure\Repository\StudentIdentityAuthorityRepository;

/** Informational eligibility only. It is not a bearer credential or final acceptance authority. */
final class StudentAcceptanceAuthorityReadService {
    public function __construct(private ?StudentIdentityAuthorityRepository $records=null){$this->records??=new StudentIdentityAuthorityRepository();}
    public function assess(int $bookingRequestId,int $actingPrincipalId):array{if(!current_user_can('dzn_view_student_acceptance_eligibility'))throw new \RuntimeException('Access denied');$row=$this->records->eligibilityRows($bookingRequestId,$actingPrincipalId,gmdate('Y-m-d H:i:s'));$result=array('eligible_adult_self'=>false,'eligible_guardian'=>false,'blocked_identity_unresolved'=>false,'blocked_capacity_unresolved'=>false,'blocked_authority_missing'=>false,'blocked_student_unavailable'=>false,'blocked_request_privacy_erased'=>false);if(!$row)return$result;if($row->privacy_erased_at!==null||$row->resolution_state==='privacy_erased'){$result['blocked_request_privacy_erased']=true;return$result;}if($row->lifecycle_status!=='submitted'||$row->resolution_state!=='unresolved'||$row->student_id===null||$row->outcome!=='resolved'||(int)$row->event_student_id!==(int)$row->student_id){$result['blocked_identity_unresolved']=true;return$result;}if($row->student_status!=='active'||$row->archived_at!==null){$result['blocked_student_unavailable']=true;return$result;}if(!$row->current_acceptance_capacity_classification_id||!in_array($row->classification,array('adult','minor'),true)){$result['blocked_capacity_unresolved']=true;return$result;}if($row->classification==='adult')$result['eligible_adult_self']=(bool)$row->principal_id;else$result['eligible_guardian']=(bool)$row->guardian_grant_id;if(!$result['eligible_adult_self']&&!$result['eligible_guardian'])$result['blocked_authority_missing']=true;return$result;}
}
