<?php
if(getenv('DZN_PHASE_2A2I_RUNTIME_TEST')!=='concurrency'||!defined('WP_CLI')||!WP_CLI){fwrite(STDERR,"Phase 2A.2-I worker refused.\n");exit(1);}
use Delnavazan\Platform\Core\Application\{BookingRequestPrivacyService,EnrolmentConversionService,IdempotencyConflictException};
global$wpdb;$state=get_option('dzn_phase_2a2i_race_state');$name=(string)getenv('DZN_PHASE_2A2I_WORKER');$action=(string)getenv('DZN_PHASE_2A2I_ACTION');$gate=(string)getenv('DZN_PHASE_2A2I_GATE_DIR');if(!is_array($state)||!in_array($name,array('w1','w2'),true)||!is_dir($gate))throw new RuntimeException('Invalid Phase I worker state');
$touch=static function(string$file,string$value='')use($gate):void{file_put_contents($gate.'/'.$file,$value);};$touch($name.'.connection',(string)$wpdb->get_var('SELECT CONNECTION_ID()'));$touch($name.'.started');
$waitFor=static function(string$file)use($gate):void{for($i=0;$i<600&&!is_file($gate.'/'.$file);$i++)usleep(100000);if(!is_file($gate.'/'.$file))throw new RuntimeException('Release gate timeout: '.$file);};
$hold=static function()use($touch,$name,$waitFor):void{$touch($name.'.locked');$waitFor('release');};
if(($state['mode']??'')==='a'){$sourceGate=static function(int$sourceId,int$familyId,int$studentId,int$courseId)use($touch,$name,$waitFor):void{$touch($name.'.source_locked',implode(':',array($sourceId,$familyId,$studentId,$courseId)));$waitFor('converge.'.$name);};add_action('dzn_phase_2a2i_source_lineage_locked',$sourceGate,10,4);}
if(($state['holder']??'')===$name){$hook=$action==='erase'?'dzn_phase_2a2e_privacy_locks_held':(($state['mode']==='u1'||$state['mode']==='u2')?'dzn_phase_2a2i_identity_root_locked':'dzn_phase_2a2i_conversion_locks_held');add_action($hook,$hold);}
$target=$name==='w1'?$state['one']:$state['two'];try{if($action==='erase'){(new BookingRequestPrivacyService())->erase((int)$target['request_id'],get_current_user_id(),'synthetic_race');echo"outcome=erased\n";}else{$key=$name==='w1'?$state['key1']:$state['key2'];$result=(new EnrolmentConversionService())->convert((int)$target['arrangement_id'],$key);$outcome=$result['created']?'created':($result['already_converted']?'already_converted':($result['idempotent']?'replay':'unknown'));echo"outcome={$outcome} enrolment={$result['enrolment_id']}\n";}}catch(IdempotencyConflictException$e){echo"outcome=idempotency_conflict class=".$e::class."\n";}catch(InvalidArgumentException$e){echo"outcome=".$e->getMessage()." class=".$e::class."\n";}finally{$touch($name.'.finished');}
