<?php
/** Disposable exact Schema 14 -> 15 migration and capability repair proof. */
if(getenv('DZN_PHASE_2A2I_RUNTIME_TEST')!=='migration'||!defined('WP_CLI')||!WP_CLI||!in_array(wp_get_environment_type(),array('local','development'),true)){fwrite(STDERR,"Phase 2A.2-I migration runtime refused.\n");exit(1);}
if((string)DZN_PLATFORM_SCHEMA_VERSION!=='15'||DZN_PLATFORM_BUILD_ID!=='phase2a2i-enrolment-conversion-authority-20260914.1')throw new RuntimeException('Exact Phase I candidate required');
use Delnavazan\Platform\Core\Infrastructure\Migration\Migrator;
global$wpdb;$p=$wpdb->prefix.'dzn_';
function dzn_2a2i_m_assert(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);}
function dzn_2a2i_m_index(string$table,string$name,array$columns):bool{global$wpdb;$rows=$wpdb->get_results($wpdb->prepare("SHOW INDEX FROM {$table} WHERE Key_name=%s",$name));if(!$rows||(int)$rows[0]->Non_unique!==0)return false;usort($rows,static fn($a,$b)=>(int)$a->Seq_in_index<=>(int)$b->Seq_in_index);return array_map(static fn($r)=>(string)$r->Column_name,$rows)===$columns;}
dzn_2a2i_m_assert((string)get_option('dzn_platform_schema_version')==='15','Schema 14 -> 15 failed');$done=(array)get_option('dzn_platform_completed_migrations',array());dzn_2a2i_m_assert(count(array_keys($done,'015_enrolment_conversion_authority',true))===1,'Migration 015 ledger invalid');
foreach(array('enrolment_identity_roots','enrolment_conversion_commands')as$table){$physical=$p.$table;dzn_2a2i_m_assert($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$physical))===$physical,'Missing '.$table);dzn_2a2i_m_assert(strcasecmp((string)$wpdb->get_var($wpdb->prepare('SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s',$physical)),'InnoDB')===0,'Non-InnoDB '.$table);dzn_2a2i_m_assert(!$wpdb->get_row("SHOW COLUMNS FROM {$physical} LIKE 'updated_at'"),'Mutable conversion table '.$table);}
foreach(array(array('enrolment_identity_roots','student_course',array('student_id','course_id')),array('enrolment_conversion_commands','uid',array('uid')),array('enrolment_conversion_commands','command_key_digest',array('command_key_digest')),array('enrolment_conversion_commands','accepted_service_arrangement_id',array('accepted_service_arrangement_id')),array('enrolment_conversion_commands','enrolment_id',array('enrolment_id')))as[$table,$index,$columns])dzn_2a2i_m_assert(dzn_2a2i_m_index($p.$table,$index,$columns),'Incorrect unique index '.$table.'.'.$index);
$role=get_role('administrator');dzn_2a2i_m_assert($role&&$role->has_cap('dzn_convert_service_arrangements_to_enrolments'),'Conversion capability installation failed');$role->remove_cap('dzn_convert_service_arrangements_to_enrolments');Migrator::maybe_upgrade();dzn_2a2i_m_assert($role->has_cap('dzn_convert_service_arrangements_to_enrolments'),'Conversion capability repair failed');
$before=array((int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}enrolment_identity_roots"),(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}enrolment_conversion_commands"));Migrator::maybe_upgrade();$after=array((int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}enrolment_identity_roots"),(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}enrolment_conversion_commands"));$done=(array)get_option('dzn_platform_completed_migrations',array());dzn_2a2i_m_assert($before===$after&&count(array_keys($done,'015_enrolment_conversion_authority',true))===1,'Repeated Migration 015 changed state');
echo"schema_14_to_15=pass\nmigration_015=pass\ncapability_install_repair=pass\nrepeat_upgrade=pass\nPhase 2A.2-I migration runtime passed\n";
