<?php
/** Builds all A-D/X targets from the established synthetic Phase 2A.2-D fixture. */
if(getenv('DZN_PHASE_2A2E_RUNTIME_TEST')!=='isolated'||!defined('WP_CLI')||!WP_CLI||!in_array(wp_get_environment_type(),array('local','development'),true)){fwrite(STDERR,"Phase 2A.2-E concurrency fixture refused.\n");exit(1);}
use Delnavazan\Platform\Core\Application\ProposalService;
function dzn_2a2e_fixture_assert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
global $wpdb;$p=$wpdb->prefix.'dzn_';$source=get_option('dzn_phase_2a2d_fixture');if(!is_array($source))throw new RuntimeException('Established synthetic Phase 2A.2-D fixture unavailable');
$inputs=array('a'=>array($source['candidate_a']??0,$source['fingerprint_a1']??''),'b'=>array($source['candidate_b']??0,$source['fingerprint_b1']??''),'c1'=>array($source['race_initial']['candidate_id']??0,$source['race_initial']['fingerprint']??''),'c2'=>array($source['race_invalidation']['candidate_id']??0,$source['race_invalidation']['initial_fingerprint']??''));
$service=new ProposalService();$targets=array();foreach($inputs as$label=>$input){[$candidate,$fingerprint]=$input;dzn_2a2e_fixture_assert($candidate>0&&preg_match('/^[a-f0-9]{64}$/D',$fingerprint),'Synthetic fixture input missing: '.$label);$existing=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}proposal_versions WHERE candidate_id=%d",$candidate));dzn_2a2e_fixture_assert($existing===0,'Disposable fixture is not fresh: '.$label);$issued=$service->issueInitial($candidate,$fingerprint,'dzn-2a2e-fixture-'.$label.'-'.substr(hash('sha256',wp_generate_uuid4()),0,30));$version=$wpdb->get_row($wpdb->prepare("SELECT prospective_subject_ref,booking_request_id FROM {$p}proposal_versions WHERE id=%d",$issued['version_id']));dzn_2a2e_fixture_assert(str_starts_with((string)$version->prospective_subject_ref,'booking_request:'),'Fixture carries a contact value instead of the canonical synthetic subject reference: '.$label);$targets[$label]=array('family_uid'=>$issued['family_uid'],'option_uid'=>$issued['option_uid'],'version_number'=>$issued['version_number'],'prospective_subject_ref'=>$version->prospective_subject_ref,'request_id'=>$version->booking_request_id,'option_id'=>$issued['option_id'],'expected_version'=>$issued['version_number']);}
$targets['c1']['replacement_fingerprint']=$source['race_revision']['replacement_fingerprint']??'';$targets['c2']['replacement_fingerprint']=$source['race_invalidation']['replacement_fingerprint']??'';foreach(array('c1','c2')as$label)dzn_2a2e_fixture_assert(preg_match('/^[a-f0-9]{64}$/D',$targets[$label]['replacement_fingerprint']),'Synthetic replacement fingerprint missing: '.$label);
$fixture=array('synthetic_domain'=>'phase-2a2e.invalid','a'=>$targets['a']+array('a1'=>array('channel'=>'message_reference'),'a2'=>array('channel'=>'message_reference')),'b'=>$targets['b']+array('b1'=>array('channel'=>'message_reference'),'b2'=>array('channel'=>'phone')),'c1'=>$targets['c1']+array('c1'=>array('channel'=>'message_reference'),'c2'=>array('channel'=>'message_reference')),'c2'=>$targets['c2']+array('c1'=>array('channel'=>'message_reference'),'c2'=>array('channel'=>'message_reference')),'d1'=>$targets['a']+array('d1'=>array('channel'=>'message_reference'),'d2'=>array('channel'=>'message_reference')),'d2'=>$targets['b']+array('d1'=>array('channel'=>'message_reference'),'d2'=>array('channel'=>'message_reference')),'x'=>$targets['c1']+array('x1'=>$targets['c1']+array('channel'=>'message_reference'),'x2'=>$targets['c2']+array('channel'=>'phone')));
update_option('dzn_phase_2a2e_concurrency_fixture',$fixture,false);echo "Phase 2A.2-E synthetic concurrency fixture passed\n";
