<?php
/** Disposable Schema 17 -> 18 and canonical Term command runtime proof. */
if(getenv('DZN_PHASE_2A2L_RUNTIME_TEST')!=='authority'||!defined('WP_CLI')||!WP_CLI||!in_array(wp_get_environment_type(),array('local','development'),true)){fwrite(STDERR,"Phase 2A.2-L runtime refused.\n");exit(1);}if((string)DZN_PLATFORM_SCHEMA_VERSION!=='18'||DZN_PLATFORM_BUILD_ID!=='phase2a2l-canonical-term-authority-20260916.1')throw new RuntimeException('Exact Phase L candidate required');
use Delnavazan\Platform\Core\Application\{CanonicalTermAuthorityService,IdempotencyConflictException,TermApplicabilityAssessment};use Delnavazan\Platform\Core\Infrastructure\Migration\Migrator;use Delnavazan\Platform\Core\Support\Identifier;
global$wpdb;$p=$wpdb->prefix.'dzn_';function dzn_l_assert(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);}function dzn_l_parent():int{global$wpdb;$p=$wpdb->prefix.'dzn_';$now=gmdate('Y-m-d H:i:s');$seed=random_int(700000000,900000000);dzn_l_assert($wpdb->insert($p.'enrolments',array('uid'=>Identifier::uid(),'reference_code'=>null,'student_id'=>$seed,'teacher_id'=>null,'course_id'=>$seed,'status'=>'canonical','record_model'=>'canonical_student_course_v1','accepted_service_arrangement_id'=>$seed,'lifecycle_state'=>'authorised','applicable_slot'=>1,'predecessor_enrolment_id'=>null,'lineage_meaning'=>null,'created_at'=>$now,'updated_at'=>$now,'created_by'=>get_current_user_id(),'updated_by'=>get_current_user_id()))===1,'Parent fixture failed: '.$wpdb->last_error);return(int)$wpdb->insert_id;}function dzn_l_evidence(string$ref):array{return array('evidence_channel'=>'staff_record','evidence_reference'=>$ref,'evidence_at'=>gmdate('Y-m-d H:i:s'));}
// Prove 17 -> 18 migration, immutable command schema, repair and repeatability.
$wpdb->query("DROP TABLE IF EXISTS {$p}term_commands");$done=array_values(array_filter((array)get_option('dzn_platform_completed_migrations',array()),static fn($id)=>$id!=='018_canonical_term_authority'));update_option('dzn_platform_completed_migrations',$done,false);update_option('dzn_platform_schema_version','17',false);update_option('dzn_platform_capability_version','2a2k',false);$admin=get_role('administrator');$admin->remove_cap('dzn_manage_canonical_terms');Migrator::maybe_upgrade();
dzn_l_assert((string)get_option('dzn_platform_schema_version')==='18'&&count(array_keys((array)get_option('dzn_platform_completed_migrations',array()),'018_canonical_term_authority',true))===1,'17 -> 18 ledger failed');dzn_l_assert($admin->has_cap('dzn_manage_canonical_terms')&&!get_role('dzn_teacher')->has_cap('dzn_manage_canonical_terms'),'Capability boundary failed');dzn_l_assert(!$wpdb->get_row("SHOW COLUMNS FROM {$p}term_commands LIKE 'updated_at'")&&!$wpdb->get_row("SHOW COLUMNS FROM {$p}term_commands LIKE 'raw_key'"),'Command evidence is mutable/raw');
$service=new CanonicalTermAuthorityService();$parent=dzn_l_parent();$proof=dzn_l_evidence('phase-l-create-'.wp_generate_uuid4());$key='phase-l-create-'.wp_generate_uuid4();$created=$service->create($parent,null,null,$proof,$key);dzn_l_assert($created['created']===true&&(new TermApplicabilityAssessment())->inspect($parent)['classification']==='canonical_applicable','Creation failed');$replay=$service->create($parent,null,null,$proof,$key);dzn_l_assert($replay['idempotent']===true&&$replay['term_id']===$created['term_id'],'Exact replay failed');$conflict=false;try{$service->create($parent,null,null,dzn_l_evidence('different'),$key);}catch(IdempotencyConflictException){$conflict=true;}dzn_l_assert($conflict,'Same-key different-payload accepted');
$term=$created['term_id'];$activated=$service->activate($term,'authorised',dzn_l_evidence('activate'), 'phase-l-activate-'.wp_generate_uuid4());dzn_l_assert($activated['term_id']===$term,'Activation failed');$closed=$service->close($term,'current',dzn_l_evidence('close'),'phase-l-close-'.wp_generate_uuid4());dzn_l_assert($closed['term_id']===$term&&(new TermApplicabilityAssessment())->inspect($parent)['classification']==='canonical_terminal_history','Close failed');$next=$service->create($parent,$term,'closed',dzn_l_evidence('next'),'phase-l-next-'.wp_generate_uuid4());dzn_l_assert($next['created']===true,'Creation after close failed');$service->cancel($next['term_id'],'authorised',dzn_l_evidence('cancel'),'phase-l-cancel-'.wp_generate_uuid4());$third=$service->create($parent,$next['term_id'],'cancelled',dzn_l_evidence('after-cancel'),'phase-l-third-'.wp_generate_uuid4());dzn_l_assert($third['created']===true,'Creation after cancellation failed');
// Failure after lifecycle evidence must roll back projection, event and command.
$beforeEvents=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}term_lifecycle_events WHERE term_id=%d",$third['term_id']));$fail=static function(){throw new RuntimeException('injected');};add_action('dzn_phase_2a2l_after_event_insert',$fail);$failed=false;try{$service->activate($third['term_id'],'authorised',dzn_l_evidence('rollback'),'phase-l-failure-'.wp_generate_uuid4());}catch(RuntimeException$e){$failed=$e->getMessage()==='injected';}remove_action('dzn_phase_2a2l_after_event_insert',$fail);$row=$wpdb->get_row($wpdb->prepare("SELECT lifecycle_state FROM {$p}terms WHERE id=%d",$third['term_id']));dzn_l_assert($failed&&$row->lifecycle_state==='authorised'&&(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}term_lifecycle_events WHERE term_id=%d",$third['term_id']))===$beforeEvents,'Rollback proof failed');
// Corrupted durable result must fail closed.
$corruptKey='phase-l-corrupt-'.wp_generate_uuid4();$corrupt=$service->activate($third['term_id'],'authorised',dzn_l_evidence('corrupt'),$corruptKey);$digest=Delnavazan\Platform\Core\Application\CanonicalTermIdempotency::keyDigest($corruptKey);$wpdb->update($p.'term_commands',array('result_state'=>'closed'),array('command_key_digest'=>$digest));$rejected=false;try{$service->activate($third['term_id'],'authorised',dzn_l_evidence('corrupt'),$corruptKey);}catch(RuntimeException){$rejected=true;}dzn_l_assert($rejected,'Corrupt command replay succeeded');
// Anonymous mutation is forbidden.
$actor=get_current_user_id();wp_set_current_user(0);$unauthorized=false;try{$service->create($parent,null,null,dzn_l_evidence('unauthorized'),'phase-l-unauth-'.wp_generate_uuid4());}catch(RuntimeException$e){$unauthorized=$e->getMessage()==='Unauthorized';}finally{wp_set_current_user($actor);}dzn_l_assert($unauthorized,'Unauthorized mutation succeeded');
$before=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}term_commands");Migrator::maybe_upgrade();dzn_l_assert($before===(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}term_commands"),'Repeat upgrade changed authority');
echo "schema_17_to_18=pass\ncapability_boundary=pass\ncreation=pass\nidempotency=pass\nlifecycle=pass\nterminal_recreation=pass\nrollback=pass\ncorruption=pass\nauthorization=pass\nrepeat_upgrade=pass\nPhase 2A.2-L runtime passed\n";
