<?php
/** Transaction rollback and duplicate-looking failure proof for every Phase J write boundary. */
if (getenv('DZN_PHASE_2A2J_RUNTIME_TEST') !== 'failure' || !defined('WP_CLI') || !WP_CLI || !in_array(wp_get_environment_type(), array('local', 'development'), true)) { fwrite(STDERR, "Phase 2A.2-J failure runtime refused.\n"); exit(1); }
use Delnavazan\Platform\Core\Application\TeacherAssignmentService;
global $wpdb; $p = $wpdb->prefix . 'dzn_'; $fixture = get_option('dzn_phase_2a2j_fixture');
function dzn_jf_assert(bool $ok, string $message): void { if (!$ok) throw new RuntimeException($message); }
function dzn_jf_key(string $label): string { return 'dzn-j-failure-' . $label . '-' . substr(hash('sha256', $label . wp_generate_uuid4()), 0, 30); }
function dzn_jf_clear(int $enrolmentId): void { global $wpdb; $p = $wpdb->prefix . 'dzn_'; $ids = array_map('intval', $wpdb->get_col($wpdb->prepare("SELECT id FROM {$p}teacher_assignments WHERE enrolment_id=%d", $enrolmentId)) ?: array()); if ($ids) { $marks = implode(',', array_fill(0, count($ids), '%d')); $wpdb->query($wpdb->prepare("DELETE FROM {$p}teacher_assignment_commands WHERE enrolment_id=%d", $enrolmentId)); $wpdb->query($wpdb->prepare("DELETE FROM {$p}teacher_assignment_lifecycle_events WHERE assignment_id IN ({$marks})", ...$ids)); $wpdb->query($wpdb->prepare("DELETE FROM {$p}teacher_assignments WHERE id IN ({$marks})", ...$ids)); } }
function dzn_jf_snapshot(int $enrolmentId): string { global $wpdb; $p = $wpdb->prefix . 'dzn_'; $a = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$p}teacher_assignments WHERE enrolment_id=%d ORDER BY id", $enrolmentId), ARRAY_A); $e = $wpdb->get_results($wpdb->prepare("SELECT e.* FROM {$p}teacher_assignment_lifecycle_events e INNER JOIN {$p}teacher_assignments a ON a.id=e.assignment_id WHERE a.enrolment_id=%d ORDER BY e.id", $enrolmentId), ARRAY_A); $c = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$p}teacher_assignment_commands WHERE enrolment_id=%d ORDER BY id", $enrolmentId), ARRAY_A); return serialize(array($a, $e, $c)); }
function dzn_jf_fail(string $hook, callable $operation, int $enrolmentId, string $message = 'synthetic_failure'): void { $before = dzn_jf_snapshot($enrolmentId); $failure = static function() use ($message): void { throw new RuntimeException($message); }; add_action($hook, $failure); $caught = null; try { $operation(); } catch (Throwable $e) { $caught = $e; } remove_action($hook, $failure); dzn_jf_assert($caught && $caught->getMessage() === $message, "{$hook} did not fail closed; caught=" . ($caught ? $caught::class . ':' . $caught->getMessage() : 'none')); dzn_jf_assert(dzn_jf_snapshot($enrolmentId) === $before, "{$hook} left partial authority"); }

dzn_jf_assert(is_array($fixture), 'Phase J fixture missing'); wp_set_current_user((int) $fixture['actor']);
$service = new TeacherAssignmentService(); $enrolment = (int) $fixture['sources'][0]['enrolment_id']; $teacher = (int) $fixture['teachers'][1];
$initial = static fn(string $label): array => $service->assignInitial($enrolment, dzn_jf_key($label));
$replacement = static function(int $base, string $label) use ($service, $enrolment, $teacher): array { return $service->replace($enrolment, $teacher, array('expected_assignment_id' => $base, 'route' => 'staff_attestation', 'evidence_channel' => 'phone', 'evidence_reference' => 'failure-' . $label, 'evidence_at' => gmdate('Y-m-d H:i:s')), dzn_jf_key($label)); };

foreach (array('dzn_phase_2a2j_after_initial_assignment_insert', 'dzn_phase_2a2j_after_initial_event_insert') as $hook) { dzn_jf_clear($enrolment); dzn_jf_fail($hook, static fn() => $initial($hook), $enrolment); }
dzn_jf_clear($enrolment); dzn_jf_fail('dzn_phase_2a2j_after_command_insert', static fn() => $initial('initial-command'), $enrolment);

foreach (array('dzn_phase_2a2j_after_predecessor_mutation', 'dzn_phase_2a2j_after_predecessor_lifecycle_event_insert', 'dzn_phase_2a2j_after_successor_assignment_insert', 'dzn_phase_2a2j_after_successor_lifecycle_event_insert') as $hook) { dzn_jf_clear($enrolment); $base = $initial('base-' . $hook); dzn_jf_fail($hook, static fn() => $replacement((int) $base['assignment_id'], $hook), $enrolment); }
dzn_jf_clear($enrolment); $base = $initial('base-replace-command'); $commandFailure = static function(string $operation): void { if ($operation === 'replace') throw new RuntimeException('synthetic_failure'); }; $before = dzn_jf_snapshot($enrolment); add_action('dzn_phase_2a2j_after_command_insert', $commandFailure); $caught = null; try { $replacement((int) $base['assignment_id'], 'replace-command'); } catch (Throwable $e) { $caught = $e; } remove_action('dzn_phase_2a2j_after_command_insert', $commandFailure); dzn_jf_assert($caught && $caught->getMessage() === 'synthetic_failure' && dzn_jf_snapshot($enrolment) === $before, 'Replacement command boundary did not roll back');

foreach (array('end', 'cancel') as $operation) {
    foreach (array('dzn_phase_2a2j_after_terminal_mutation', 'dzn_phase_2a2j_after_terminal_event_insert', 'dzn_phase_2a2j_after_command_insert') as $hook) {
        dzn_jf_clear($enrolment); $base = $initial($operation . '-base-' . $hook); $evidence = array('expected_assignment_id' => (int) $base['assignment_id'], 'evidence_channel' => 'email', 'evidence_reference' => $operation . '-failure', 'evidence_at' => gmdate('Y-m-d H:i:s'), 'reason_code' => $operation === 'end' ? 'service_ended' : 'assignment_cancelled');
        $call = static fn() => $service->{$operation}($enrolment, $evidence, dzn_jf_key($operation . '-' . $hook));
        if ($hook === 'dzn_phase_2a2j_after_command_insert') { $before = dzn_jf_snapshot($enrolment); $failure = static function(string $actual) use ($operation): void { if ($actual === $operation) throw new RuntimeException('synthetic_failure'); }; add_action($hook, $failure); $caught = null; try { $call(); } catch (Throwable $e) { $caught = $e; } remove_action($hook, $failure); dzn_jf_assert($caught && $caught->getMessage() === 'synthetic_failure' && dzn_jf_snapshot($enrolment) === $before, ucfirst($operation) . ' command boundary did not roll back'); }
        else dzn_jf_fail($hook, $call, $enrolment);
    }
    foreach (array("Duplicate entry synthetic persistence failure", "Duplicate entry '1' for key 'enrolment_applicable'") as $duplicateCase => $message) {
        dzn_jf_clear($enrolment); $base = $initial($operation . '-duplicate-base'); $evidence = array('expected_assignment_id' => (int) $base['assignment_id'], 'evidence_channel' => 'email', 'evidence_reference' => $operation . '-duplicate', 'evidence_at' => gmdate('Y-m-d H:i:s'), 'reason_code' => $operation === 'end' ? 'service_ended' : 'assignment_cancelled');
        dzn_jf_fail('dzn_phase_2a2j_after_terminal_mutation', static fn() => $service->{$operation}($enrolment, $evidence, dzn_jf_key($operation . '-duplicate-' . $duplicateCase)), $enrolment, $message);
    }
    dzn_jf_clear($enrolment); $base = $initial($operation . '-convergence-base'); $evidence = array('expected_assignment_id' => (int) $base['assignment_id'], 'evidence_channel' => 'email', 'evidence_reference' => $operation . '-convergence', 'evidence_at' => gmdate('Y-m-d H:i:s'), 'reason_code' => $operation === 'end' ? 'service_ended' : 'assignment_cancelled'); $created = $service->{$operation}($enrolment, $evidence, dzn_jf_key($operation . '-convergence-one')); $converged = $service->{$operation}($enrolment, $evidence, dzn_jf_key($operation . '-convergence-two')); dzn_jf_assert($created['created'] && $converged['already_applied'] && $created['assignment_id'] === $converged['assignment_id'], ucfirst($operation) . ' complete-result convergence failed');
}
dzn_jf_clear($enrolment);
echo "initial_write_boundaries=pass\nreplacement_write_boundaries=pass\nterminal_write_boundaries=pass\nterminal_duplicate_false_success_closed=pass\nterminal_complete_convergence=pass\nPhase 2A.2-J failure runtime passed\n";
