<?php
/** Disposable production-path Phase-M authority proof; synthetic local data only. */
if(getenv('DZN_PHASE_2A2M_RUNTIME_TEST')!=='authority'||!defined('WP_CLI')||!WP_CLI||!in_array(wp_get_environment_type(),array('local','development'),true)){fwrite(STDERR,"Phase 2A.2-M runtime refused.\n");exit(1);}
use Delnavazan\Platform\Core\Application\{CanonicalEnrolmentLifecycleService,CanonicalLessonAuthorityService,CanonicalTermAuthorityService,IdempotencyConflictException,TeacherAssignmentService};
global$wpdb;$p=$wpdb->prefix.'dzn_';function dzn_m_assert(bool$v,string$m):void{if(!$v)throw new RuntimeException($m);}function dzn_m_e(string$r):array{return array('evidence_channel'=>'staff_record','evidence_reference'=>$r,'evidence_at'=>gmdate('Y-m-d H:i:s'));}
$fixture=get_option('dzn_phase_2a2j_fixture');if(!is_array($fixture)||count($fixture['sources']??array())<12)throw new RuntimeException('Phase-J production fixture required');$sources=$fixture['sources'];$enrolment=new CanonicalEnrolmentLifecycleService();$termService=new CanonicalTermAuthorityService();$assignmentService=new TeacherAssignmentService();$lessonService=new CanonicalLessonAuthorityService();
$ready=function(int$index)use($sources,$enrolment,$termService,$assignmentService):array{$id=(int)$sources[$index]['enrolment_id'];$enrolment->activate($id,'authorised',dzn_m_e('activate-'.$index),'m-activate-'.$index.'-'.wp_generate_uuid4());$term=$termService->create($id,null,null,dzn_m_e('term-'.$index),'m-term-'.$index.'-'.wp_generate_uuid4());$termService->activate((int)$term['term_id'],'authorised',dzn_m_e('term-active-'.$index),'m-term-active-'.$index.'-'.wp_generate_uuid4());$assignment=$assignmentService->assignInitial($id,'m-assignment-'.$index.'-'.wp_generate_uuid4());return array($id,(int)$term['term_id'],(int)$assignment['assignment_id']);};
[$id,$term,$assignment]=$ready(0);$first=null;for($n=1;$n<=12;$n++){$result=$lessonService->createStandard($term,$assignment,dzn_m_e('standard-'.$n),'m-standard-'.$n.'-'.wp_generate_uuid4());if($n===1)$first=(int)$result['lesson_id'];}dzn_m_assert((int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}lessons WHERE term_id=%d AND record_model='canonical_term_lesson_v1' AND lesson_type='standard'",$term))===12,'standard allocation projection');
$reject=static function(callable$f,string$m):void{$ok=false;try{$f();}catch(InvalidArgumentException){$ok=true;}dzn_m_assert($ok,$m);};$reject(fn()=>$lessonService->createStandard($term,$assignment,dzn_m_e('thirteen'),'m-standard-thirteen-'.wp_generate_uuid4()),'13th standard accepted');$lessonService->cancel($first,'authorised',dzn_m_e('eligible')+array('reason_code'=>'attested_non_delivery'),'m-cancel-origin-'.wp_generate_uuid4());$reject(fn()=>$lessonService->createStandard($term,$assignment,dzn_m_e('after-cancel'),'m-standard-after-cancel-'.wp_generate_uuid4()),'cancellation restored standard allocation');$replacement=$lessonService->createReplacement($term,$assignment,$first,dzn_m_e('replacement'),'m-replacement-'.wp_generate_uuid4());$reject(fn()=>$lessonService->createReplacement($term,$assignment,$first,dzn_m_e('duplicate-origin'),'m-replacement-origin-'.wp_generate_uuid4()),'replacement origin reused');
[$guardId,$guardTerm,$guardAssignment]=$ready(1);$guardLesson=$lessonService->createStandard($guardTerm,$guardAssignment,dzn_m_e('closure-lesson'),'m-closure-lesson-'.wp_generate_uuid4());$reject(fn()=>$enrolment->close($guardId,'current',dzn_m_e('close-live'),'m-close-live-'.wp_generate_uuid4()),'live Lesson did not block Enrolment close');$lessonService->complete((int)$guardLesson['lesson_id'],'authorised',dzn_m_e('complete'),'m-complete-'.wp_generate_uuid4());$termService->close($guardTerm,'current',dzn_m_e('term-close'),'m-term-close-'.wp_generate_uuid4());$assignmentService->end($guardId,array('expected_assignment_id'=>$guardAssignment,'evidence_channel'=>'email','evidence_reference'=>'synthetic','evidence_at'=>gmdate('Y-m-d H:i:s'),'reason_code'=>'service_ended'),'m-assignment-end-'.wp_generate_uuid4());$enrolment->close($guardId,'current',dzn_m_e('close-terminal'),'m-close-terminal-'.wp_generate_uuid4());
[$termGuardId,$termGuard,$termGuardAssignment]=$ready(2);$termLesson=$lessonService->createStandard($termGuard,$termGuardAssignment,dzn_m_e('term-guard'),'m-term-guard-'.wp_generate_uuid4());$reject(fn()=>$termService->close($termGuard,'current',dzn_m_e('blocked-term-close'),'m-blocked-term-close-'.wp_generate_uuid4()),'live Lesson did not block Term close');$lessonService->cancel((int)$termLesson['lesson_id'],'authorised',dzn_m_e('terminal'),'m-term-lesson-cancel-'.wp_generate_uuid4());$termService->close($termGuard,'current',dzn_m_e('term-close-terminal'),'m-term-close-terminal-'.wp_generate_uuid4());
[$replayId,$replayTerm,$replayAssignment]=$ready(3);$key='m-replay-'.wp_generate_uuid4();$issued=$lessonService->createStandard($replayTerm,$replayAssignment,dzn_m_e('replay'),$key);$replay=$lessonService->createStandard($replayTerm,$replayAssignment,dzn_m_e('replay'),$key);dzn_m_assert((int)$issued['lesson_id']===(int)$replay['lesson_id']&&($replay['idempotent']??false),'exact Lesson replay failed');$conflict=false;try{$lessonService->createStandard($replayTerm,$replayAssignment,dzn_m_e('changed'),$key);}catch(IdempotencyConflictException){$conflict=true;}dzn_m_assert($conflict,'Lesson idempotency conflict failed');
[$pauseId,$pauseTerm,$pauseAssignment]=$ready(4);$enrolment->pause($pauseId,'current',dzn_m_e('pause'),'m-pause-'.wp_generate_uuid4());$reject(fn()=>$lessonService->createStandard($pauseTerm,$pauseAssignment,dzn_m_e('paused'),'m-paused-'.wp_generate_uuid4()),'paused Enrolment issued Lesson');
foreach(array('dzn_phase_2a2m_after_lesson_insert','dzn_phase_2a2m_after_lifecycle_event_insert','dzn_phase_2a2m_after_command_insert')as$offset=>$hook){[$failId,$failTerm,$failAssignment]=$ready(5+$offset);$before=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}lessons WHERE term_id=%d",$failTerm));$inject=static function(){throw new RuntimeException('injected');};add_action($hook,$inject);$failed=false;try{$lessonService->createStandard($failTerm,$failAssignment,dzn_m_e('failure-'.$offset),'m-failure-'.$offset.'-'.wp_generate_uuid4());}catch(RuntimeException$e){$failed=$e->getMessage()==='injected';}finally{remove_action($hook,$inject);}dzn_m_assert($failed&&(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}lessons WHERE term_id=%d",$failTerm))===$before&&(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}canonical_lesson_commands WHERE term_id=%d",$failTerm))===0,'Lesson write rollback failed');}
$commands=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}canonical_lesson_commands");\Delnavazan\Platform\Core\Infrastructure\Migration\Migrator::maybe_upgrade();dzn_m_assert($commands===(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}canonical_lesson_commands"),'repeat upgrade changed Lesson evidence');
echo "schema_19_to_20=pass\nproduction_authoritative_chain=pass\nstandard_allocation=pass\nreplacement_origin=pass\nenrolment_closure_guard=pass\nterm_closure_guard=pass\nlifecycle=pass\nidempotency=pass\npaused_rejection=pass\nwrite_boundary_rollback=pass\nrepeat_upgrade=pass\nPhase 2A.2-M runtime passed\n";
