<?php
/** Complete readiness, frozen evidence, lifecycle, replay and atomicity runtime proof. */
if(getenv('DZN_PHASE_2A2I_RUNTIME_TEST')!=='isolated'||!defined('WP_CLI')||!WP_CLI||!in_array(wp_get_environment_type(),array('local','development'),true)){fwrite(STDERR,"Phase 2A.2-I isolated runtime refused.\n");exit(1);}
use Delnavazan\Platform\Core\Application\{BookingRequestPrivacyService,EnrolmentConversionReadinessService,EnrolmentConversionService,IdempotencyConflictException};
use Delnavazan\Platform\Core\Infrastructure\Repository\EnrolmentRepository;
global$wpdb;$p=$wpdb->prefix.'dzn_';$f=get_option('dzn_phase_2a2i_fixture');$actor=get_current_user_id();
function dzn_2a2i_assert(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);}
function dzn_2a2i_key(string$label):string{return'dzn-2a2i-'.$label.'-'.substr(hash('sha256',$label.'-'.wp_generate_uuid4()),0,40);}
function dzn_2a2i_counts():array{global$wpdb;$prefix=$wpdb->prefix.'dzn_';return array((int)$wpdb->get_var("SELECT COUNT(*) FROM {$prefix}enrolments WHERE record_model='canonical_student_course_v1'"),(int)$wpdb->get_var("SELECT COUNT(*) FROM {$prefix}enrolment_lifecycle_events"),(int)$wpdb->get_var("SELECT COUNT(*) FROM {$prefix}enrolment_conversion_commands"));}
function dzn_2a2i_rejected(callable$operation,string$message):void{$rejected=false;try{$operation();}catch(Throwable){$rejected=true;}dzn_2a2i_assert($rejected,$message);}
function dzn_2a2i_close(int$enrolmentId,int$sequence,string$from,string$to,string$occurred,string$recorded):void{global$wpdb;$prefix=$wpdb->prefix.'dzn_';$actorId=get_current_user_id();$created=max($occurred,$recorded);dzn_2a2i_assert($wpdb->insert($prefix.'enrolment_lifecycle_events',array('uid'=>str_pad('AHC'.$enrolmentId.$sequence,26,'0'),'enrolment_id'=>$enrolmentId,'event_sequence'=>$sequence,'from_state'=>$from,'to_state'=>$to,'lineage_meaning'=>null,'reason_code'=>'synthetic_closure','evidence_channel'=>'runtime_test','evidence_reference'=>'phase-i-history-'.$enrolmentId.'-'.$sequence,'occurred_at'=>$occurred,'recorded_at'=>$recorded,'recorded_by'=>$actorId,'created_at'=>$created,'created_by'=>$actorId))===1,'Lifecycle fixture insert failed: '.$wpdb->last_error);}
function dzn_2a2i_convert_close(array$source,string$case,EnrolmentConversionService$service):int{global$wpdb;$prefix=$wpdb->prefix.'dzn_';$result=$service->convert((int)$source['arrangement_id'],dzn_2a2i_key('history-'.$case));$id=(int)$result['enrolment_id'];$at=gmdate('Y-m-d H:i:s',strtotime('+10 seconds'));dzn_2a2i_assert($wpdb->update($prefix.'enrolments',array('lifecycle_state'=>'closed','applicable_slot'=>null),array('id'=>$id))===1,'History row close failed');switch($case){case'start':$wpdb->delete($prefix.'enrolment_lifecycle_events',array('enrolment_id'=>$id));dzn_2a2i_close($id,2,'authorised','closed',$at,$at);break;case'gap':dzn_2a2i_close($id,3,'authorised','closed',$at,$at);break;case'chain':dzn_2a2i_close($id,2,'paused','closed',$at,$at);break;case'invalid':dzn_2a2i_close($id,2,'authorised','invalid_state',$at,$at);break;case'state':dzn_2a2i_close($id,2,'authorised','paused',$at,$at);break;case'timestamp':dzn_2a2i_close($id,2,'authorised','closed',$at,gmdate('Y-m-d H:i:s',strtotime('+9 seconds')));break;default:dzn_2a2i_close($id,2,'authorised','closed',$at,$at);}return$id;}

dzn_2a2i_assert(is_array($f),'Phase I fixture missing');$ready=new EnrolmentConversionReadinessService();$service=new EnrolmentConversionService();
$actorId=$actor;wp_set_current_user(0);$unauthorized=false;try{$ready->assess((int)$f['main']['arrangement_id']);}catch(RuntimeException$e){$unauthorized=$e->getMessage()==='Unauthorized';}finally{wp_set_current_user($actorId);}dzn_2a2i_assert($unauthorized,'Readiness capability was not enforced');

// Exercise every public readiness classification and integrity precedence.
$classifications=array();$classifications['ready']=$ready->assess((int)$f['main']['arrangement_id']);$classifications['legacy_review_required']=$ready->assess((int)$f['legacy']['arrangement_id']);$classifications['student_not_current']=$ready->assess((int)$f['inactive_student']['arrangement_id']);$classifications['course_not_current']=$ready->assess((int)$f['inactive_course']['arrangement_id']);$classifications['source_integrity_conflict']=$ready->assess(999999999);
$notFinal=$wpdb->get_row($wpdb->prepare("SELECT proposal_version_id FROM {$p}accepted_service_arrangements WHERE id=%d",$f['source_not_final']['arrangement_id']));$wpdb->update($p.'proposal_versions',array('course_id'=>null,'unresolved_course_spec'=>'review_required'),array('id'=>$notFinal->proposal_version_id));$wpdb->update($p.'accepted_service_arrangements',array('course_id'=>null,'unresolved_course_spec'=>'review_required'),array('id'=>$f['source_not_final']['arrangement_id']));$classifications['source_not_final']=$ready->assess((int)$f['source_not_final']['arrangement_id']);
$wpdb->update($p.'accepted_service_arrangements',array('family_uid'=>str_pad('BADFAMILY',26,'0')),array('id'=>$f['malformed_source']['arrangement_id']));dzn_2a2i_assert($ready->assess((int)$f['malformed_source']['arrangement_id'])==='source_integrity_conflict','Malformed source lineage did not fail closed');
$wpdb->query($wpdb->prepare("UPDATE {$p}accepted_service_arrangements SET identity_resolution_sequence=identity_resolution_sequence+1 WHERE id=%d",$f['identity_contaminated']['arrangement_id']));dzn_2a2i_assert($ready->assess((int)$f['identity_contaminated']['arrangement_id'])==='source_integrity_conflict','Frozen identity evidence contamination accepted');
$wpdb->update($p.'accepted_service_arrangements',array('capacity_classification'=>'minor'),array('id'=>$f['capacity_contaminated']['arrangement_id']));dzn_2a2i_assert($ready->assess((int)$f['capacity_contaminated']['arrangement_id'])==='source_integrity_conflict','Frozen capacity evidence contamination accepted');
dzn_2a2i_assert($ready->assess((int)$f['stale_readiness']['arrangement_id'])==='ready','Stale-readiness fixture did not begin ready');$wpdb->update($p.'accepted_service_arrangements',array('version_fingerprint'=>hash('sha256','stale-after-readiness')),array('id'=>$f['stale_readiness']['arrangement_id']));dzn_2a2i_rejected(static fn()=>$service->convert((int)$f['stale_readiness']['arrangement_id'],dzn_2a2i_key('stale-readiness')),'Conversion trusted stale readiness');

// Clean conversion, replay, already-converted and key conflict semantics.
$key=dzn_2a2i_key('main');$created=$service->convert((int)$f['main']['arrangement_id'],$key);$replay=$service->convert((int)$f['main']['arrangement_id'],$key);$otherKey=$service->convert((int)$f['main']['arrangement_id'],dzn_2a2i_key('main-other'));
dzn_2a2i_assert($created['created']&&!$created['idempotent']&&!$created['already_converted'],'Initial conversion response invalid');dzn_2a2i_assert(!$replay['created']&&$replay['idempotent']&&$replay['enrolment_id']===$created['enrolment_id'],'Same-command replay invalid');dzn_2a2i_assert($otherKey['already_converted']&&!$otherKey['created']&&!$otherKey['idempotent']&&$otherKey['enrolment_id']===$created['enrolment_id'],'Different-key already-converted result invalid');$classifications['already_converted']=$ready->assess((int)$f['main']['arrangement_id']);
$conflict=false;try{$service->convert((int)$f['return']['arrangement_id'],$key);}catch(IdempotencyConflictException){$conflict=true;}dzn_2a2i_assert($conflict,'Same key with different source did not conflict');
$enrolment=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}enrolments WHERE id=%d",$created['enrolment_id']));$event=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}enrolment_lifecycle_events WHERE enrolment_id=%d",$created['enrolment_id']));dzn_2a2i_assert($enrolment&&$enrolment->record_model==='canonical_student_course_v1'&&$enrolment->status==='canonical'&&$enrolment->lifecycle_state==='authorised'&&(int)$enrolment->applicable_slot===1&&(int)$enrolment->student_id===(int)$f['main']['student_id']&&(int)$enrolment->course_id===(int)$f['main']['course_id']&&(int)$enrolment->teacher_id===(int)$f['main']['teacher_id'],'Canonical target facts invalid');dzn_2a2i_assert($event&&(int)$event->event_sequence===1&&$event->from_state===null&&$event->to_state==='authorised'&&$event->reason_code==='accepted_service_arrangement_conversion'&&$event->evidence_channel==='platform_conversion_command','Initial lifecycle event invalid');

$service->convert((int)$f['conflict_predecessor']['arrangement_id'],dzn_2a2i_key('conflict-predecessor'));$classifications['canonical_conflict']=$ready->assess((int)$f['conflict_target']['arrangement_id']);
$service->convert((int)$f['mixed_predecessor']['arrangement_id'],dzn_2a2i_key('mixed-predecessor'));$now=gmdate('Y-m-d H:i:s');(new EnrolmentRepository())->insertLegacyBootstrap(array('uid'=>str_pad('IMIXED',26,'0'),'reference_code'=>null,'student_id'=>$f['mixed_predecessor']['student_id'],'teacher_id'=>$f['mixed_predecessor']['teacher_id'],'course_id'=>$f['mixed_predecessor']['course_id'],'status'=>'active','record_model'=>'legacy_phase1','created_at'=>$now,'updated_at'=>$now,'created_by'=>$actor,'updated_by'=>$actor));$classifications['data_integrity_conflict']=$ready->assess((int)$f['mixed_target']['arrangement_id']);
foreach(array_keys($classifications)as$expected)dzn_2a2i_assert($classifications[$expected]===$expected,'Readiness classification failed: '.$expected.' got '.$classifications[$expected]);

// Every replay/already-converted path rejects contaminated command, source, Teacher or lifecycle evidence.
$commandKey=dzn_2a2i_key('replay-command');$commandResult=$service->convert((int)$f['replay_command_contaminated']['arrangement_id'],$commandKey);$wpdb->update($p.'enrolment_conversion_commands',array('accepted_service_arrangement_id'=>$f['malformed_source']['arrangement_id']),array('enrolment_id'=>$commandResult['enrolment_id']));dzn_2a2i_rejected(static fn()=>$service->convert((int)$f['replay_command_contaminated']['arrangement_id'],$commandKey),'Command/source contamination replayed');
$teacherKey=dzn_2a2i_key('replay-teacher');$teacherResult=$service->convert((int)$f['replay_teacher_contaminated']['arrangement_id'],$teacherKey);$wpdb->query($wpdb->prepare("UPDATE {$p}enrolments SET teacher_id=teacher_id+100000 WHERE id=%d",$teacherResult['enrolment_id']));dzn_2a2i_rejected(static fn()=>$service->convert((int)$f['replay_teacher_contaminated']['arrangement_id'],$teacherKey),'Teacher-contaminated Enrolment replayed');
$lifecycleKey=dzn_2a2i_key('replay-lifecycle');$lifecycleResult=$service->convert((int)$f['replay_lifecycle_contaminated']['arrangement_id'],$lifecycleKey);$wpdb->update($p.'enrolment_lifecycle_events',array('reason_code'=>'contaminated'),array('enrolment_id'=>$lifecycleResult['enrolment_id'],'event_sequence'=>1));dzn_2a2i_rejected(static fn()=>$service->convert((int)$f['replay_lifecycle_contaminated']['arrangement_id'],$lifecycleKey),'Lifecycle-contaminated Enrolment replayed');
$alreadyResult=$service->convert((int)$f['already_contaminated']['arrangement_id'],dzn_2a2i_key('already-create'));$wpdb->query($wpdb->prepare("UPDATE {$p}enrolments SET teacher_id=teacher_id+100000 WHERE id=%d",$alreadyResult['enrolment_id']));dzn_2a2i_rejected(static fn()=>$service->convert((int)$f['already_contaminated']['arrangement_id'],dzn_2a2i_key('already-second')),'Contaminated already-converted Enrolment returned');
$sourceKey=dzn_2a2i_key('replay-source');$sourceResult=$service->convert((int)$f['replay_source_contaminated']['arrangement_id'],$sourceKey);$wpdb->update($p.'enrolments',array('accepted_service_arrangement_id'=>$f['capacity_contaminated']['arrangement_id']),array('id'=>$sourceResult['enrolment_id']));dzn_2a2i_rejected(static fn()=>$service->convert((int)$f['replay_source_contaminated']['arrangement_id'],$sourceKey),'Source-contaminated Enrolment replayed');

// Clean and malformed closed-history predecessor cases.
$closedAt=gmdate('Y-m-d H:i:s',strtotime('+1 second'));$wpdb->update($p.'enrolments',array('lifecycle_state'=>'closed','applicable_slot'=>null),array('id'=>$created['enrolment_id']));dzn_2a2i_close((int)$created['enrolment_id'],2,'authorised','closed',$closedAt,$closedAt);dzn_2a2i_assert($ready->assess((int)$f['return']['arrangement_id'])==='ready','Valid return-after-closure not ready');$returned=$service->convert((int)$f['return']['arrangement_id'],dzn_2a2i_key('return'));$returnRow=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}enrolments WHERE id=%d",$returned['enrolment_id']));dzn_2a2i_assert($returnRow&&(int)$returnRow->predecessor_enrolment_id===$created['enrolment_id']&&$returnRow->lineage_meaning==='return_after_closure','Closure-evidence predecessor selection failed');
foreach(array('start','gap','chain','invalid','state','timestamp')as$case){dzn_2a2i_convert_close($f['history_'.$case.'_predecessor'],$case,$service);dzn_2a2i_assert($ready->assess((int)$f['history_'.$case.'_target']['arrangement_id'])==='data_integrity_conflict','Malformed lifecycle accepted: '.$case);}
$tieAt=gmdate('Y-m-d H:i:s',strtotime('+20 seconds'));$tieOne=$service->convert((int)$f['tie_predecessor_one']['arrangement_id'],dzn_2a2i_key('tie-one'));$wpdb->update($p.'enrolments',array('lifecycle_state'=>'closed','applicable_slot'=>null),array('id'=>$tieOne['enrolment_id']));dzn_2a2i_close((int)$tieOne['enrolment_id'],2,'authorised','closed',$tieAt,$tieAt);$tieTwo=$service->convert((int)$f['tie_predecessor_two']['arrangement_id'],dzn_2a2i_key('tie-two'));$wpdb->update($p.'enrolments',array('lifecycle_state'=>'closed','applicable_slot'=>null),array('id'=>$tieTwo['enrolment_id']));dzn_2a2i_close((int)$tieTwo['enrolment_id'],2,'authorised','closed',$tieAt,$tieAt);dzn_2a2i_assert($ready->assess((int)$f['tie_target']['arrangement_id'])==='data_integrity_conflict','Equal closure ambiguity accepted');

(new BookingRequestPrivacyService())->erase((int)$f['privacy']['request_id'],$actor,'synthetic_runtime');$erasedBefore=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}booking_requests WHERE id=%d",$f['privacy']['request_id']));dzn_2a2i_assert($erasedBefore&&$erasedBefore->privacy_erased_at!==null&&$ready->assess((int)$f['privacy']['arrangement_id'])==='ready','Retained final source became unready after erasure');$privacyResult=$service->convert((int)$f['privacy']['arrangement_id'],dzn_2a2i_key('privacy'));$erasedAfter=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}booking_requests WHERE id=%d",$f['privacy']['request_id']));$contact=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}booking_request_contact_snapshots WHERE booking_request_id=%d",$f['privacy']['request_id']));$privacyEnrolment=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}enrolments WHERE id=%d",$privacyResult['enrolment_id']),ARRAY_A);dzn_2a2i_assert($erasedAfter->privacy_erased_at===$erasedBefore->privacy_erased_at&&$contact&&$contact->email===null&&$contact->full_name===null,'Conversion reversed privacy erasure');foreach(array('email','phone','mobile','full_name','whatsapp','address')as$field)dzn_2a2i_assert(!array_key_exists($field,$privacyEnrolment),'Enrolment copied prohibited PII '.$field);

foreach(array('atomic_enrolment'=>'dzn_phase_2a2i_after_enrolment_insert','atomic_event'=>'dzn_phase_2a2i_after_lifecycle_event_insert','atomic_command'=>'dzn_phase_2a2i_after_command_insert')as$name=>$hook){$before=dzn_2a2i_counts();$failure=static function(){throw new RuntimeException('synthetic_failure');};add_action($hook,$failure);$failed=false;try{$service->convert((int)$f[$name]['arrangement_id'],dzn_2a2i_key($name));}catch(RuntimeException$e){$failed=$e->getMessage()==='synthetic_failure';}remove_action($hook,$failure);dzn_2a2i_assert($failed&&dzn_2a2i_counts()===$before,'Atomic rollback failed at '.$hook);}

$command=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}enrolment_conversion_commands WHERE enrolment_id=%d",$created['enrolment_id']),ARRAY_A);$wpdb->suppress_errors(true);$duplicateCommand=$wpdb->insert($p.'enrolment_conversion_commands',array_replace($command,array('id'=>null,'uid'=>str_pad('IDUPCMD',26,'0'))))===false;$duplicateSource=$wpdb->insert($p.'enrolment_conversion_commands',array_replace($command,array('id'=>null,'uid'=>str_pad('IDUPSRC',26,'0'),'command_key_digest'=>hash('sha256','other-command'))))===false;$duplicateEnrolment=$wpdb->insert($p.'enrolment_conversion_commands',array_replace($command,array('id'=>null,'uid'=>str_pad('IDUPENR',26,'0'),'command_key_digest'=>hash('sha256','third-command'),'accepted_service_arrangement_id'=>$f['atomic_enrolment']['arrangement_id'])))===false;$duplicateApplicable=$wpdb->insert($p.'enrolments',array('uid'=>str_pad('IDUPAPP',26,'0'),'student_id'=>$returnRow->student_id,'teacher_id'=>$returnRow->teacher_id,'course_id'=>$returnRow->course_id,'status'=>'canonical','record_model'=>'canonical_student_course_v1','accepted_service_arrangement_id'=>$f['atomic_event']['arrangement_id'],'lifecycle_state'=>'authorised','applicable_slot'=>1,'created_at'=>gmdate('Y-m-d H:i:s'),'updated_at'=>gmdate('Y-m-d H:i:s')))===false;$duplicateEvent=$wpdb->insert($p.'enrolment_lifecycle_events',array('uid'=>str_pad('IDUPEVT',26,'0'),'enrolment_id'=>$created['enrolment_id'],'event_sequence'=>2,'from_state'=>'authorised','to_state'=>'closed','reason_code'=>'duplicate','evidence_channel'=>'runtime_test','evidence_reference'=>'duplicate','occurred_at'=>$closedAt,'recorded_at'=>$closedAt,'recorded_by'=>$actor,'created_at'=>$closedAt,'created_by'=>$actor))===false;$wpdb->suppress_errors(false);dzn_2a2i_assert($duplicateCommand&&$duplicateSource&&$duplicateEnrolment&&$duplicateApplicable&&$duplicateEvent,'Database final arbitration incomplete');
echo"classifications=".implode(',',array_keys($classifications))."\nfrozen_identity_capacity=pass\nstale_readiness=pass\nconversion=pass\nreplay_contamination=pass\nreturn_after_closure=pass\nmalformed_lifecycle=pass\nambiguous_predecessor=pass\nprivacy_after_final=pass\natomicity=pass\ndatabase_uniqueness=pass\nPhase 2A.2-I isolated runtime passed\n";
