<?php
if (getenv('DZN_PHASE_2A2J_RUNTIME_TEST') !== 'concurrency' || !defined('WP_CLI') || !WP_CLI || !in_array(wp_get_environment_type(), array('local', 'development'), true)) { fwrite(STDERR, "Phase 2A.2-J concurrency setup refused.\n"); exit(1); }
use Delnavazan\Platform\Core\Application\TeacherAssignmentService;
global $wpdb; $p = $wpdb->prefix . 'dzn_'; $fixture = get_option('dzn_phase_2a2j_fixture'); $mode = (string) getenv('DZN_PHASE_2A2J_MODE');
if (!is_array($fixture) || !in_array($mode, array('a_same_teacher_keys','c_replace_end','d1_replace_diff','d2_replace_same','e_initial_archive','e_replace_archive','e_archive_initial','e_archive_replace','f_initial_close','f_replace_close','f_close_initial','f_close_replace','u1_unrelated_roots','u2_shared_teacher'), true)) throw new RuntimeException('Phase J race state unavailable');
$enrolments = array_map(static fn(array $source): int => (int) $source['enrolment_id'], $fixture['sources']);
foreach ($enrolments as $enrolmentId) { $assignmentIds = array_map('intval', $wpdb->get_col($wpdb->prepare("SELECT id FROM {$p}teacher_assignments WHERE enrolment_id=%d", $enrolmentId)) ?: array()); $wpdb->delete($p . 'teacher_assignment_commands', array('enrolment_id' => $enrolmentId)); if ($assignmentIds) { $marks = implode(',', array_fill(0, count($assignmentIds), '%d')); $wpdb->query($wpdb->prepare("DELETE FROM {$p}teacher_assignment_lifecycle_events WHERE assignment_id IN ({$marks})", ...$assignmentIds)); $wpdb->query($wpdb->prepare("DELETE FROM {$p}teacher_assignments WHERE id IN ({$marks})", ...$assignmentIds)); } $wpdb->query($wpdb->prepare("DELETE FROM {$p}enrolment_lifecycle_events WHERE enrolment_id=%d AND event_sequence>1", $enrolmentId)); $wpdb->update($p . 'enrolments', array('lifecycle_state' => 'authorised', 'applicable_slot' => 1), array('id' => $enrolmentId)); }
foreach ($fixture['teachers'] as $teacherId) $wpdb->update($p . 'teachers', array('status' => 'active', 'archived_at' => null, 'archived_by' => null), array('id' => (int) $teacherId));
$state = array('mode' => $mode, 'enrolment_id' => $enrolments[0], 'other_enrolment_id' => $enrolments[1], 'teacher_initial' => (int) $fixture['teachers'][0], 'teacher_one' => (int) $fixture['teachers'][1], 'teacher_two' => (int) $fixture['teachers'][2], 'evidence_at' => gmdate('Y-m-d H:i:s', strtotime('-2 seconds')), 'key_one' => dzn_2a2j_race_key($mode . '-one'), 'key_two' => dzn_2a2j_race_key($mode . '-two'));
if (in_array($mode, array('c_replace_end','d1_replace_diff','d2_replace_same','e_replace_archive','e_archive_replace','f_replace_close','f_close_replace'), true)) { $initial = (new TeacherAssignmentService())->assignInitial($enrolments[0], dzn_2a2j_race_key($mode . '-base')); $state['expected_assignment_id'] = (int) $initial['assignment_id']; }
$state['teacher_two'] = in_array($mode, array('d2_replace_same', 'e_archive_replace'), true) ? $state['teacher_one'] : $state['teacher_two'];
update_option('dzn_phase_2a2j_race_state', $state, false);
echo "Phase 2A.2-J {$mode} concurrency setup passed\n";
function dzn_2a2j_race_key(string $label): string { return 'dzn-2a2j-race-' . $label . '-' . substr(hash('sha256', $label . wp_generate_uuid4()), 0, 32); }
