<?php
/** Disposable Schema 18 -> 19 and canonical Enrolment lifecycle runtime proof. */
if(getenv('DZN_PHASE_2A2M0_RUNTIME_TEST')!=='authority'||!defined('WP_CLI')||!WP_CLI||!in_array(wp_get_environment_type(),array('local','development'),true)){fwrite(STDERR,"Phase 2A.2-M0 runtime refused.\n");exit(1);}
use Delnavazan\Platform\Core\Application\{CanonicalEnrolmentLifecycleIdempotency,CanonicalEnrolmentLifecycleService,CanonicalTermAuthorityService,IdempotencyConflictException,TeacherAssignmentService};
use Delnavazan\Platform\Core\Infrastructure\Migration\Migrator;
use Delnavazan\Platform\Core\Support\Identifier;
global$wpdb;$p=$wpdb->prefix.'dzn_';function dzn_m0_assert(bool$v,string$m):void{if(!$v)throw new RuntimeException($m);}function dzn_m0_evidence(string$r):array{return array('evidence_channel'=>'staff_record','evidence_reference'=>$r,'evidence_at'=>gmdate('Y-m-d H:i:s'));}
// Migration, repeat safety and capability repair.
$wpdb->query("DROP TABLE IF EXISTS {$p}enrolment_lifecycle_commands");$done=array_values(array_filter((array)get_option('dzn_platform_completed_migrations',array()),static fn($id)=>$id!=='019_canonical_enrolment_lifecycle_authority'));update_option('dzn_platform_completed_migrations',$done,false);update_option('dzn_platform_schema_version','18',false);update_option('dzn_platform_capability_version','2a2l',false);$admin=get_role('administrator');$admin->remove_cap('dzn_manage_canonical_enrolment_lifecycle');Migrator::maybe_upgrade();dzn_m0_assert((string)get_option('dzn_platform_schema_version')=== (string) DZN_PLATFORM_SCHEMA_VERSION &&$admin->has_cap('dzn_manage_canonical_enrolment_lifecycle')&&$admin->has_cap('dzn_manage_canonical_lessons')&&!get_role('dzn_teacher')->has_cap('dzn_manage_canonical_enrolment_lifecycle'),'Migration/capability failed');
$authoritative=get_option('dzn_phase_2a2j_fixture');if(!is_array($authoritative)||count($authoritative['sources']??array())<12)throw new RuntimeException('Run the expanded Phase-J production-authoritative fixture first');$sources=$authoritative['sources'];
$service=new CanonicalEnrolmentLifecycleService();$id=(int)$sources[0]['enrolment_id'];$activateEvidence=dzn_m0_evidence('activate');$activateKey='m0-activate-'.wp_generate_uuid4();$activate=$service->activate($id,'authorised',$activateEvidence,$activateKey);$service->pause($id,'current',dzn_m0_evidence('pause'),'m0-pause-'.wp_generate_uuid4());$replay=$service->activate($id,'authorised',$activateEvidence,$activateKey);dzn_m0_assert($replay['idempotent']&&$replay['event_id']===$activate['event_id'],'Historical replay after progression failed');$service->resume($id,'paused',dzn_m0_evidence('resume'),'m0-resume-'.wp_generate_uuid4());$service->close($id,'current',dzn_m0_evidence('close'),'m0-close-'.wp_generate_uuid4());$row=$wpdb->get_row($wpdb->prepare("SELECT lifecycle_state,applicable_slot FROM {$p}enrolments WHERE id=%d",$id));dzn_m0_assert($row->lifecycle_state==='closed'&&$row->applicable_slot===null,'Lifecycle/slot graph failed');
$conflict=false;try{$service->activate($id,'authorised',dzn_m0_evidence('changed'),$activateKey);}catch(IdempotencyConflictException){$conflict=true;}dzn_m0_assert($conflict,'Same-key conflict failed');$stale=false;try{$service->resume($id,'paused',dzn_m0_evidence('stale'),'m0-stale-'.wp_generate_uuid4());}catch(InvalidArgumentException$e){$stale=$e->getMessage()==='stale_enrolment_state';}dzn_m0_assert($stale,'Stale state failed');
// Rollback after each write boundary.
foreach(array('dzn_phase_2a2m0_after_projection_update','dzn_phase_2a2m0_after_lifecycle_event_insert','dzn_phase_2a2m0_after_command_insert')as$index=>$hook){$target=(int)$sources[8+$index]['enrolment_id'];$before=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}enrolment_lifecycle_events WHERE enrolment_id=%d",$target));$fail=static function(){throw new RuntimeException('injected');};add_action($hook,$fail);try{$service->activate($target,'authorised',dzn_m0_evidence($hook),'m0-fail-'.wp_generate_uuid4());}catch(RuntimeException$e){dzn_m0_assert($e->getMessage()==='injected','Unexpected injected failure');}finally{remove_action($hook,$fail);}$projection=$wpdb->get_row($wpdb->prepare("SELECT lifecycle_state,applicable_slot FROM {$p}enrolments WHERE id=%d",$target));dzn_m0_assert($projection->lifecycle_state==='authorised'&&(int)$projection->applicable_slot===1&&(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}enrolment_lifecycle_events WHERE enrolment_id=%d",$target))===$before&&(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}enrolment_lifecycle_commands WHERE enrolment_id=%d",$target))===0,'Atomic rollback failed');}
// Applicable canonical Term blocks close without subordinate mutation.
$guard=(int)$sources[1]['enrolment_id'];$term=(new CanonicalTermAuthorityService())->create($guard,null,null,dzn_m0_evidence('term'),'m0-term-'.wp_generate_uuid4());$blocked=false;try{$service->close($guard,'authorised',dzn_m0_evidence('blocked'),'m0-blocked-'.wp_generate_uuid4());}catch(InvalidArgumentException$e){$blocked=$e->getMessage()==='applicable_term_exists';}dzn_m0_assert($blocked&&(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}terms WHERE id=%d AND lifecycle_state='authorised'",$term['term_id']))===1,'Term closure guard failed');
// Real Assignment authority blocks closure, terminal authority permits it, and no guard cascades Assignment mutation.
$assignments=new TeacherAssignmentService();$assignmentGuard=(int)$sources[2]['enrolment_id'];$assigned=$assignments->assignInitial($assignmentGuard,'m0-assign-'.wp_generate_uuid4());$blocked=false;try{$service->close($assignmentGuard,'authorised',dzn_m0_evidence('assignment-blocked'),'m0-assignment-blocked-'.wp_generate_uuid4());}catch(InvalidArgumentException$e){$blocked=$e->getMessage()==='applicable_teacher_assignment_exists';}$assignmentRow=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}teacher_assignments WHERE id=%d",$assigned['assignment_id']));dzn_m0_assert($blocked&&$assignmentRow->state==='assigned'&&(int)$assignmentRow->applicable_slot===1,'Assignment closure guard mutated or failed');$assignments->end($assignmentGuard,array('expected_assignment_id'=>$assigned['assignment_id'],'evidence_channel'=>'email','evidence_reference'=>'m0-end','evidence_at'=>gmdate('Y-m-d H:i:s'),'reason_code'=>'service_ended'),'m0-end-'.wp_generate_uuid4());$service->close($assignmentGuard,'authorised',dzn_m0_evidence('after-end'),'m0-after-end-'.wp_generate_uuid4());
// Malformed and combined subordinate authority fail closed without partial mutation.
$malformed=(int)$sources[3]['enrolment_id'];$bad=$assignments->assignInitial($malformed,'m0-bad-'.wp_generate_uuid4());$wpdb->update($p.'teacher_assignments',array('assignment_sequence'=>2),array('id'=>$bad['assignment_id']));$rejected=false;try{$service->close($malformed,'authorised',dzn_m0_evidence('malformed'),'m0-malformed-'.wp_generate_uuid4());}catch(InvalidArgumentException$e){$rejected=$e->getMessage()==='subordinate_assignment_integrity_conflict';}dzn_m0_assert($rejected,'Malformed Assignment aggregate did not fail closed');
$combined=(int)$sources[4]['enrolment_id'];$combinedAssignment=$assignments->assignInitial($combined,'m0-combined-assignment-'.wp_generate_uuid4());$combinedTerm=(new CanonicalTermAuthorityService())->create($combined,null,null,dzn_m0_evidence('combined-term'),'m0-combined-term-'.wp_generate_uuid4());$blocked=false;try{$service->close($combined,'authorised',dzn_m0_evidence('combined'),'m0-combined-'.wp_generate_uuid4());}catch(InvalidArgumentException$e){$blocked=$e->getMessage()==='applicable_term_exists';}dzn_m0_assert($blocked&&(string)$wpdb->get_var($wpdb->prepare("SELECT state FROM {$p}teacher_assignments WHERE id=%d",$combinedAssignment['assignment_id']))==='assigned'&&(string)$wpdb->get_var($wpdb->prepare("SELECT lifecycle_state FROM {$p}terms WHERE id=%d",$combinedTerm['term_id']))==='authorised','Combined guard cascaded or failed');
// Direct closure from every non-terminal state uses converted Enrolments and preserves slot semantics.
$service->close((int)$sources[5]['enrolment_id'],'authorised',dzn_m0_evidence('close-authorised'),'m0-close-authorised-'.wp_generate_uuid4());$service->activate((int)$sources[6]['enrolment_id'],'authorised',dzn_m0_evidence('activate-close'),'m0-activate-close-'.wp_generate_uuid4());$service->close((int)$sources[6]['enrolment_id'],'current',dzn_m0_evidence('close-current'),'m0-close-current-'.wp_generate_uuid4());$service->activate((int)$sources[7]['enrolment_id'],'authorised',dzn_m0_evidence('activate-pause'),'m0-activate-pause-'.wp_generate_uuid4());$service->pause((int)$sources[7]['enrolment_id'],'current',dzn_m0_evidence('pause-close'),'m0-pause-close-'.wp_generate_uuid4());$service->close((int)$sources[7]['enrolment_id'],'paused',dzn_m0_evidence('close-paused'),'m0-close-paused-'.wp_generate_uuid4());
// Exact result-event corruption fails replay.
$corrupt=(int)$sources[11]['enrolment_id'];$proof=dzn_m0_evidence('corrupt');$key='m0-corrupt-'.wp_generate_uuid4();$service->activate($corrupt,'authorised',$proof,$key);$digest=CanonicalEnrolmentLifecycleIdempotency::keyDigest($key);$wpdb->update($p.'enrolment_lifecycle_commands',array('result_state'=>'closed'),array('command_key_digest'=>$digest));$rejected=false;try{$service->activate($corrupt,'authorised',$proof,$key);}catch(RuntimeException){$rejected=true;}dzn_m0_assert($rejected,'Corrupt command replay succeeded');
$commands=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}enrolment_lifecycle_commands");Migrator::maybe_upgrade();dzn_m0_assert($commands===(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}enrolment_lifecycle_commands"),'Repeat upgrade changed evidence');
echo "schema_18_to_19=pass\ncapability=pass\nproduction_conversion_fixture=pass\nlifecycle_graph=pass\nhistorical_replay=pass\nidempotency_conflict=pass\nstale=pass\nwrite_boundary_rollback=pass\nterm_closure_guard=pass\nassignment_closure_guard=pass\nterminal_assignment_allows_close=pass\nmalformed_assignment_guard=pass\ncombined_guard=pass\nclosure_from_all_nonterminal_states=pass\ncorruption=pass\nrepeat_upgrade=pass\nPhase 2A.2-M0 runtime passed\n";
