<?php
if (getenv('DZN_PHASE_2A2J_RUNTIME_TEST') !== 'concurrency' || !defined('WP_CLI') || !WP_CLI) { fwrite(STDERR, "Phase 2A.2-J concurrency worker refused.\n"); exit(1); }
use Delnavazan\Platform\Core\Application\{ArchiveService,PrincipalInvitationService,TeacherAssignmentService};
global $wpdb; $state = get_option('dzn_phase_2a2j_race_state'); $worker = (string) getenv('DZN_PHASE_2A2J_WORKER'); $gate = (string) getenv('DZN_PHASE_2A2J_GATE_DIR');
if (!is_array($state) || !in_array($worker, array('w1', 'w2'), true) || !is_dir($gate)) throw new RuntimeException('Invalid Phase J worker state');
$touch = static function(string $name, string $value = '') use ($gate): void { if (file_put_contents($gate . '/' . $name, $value) === false) throw new RuntimeException('Gate write failed'); };
$touch($worker . '.connection', (string) $wpdb->get_var('SELECT CONNECTION_ID()')); $touch($worker . '.started');
$wait = static function(string $name) use ($gate): void { for ($i = 0; $i < 600 && !is_file($gate . '/' . $name); $i++) usleep(100000); if (!is_file($gate . '/' . $name)) throw new RuntimeException('Release gate timeout'); };
$offboardFirst = in_array($state['mode'], array('o2_offboard_initial','o4_offboard_staff_replace','o6_offboard_authenticated_replace'), true);
if ($worker === 'w1' && $offboardFirst) {
    add_filter('query', static function(string $query) use ($touch, $wait, $worker): string { static $gated = false; if (!$gated && str_contains($query, 'dzn_teacher_invitations') && str_contains($query, 'FOR UPDATE')) { $gated = true; $touch($worker . '.locked'); $wait('release'); } return $query; }, PHP_INT_MAX);
} elseif ($worker === 'w1') {
    $hook = match ($state['mode']) { 'u1_unrelated_roots' => 'dzn_phase_2a2i_identity_root_locked', 'e_archive_initial', 'e_archive_replace' => 'dzn_phase_2a2j_teacher_archive_lock_held', default => 'dzn_phase_2a2j_assignment_locks_held' };
    if (!in_array($state['mode'], array('f_close_initial','f_close_replace'), true)) add_action($hook, static function() use ($touch, $wait, $worker): void { $touch($worker . '.locked'); $wait('release'); });
}
$service = new TeacherAssignmentService();
try {
    $mode = (string) $state['mode'];
    if ($mode === 'u1_unrelated_roots') { $source = get_option('dzn_phase_2a2j_fixture')['sources'][$worker === 'w1' ? 0 : 1]; $wpdb->query('SET TRANSACTION ISOLATION LEVEL READ COMMITTED'); $wpdb->query('START TRANSACTION'); try { $root = $wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}dzn_enrolment_identity_roots WHERE student_id=%d AND course_id=%d FOR UPDATE", (int) $source['student_id'], (int) $source['course_id'])); if (!$root) throw new RuntimeException('Identity root unavailable'); do_action('dzn_phase_2a2i_identity_root_locked'); $wpdb->query('COMMIT'); echo "outcome=root_locked root={$root->id}\n"; } catch (Throwable $e) { $wpdb->query('ROLLBACK'); throw $e; } }
    elseif (($worker === 'w1' && $offboardFirst) || ($worker === 'w2' && in_array($mode, array('o1_initial_offboard','o3_staff_replace_offboard','o5_authenticated_replace_offboard'), true))) { $teacher = (int) $state['offboard_teacher']; $reason = 'phase_j_' . substr(hash('sha256', (string) $state['key_one']), 0, 24); (new PrincipalInvitationService())->offboard($teacher, $reason); echo "outcome=offboarded teacher={$teacher}\n"; }
    elseif ($worker === 'w1' && in_array($mode, array('e_archive_initial','e_archive_replace'), true)) { $teacher = $mode === 'e_archive_initial' ? (int) $state['teacher_initial'] : (int) $state['teacher_one']; (new ArchiveService())->archive('teacher', $teacher); echo "outcome=archived teacher={$teacher}\n"; }
    elseif ($worker === 'w1' && in_array($mode, array('f_close_initial','f_close_replace'), true)) { $wpdb->query('START TRANSACTION'); try { $id = (int) $state['enrolment_id']; $wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}dzn_enrolments WHERE id=%d FOR UPDATE", $id)); $touch('w1.locked'); $wait('release'); dzn_2a2j_race_close($id); $wpdb->query('COMMIT'); echo "outcome=closed enrolment={$id}\n"; } catch (Throwable $e) { $wpdb->query('ROLLBACK'); throw $e; } }
    elseif ($worker === 'w2' && in_array($mode, array('e_initial_archive','e_replace_archive'), true)) { $teacher = $mode === 'e_initial_archive' ? (int) $state['teacher_initial'] : (int) $state['teacher_one']; (new ArchiveService())->archive('teacher', $teacher); echo "outcome=archived teacher={$teacher}\n"; }
    elseif ($worker === 'w2' && in_array($mode, array('f_initial_close','f_replace_close'), true)) { $wpdb->query('START TRANSACTION'); try { $id = (int) $state['enrolment_id']; $wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}dzn_enrolments WHERE id=%d FOR UPDATE", $id)); dzn_2a2j_race_close($id); $wpdb->query('COMMIT'); echo "outcome=closed enrolment={$id}\n"; } catch (Throwable $e) { $wpdb->query('ROLLBACK'); throw $e; } }
    elseif (in_array($mode, array('a_same_teacher_keys','e_initial_archive','e_archive_initial','f_initial_close','f_close_initial','o1_initial_offboard','o2_offboard_initial','u2_shared_teacher'), true)) { $target = $mode === 'u2_shared_teacher' && $worker === 'w2' ? (int) $state['other_enrolment_id'] : (int) $state['enrolment_id']; $result = $service->assignInitial($target, (string) $state[$worker === 'w1' ? 'key_one' : 'key_two']); $outcome = $result['created'] ? 'created' : ($result['already_applied'] ? 'already_applied' : 'replay'); echo "outcome={$outcome} assignment={$result['assignment_id']}\n"; }
    elseif ($worker === 'w2' && $mode === 'c_replace_end') { $evidence = array('expected_assignment_id' => (int) $state['expected_assignment_id'], 'evidence_channel' => 'email', 'evidence_reference' => 'race-end', 'evidence_at' => (string) $state['evidence_at'], 'reason_code' => 'service_ended'); $result = $service->end((int) $state['enrolment_id'], $evidence, (string) $state['key_two']); echo "outcome=" . ($result['created'] ? 'created' : 'already_applied') . " assignment={$result['assignment_id']}\n"; }
    else {
        $teacher = (int) $state[$worker === 'w1' ? 'teacher_one' : 'teacher_two'];
        if (in_array($mode, array('o3_staff_replace_offboard','o4_offboard_staff_replace'), true)) $teacher = (int) $state['teacher_one'];
        if (in_array($mode, array('o5_authenticated_replace_offboard','o6_offboard_authenticated_replace'), true)) { $teacher = (int) $state['teacher_two']; wp_set_current_user((int) $state['authenticated_teacher_user']); }
        $reference = $mode === 'd2_replace_same' ? 'race-shared-agreement' : 'race-' . $worker . '-agreement';
        $route = in_array($mode, array('o5_authenticated_replace_offboard','o6_offboard_authenticated_replace'), true) ? 'authenticated_teacher' : 'staff_attestation';
        $evidence = array('expected_assignment_id' => (int) $state['expected_assignment_id'], 'route' => $route, 'evidence_channel' => 'phone', 'evidence_reference' => $reference, 'evidence_at' => (string) $state['evidence_at']);
        $result = $service->replace((int) $state['enrolment_id'], $teacher, $evidence, (string) $state[$worker === 'w1' ? 'key_one' : 'key_two']);
        $outcome = $result['created'] ? 'created' : ($result['idempotent'] ? 'replay' : ($result['already_applied'] ? 'already_applied' : 'unknown')); echo "outcome={$outcome} assignment={$result['assignment_id']}\n";
    }
} catch (Throwable $exception) { echo 'outcome=' . $exception->getMessage() . ' class=' . $exception::class . "\n"; }
finally { $touch($worker . '.finished'); }
function dzn_2a2j_race_close(int $id): void { global $wpdb; $p = $wpdb->prefix . 'dzn_'; $at = gmdate('Y-m-d H:i:s'); if ($wpdb->update($p . 'enrolments', array('lifecycle_state' => 'closed', 'applicable_slot' => null), array('id' => $id, 'lifecycle_state' => 'authorised', 'applicable_slot' => 1)) !== 1) throw new RuntimeException('Closure update failed'); if ($wpdb->insert($p . 'enrolment_lifecycle_events', array('uid' => \Delnavazan\Platform\Core\Support\Identifier::uid(), 'enrolment_id' => $id, 'event_sequence' => 2, 'from_state' => 'authorised', 'to_state' => 'closed', 'lineage_meaning' => null, 'reason_code' => 'synthetic_concurrency_closure', 'evidence_channel' => 'runtime_test', 'evidence_reference' => hash('sha256', 'closure:' . $id . ':' . wp_generate_uuid4()), 'occurred_at' => $at, 'recorded_at' => $at, 'recorded_by' => get_current_user_id(), 'created_at' => $at, 'created_by' => get_current_user_id())) !== 1) throw new RuntimeException('Closure evidence insert failed: ' . $wpdb->last_error); }
