<?php
/* Source contract only; database and REST behaviour requires isolated WordPress/MySQL validation. */
$root=dirname(__DIR__);$migration=file_get_contents($root.'/src/Core/Infrastructure/Migration/Migrator.php');$validation=file_get_contents($root.'/src/Core/Application/BookingRequestValidationService.php');$submission=file_get_contents($root.'/src/Core/Application/BookingRequestSubmissionService.php');$repository=file_get_contents($root.'/src/Core/Infrastructure/Repository/BookingRequestRepository.php');$normalizer=file_get_contents($root.'/src/Core/Application/RequestedTimeNormalizer.php');$rest=file_get_contents($root.'/src/Public/BookingRequestRestController.php');$admin=file_get_contents($root.'/src/Admin/Controller/BookingRequestController.php');
foreach(['006_booking_request_core','booking_requests','booking_request_contact_snapshots','booking_request_requested_times','UNIQUE KEY request_snapshot','UNIQUE KEY request_sequence','UNIQUE KEY request_time_fact','verify_booking_request_schema','booking request table must use InnoDB']as$f)if(strpos($migration,$f)===false)throw new RuntimeException('Missing booking schema contract: '.$f);
foreach(['full_name','country','city','privacy_notice_accepted','2026-09-05','whatsapp_same_as_mobile','public_rest_booking_request','requested_instrument_id','array_diff( array_keys( $input ), $allowed )','Unsupported public intake field','At least one requested time required','Duplicate requested time','Valid active Intro Course for Instrument required']as$f)if(strpos($validation.$repository.$migration,$f)===false)throw new RuntimeException('Missing booking validation contract: '.$f);
foreach(['START TRANSACTION','createRequest','createSnapshot','createTime','rollback',"'REQ-' . \$uid",'submitted','unresolved','+24 months']as$f)if(strpos($submission.$repository,$f)===false)throw new RuntimeException('Missing aggregate atomicity contract: '.$f);
foreach(['AvailabilityLocalTime::wall','instructional_ends_at_utc','occupied_ends_at_utc','Invalid requested duration or buffer','canonical seconds-qualified wall time']as$f)if(strpos($normalizer,$f)===false)throw new RuntimeException('Missing requested-time contract: '.$f);
foreach(['register_rest_route','POST','invalid_request','permission_callback','__return_true']as$f)if(strpos($rest,$f)===false)throw new RuntimeException('Missing public submission contract: '.$f);if(strpos($submission,'request_reference')===false)throw new RuntimeException('Missing non-authorizing public reference contract');
foreach(['dzn_view_booking_requests','esc_html','Booking Requests']as$f)if(strpos($admin,$f)===false)throw new RuntimeException('Missing protected inspection contract: '.$f);
if(preg_match('/(?:amelia_|wp_amelia|teacher_offers|booking_routes|platform_payments|createStudent|createLesson)/i',$migration.$validation.$submission.$repository.$rest))throw new RuntimeException('Phase 2A.1-C introduced prohibited authority');
echo "Phase 2A.1-C source contract passed\n";
