<?php
/** Prepares synthetic production-path authority chains for a named Phase-M race. */
if(getenv('DZN_PHASE_2A2M_RUNTIME_TEST')!=='concurrency'||!defined('WP_CLI')||!WP_CLI){fwrite(STDERR,"Phase 2A.2-M setup refused.\n");exit(1);}
use Delnavazan\Platform\Core\Application\{CanonicalEnrolmentLifecycleService,CanonicalLessonAuthorityService,CanonicalTermAuthorityService,TeacherAssignmentService};
$mode=(string)getenv('DZN_PHASE_2A2M_MODE');$fixture=get_option('dzn_phase_2a2j_fixture');if(!is_array($fixture)||count($fixture['sources']??array())<2)throw new RuntimeException('Phase-J fixture required');$at=gmdate('Y-m-d H:i:s');$e=static fn(string$r)=>array('evidence_channel'=>'staff_record','evidence_reference'=>$r,'evidence_at'=>gmdate('Y-m-d H:i:s'));$enrolment=new CanonicalEnrolmentLifecycleService();$term=new CanonicalTermAuthorityService();$assignment=new TeacherAssignmentService();$lesson=new CanonicalLessonAuthorityService();$ready=function(int$index)use($fixture,$enrolment,$term,$assignment,$e):array{$id=(int)$fixture['sources'][$index]['enrolment_id'];$enrolment->activate($id,'authorised',$e('activate-'.$index),'race-activate-'.$index.'-'.wp_generate_uuid4());$t=$term->create($id,null,null,$e('term-'.$index),'race-term-'.$index.'-'.wp_generate_uuid4());$term->activate((int)$t['term_id'],'authorised',$e('term-active-'.$index),'race-term-active-'.$index.'-'.wp_generate_uuid4());$a=$assignment->assignInitial($id,'race-assignment-'.$index.'-'.wp_generate_uuid4());return array('enrolment_id'=>$id,'term_id'=>(int)$t['term_id'],'assignment_id'=>(int)$a['assignment_id']);};
$one=$ready(0);$state=$one+array('at'=>$at,'key'=>'race-'.wp_generate_uuid4(),'keys'=>array('w1'=>'race-w1-'.wp_generate_uuid4(),'w2'=>'race-w2-'.wp_generate_uuid4()),'references'=>array('w1'=>'race-w1','w2'=>'race-w2'));
if(in_array($mode,array('replacement_same','replacement_diff','replacement_final'),true)){$origin=(int)$lesson->createStandard($one['term_id'],$one['assignment_id'],$e('origin'),'origin-standard-'.wp_generate_uuid4())['lesson_id'];$lesson->cancel($origin,'authorised',$e('eligible')+array('reason_code'=>'attested_non_delivery'),'origin-cancel-'.wp_generate_uuid4());$state['origin_id']=$origin;}
if($mode==='replacement_same'){$state['actions']=array('w1'=>'replacement','w2'=>'replacement');$state['keys']['w2']=$state['keys']['w1'];$state['references']['w2']=$state['references']['w1'];}
elseif($mode==='replacement_diff')$state['actions']=array('w1'=>'replacement','w2'=>'replacement');
elseif($mode==='replacement_final'){ $lesson->createReplacement($one['term_id'],$one['assignment_id'],(int)$state['origin_id'],$e('first-replacement'),'first-replacement-'.wp_generate_uuid4());$originTwo=(int)$lesson->createStandard($one['term_id'],$one['assignment_id'],$e('origin-two'),'origin-two-'.wp_generate_uuid4())['lesson_id'];$lesson->cancel($originTwo,'authorised',$e('eligible-two')+array('reason_code'=>'attested_non_delivery'),'origin-two-cancel-'.wp_generate_uuid4());$originThree=(int)$lesson->createStandard($one['term_id'],$one['assignment_id'],$e('origin-three'),'origin-three-'.wp_generate_uuid4())['lesson_id'];$lesson->cancel($originThree,'authorised',$e('eligible-three')+array('reason_code'=>'attested_non_delivery'),'origin-three-cancel-'.wp_generate_uuid4());$state['origin_id']=$originTwo;$state['origin_ids']=array('w1'=>$originTwo,'w2'=>$originThree);$state['actions']=array('w1'=>'replacement','w2'=>'replacement');}
elseif($mode==='unrelated'){$two=$ready(1);$state['actions']=array('w1'=>'lesson','w2'=>'lesson');$state['chains']=array('w1'=>$one,'w2'=>$two);}
else{$pairs=array('term_close_lesson'=>array('term_close','lesson'),'term_cancel_lesson'=>array('term_cancel','lesson'));$parts=$pairs[$mode]??explode('_',$mode,2);if(count($parts)!==2)throw new RuntimeException('Unknown race mode');$map=array('lesson'=>'lesson','pause'=>'pause','close'=>'close','term_close'=>'term_close','term_cancel'=>'term_cancel','replace'=>'replace');$state['actions']=array('w1'=>$map[$parts[0]]??null,'w2'=>$map[$parts[1]]??null);if(in_array(null,$state['actions'],true))throw new RuntimeException('Unknown race action');if(in_array('replace',$state['actions'],true))$state['new_teacher_id']=(int)$fixture['teachers'][1];}
update_option('dzn_phase_2a2m_concurrency_state',$state,false);echo 'mode='.$mode.' state='.wp_json_encode($state)."\n";
