<?php
/** Disposable Schema 12 -> 13 and repeat-safe migration validation. */
if(getenv('DZN_PHASE_2A2G_RUNTIME_TEST')!=='migration'||!defined('WP_CLI')||!WP_CLI||!in_array(wp_get_environment_type(),array('local','development'),true)){fwrite(STDERR,"Phase 2A.2-G migration runtime refused.\n");exit(1);}
use Delnavazan\Platform\Core\Infrastructure\Migration\Migrator;
global $wpdb;$p=$wpdb->prefix.'dzn_';
function dzn_2a2g_m_assert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
function dzn_2a2g_m_index(string $table,string $name,bool $unique,array $columns):bool{global $wpdb;$rows=$wpdb->get_results($wpdb->prepare("SHOW INDEX FROM {$table} WHERE Key_name=%s",$name));if(!$rows)return false;usort($rows,static fn($a,$b)=>(int)$a->Seq_in_index<=>(int)$b->Seq_in_index);return(!$unique||(int)$rows[0]->Non_unique===0)&&array_map(static fn($row)=>(string)$row->Column_name,$rows)===$columns;}
dzn_2a2g_m_assert((string)get_option('dzn_platform_schema_version')==='13','Schema 12 -> 13 did not complete');
$done=(array)get_option('dzn_platform_completed_migrations',array());dzn_2a2g_m_assert(count(array_keys($done,'013_final_acceptance_arrangement_foundation',true))===1,'Migration 013 completion missing or duplicated');
foreach(array('accepted_service_arrangements','proposal_option_outcome_events')as$table){$physical=$p.$table;dzn_2a2g_m_assert($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$physical))===$physical,'Missing '.$table);dzn_2a2g_m_assert(strcasecmp((string)$wpdb->get_var($wpdb->prepare('SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s',$physical)),'InnoDB')===0,'Non-InnoDB '.$table);dzn_2a2g_m_assert(!$wpdb->get_row("SHOW COLUMNS FROM {$physical} LIKE 'updated_at'"),'Mutable updated_at present on '.$table);}
foreach(array(array('accepted_service_arrangements','proposal_family_id',true,array('proposal_family_id')),array('accepted_service_arrangements','proposal_option_id',true,array('proposal_option_id')),array('accepted_service_arrangements','command_key_digest',true,array('command_key_digest')),array('proposal_option_outcome_events','proposal_option_id',true,array('proposal_option_id')))as[$table,$index,$unique,$columns])dzn_2a2g_m_assert(dzn_2a2g_m_index($p.$table,$index,$unique,$columns),'Incorrect index '.$table.'.'.$index);
$role=get_role('administrator');dzn_2a2g_m_assert($role&&$role->has_cap('dzn_finalize_service_arrangements'),'Final acceptance capability installation failed');$role->remove_cap('dzn_finalize_service_arrangements');Migrator::maybe_upgrade();dzn_2a2g_m_assert($role->has_cap('dzn_finalize_service_arrangements'),'Final acceptance capability repair failed');
$before=array((int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}accepted_service_arrangements"),(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}proposal_option_outcome_events"));Migrator::maybe_upgrade();$after=array((int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}accepted_service_arrangements"),(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}proposal_option_outcome_events"));$done=(array)get_option('dzn_platform_completed_migrations',array());dzn_2a2g_m_assert($before===$after&&count(array_keys($done,'013_final_acceptance_arrangement_foundation',true))===1,'Repeated migration changed immutable history');
echo "Phase 2A.2-G Schema 12 -> 13 migration runtime passed\n";
