<?php
/** Disposable Schema 18 -> 19 and canonical Enrolment lifecycle runtime proof. */
if(getenv('DZN_PHASE_2A2M0_RUNTIME_TEST')!=='authority'||!defined('WP_CLI')||!WP_CLI||!in_array(wp_get_environment_type(),array('local','development'),true)){fwrite(STDERR,"Phase 2A.2-M0 runtime refused.\n");exit(1);}
use Delnavazan\Platform\Core\Application\{CanonicalEnrolmentLifecycleIdempotency,CanonicalEnrolmentLifecycleService,CanonicalTermAuthorityService,IdempotencyConflictException};
use Delnavazan\Platform\Core\Infrastructure\Migration\Migrator;
use Delnavazan\Platform\Core\Support\Identifier;
global$wpdb;$p=$wpdb->prefix.'dzn_';function dzn_m0_assert(bool$v,string$m):void{if(!$v)throw new RuntimeException($m);}function dzn_m0_evidence(string$r):array{return array('evidence_channel'=>'staff_record','evidence_reference'=>$r,'evidence_at'=>gmdate('Y-m-d H:i:s'));}
function dzn_m0_fixture(string$suffix):int{global$wpdb;$p=$wpdb->prefix.'dzn_';$n=random_int(400000000,600000000);$now=gmdate('Y-m-d H:i:s');$actor=get_current_user_id();dzn_m0_assert($wpdb->insert($p.'enrolment_identity_roots',array('student_id'=>$n,'course_id'=>$n,'created_at'=>$now,'created_by'=>$actor))===1,'Root fixture failed');dzn_m0_assert($wpdb->insert($p.'enrolments',array('uid'=>Identifier::uid(),'reference_code'=>null,'student_id'=>$n,'teacher_id'=>null,'course_id'=>$n,'status'=>'canonical','record_model'=>'canonical_student_course_v1','accepted_service_arrangement_id'=>$n,'lifecycle_state'=>'authorised','applicable_slot'=>1,'predecessor_enrolment_id'=>null,'lineage_meaning'=>null,'created_at'=>$now,'updated_at'=>$now,'created_by'=>$actor,'updated_by'=>$actor))===1,'Enrolment fixture failed');$id=(int)$wpdb->insert_id;dzn_m0_assert($wpdb->insert($p.'enrolment_lifecycle_events',array('uid'=>Identifier::uid(),'enrolment_id'=>$id,'event_sequence'=>1,'from_state'=>null,'to_state'=>'authorised','lineage_meaning'=>null,'reason_code'=>'accepted_service_arrangement_conversion','evidence_channel'=>'platform_conversion_command','evidence_reference'=>hash('sha256','fixture-'.$suffix),'occurred_at'=>$now,'recorded_at'=>$now,'recorded_by'=>$actor,'created_at'=>$now,'created_by'=>$actor))===1,'Origin fixture failed');return$id;}
// Migration, repeat safety and capability repair.
$wpdb->query("DROP TABLE IF EXISTS {$p}enrolment_lifecycle_commands");$done=array_values(array_filter((array)get_option('dzn_platform_completed_migrations',array()),static fn($id)=>$id!=='019_canonical_enrolment_lifecycle_authority'));update_option('dzn_platform_completed_migrations',$done,false);update_option('dzn_platform_schema_version','18',false);update_option('dzn_platform_capability_version','2a2l',false);$admin=get_role('administrator');$admin->remove_cap('dzn_manage_canonical_enrolment_lifecycle');Migrator::maybe_upgrade();dzn_m0_assert((string)get_option('dzn_platform_schema_version')==='19'&&$admin->has_cap('dzn_manage_canonical_enrolment_lifecycle')&&!get_role('dzn_teacher')->has_cap('dzn_manage_canonical_enrolment_lifecycle'),'Migration/capability failed');
$service=new CanonicalEnrolmentLifecycleService();$id=dzn_m0_fixture('progress');$activateEvidence=dzn_m0_evidence('activate');$activateKey='m0-activate-'.wp_generate_uuid4();$activate=$service->activate($id,'authorised',$activateEvidence,$activateKey);$service->pause($id,'current',dzn_m0_evidence('pause'),'m0-pause-'.wp_generate_uuid4());$replay=$service->activate($id,'authorised',$activateEvidence,$activateKey);dzn_m0_assert($replay['idempotent']&&$replay['event_id']===$activate['event_id'],'Historical replay after progression failed');$service->resume($id,'paused',dzn_m0_evidence('resume'),'m0-resume-'.wp_generate_uuid4());$service->close($id,'current',dzn_m0_evidence('close'),'m0-close-'.wp_generate_uuid4());$row=$wpdb->get_row($wpdb->prepare("SELECT lifecycle_state,applicable_slot FROM {$p}enrolments WHERE id=%d",$id));dzn_m0_assert($row->lifecycle_state==='closed'&&$row->applicable_slot===null,'Lifecycle/slot graph failed');
$conflict=false;try{$service->activate($id,'authorised',dzn_m0_evidence('changed'),$activateKey);}catch(IdempotencyConflictException){$conflict=true;}dzn_m0_assert($conflict,'Same-key conflict failed');$stale=false;try{$service->resume($id,'paused',dzn_m0_evidence('stale'),'m0-stale-'.wp_generate_uuid4());}catch(InvalidArgumentException$e){$stale=$e->getMessage()==='stale_enrolment_state';}dzn_m0_assert($stale,'Stale state failed');
// Rollback after each write boundary.
foreach(array('dzn_phase_2a2m0_after_projection_update','dzn_phase_2a2m0_after_lifecycle_event_insert','dzn_phase_2a2m0_after_command_insert')as$hook){$target=dzn_m0_fixture($hook);$before=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}enrolment_lifecycle_events WHERE enrolment_id=%d",$target));$fail=static function(){throw new RuntimeException('injected');};add_action($hook,$fail);try{$service->activate($target,'authorised',dzn_m0_evidence($hook),'m0-fail-'.wp_generate_uuid4());}catch(RuntimeException$e){dzn_m0_assert($e->getMessage()==='injected','Unexpected injected failure');}finally{remove_action($hook,$fail);}$projection=$wpdb->get_row($wpdb->prepare("SELECT lifecycle_state,applicable_slot FROM {$p}enrolments WHERE id=%d",$target));dzn_m0_assert($projection->lifecycle_state==='authorised'&&(int)$projection->applicable_slot===1&&(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}enrolment_lifecycle_events WHERE enrolment_id=%d",$target))===$before&&(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}enrolment_lifecycle_commands WHERE enrolment_id=%d",$target))===0,'Atomic rollback failed');}
// Applicable canonical Term blocks close without subordinate mutation.
$guard=dzn_m0_fixture('term-guard');$term=(new CanonicalTermAuthorityService())->create($guard,null,null,dzn_m0_evidence('term'),'m0-term-'.wp_generate_uuid4());$blocked=false;try{$service->close($guard,'authorised',dzn_m0_evidence('blocked'),'m0-blocked-'.wp_generate_uuid4());}catch(InvalidArgumentException$e){$blocked=$e->getMessage()==='applicable_term_exists';}dzn_m0_assert($blocked&&(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}terms WHERE id=%d AND lifecycle_state='authorised'",$term['term_id']))===1,'Term closure guard failed');
// Exact result-event corruption fails replay.
$corrupt=dzn_m0_fixture('corrupt');$proof=dzn_m0_evidence('corrupt');$key='m0-corrupt-'.wp_generate_uuid4();$service->activate($corrupt,'authorised',$proof,$key);$digest=CanonicalEnrolmentLifecycleIdempotency::keyDigest($key);$wpdb->update($p.'enrolment_lifecycle_commands',array('result_state'=>'closed'),array('command_key_digest'=>$digest));$rejected=false;try{$service->activate($corrupt,'authorised',$proof,$key);}catch(RuntimeException){$rejected=true;}dzn_m0_assert($rejected,'Corrupt command replay succeeded');
$commands=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}enrolment_lifecycle_commands");Migrator::maybe_upgrade();dzn_m0_assert($commands===(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}enrolment_lifecycle_commands"),'Repeat upgrade changed evidence');
echo "schema_18_to_19=pass\ncapability=pass\nlifecycle_graph=pass\nhistorical_replay=pass\nidempotency_conflict=pass\nstale=pass\nwrite_boundary_rollback=pass\nterm_closure_guard=pass\ncorruption=pass\nrepeat_upgrade=pass\nPhase 2A.2-M0 runtime passed\n";
