<?php
/** Build synthetic, fully accepted Schema 14 sources through pre-I application services. */
if(getenv('DZN_PHASE_2A2I_RUNTIME_TEST')!=='schema14_fixture'||!defined('WP_CLI')||!WP_CLI||!in_array(wp_get_environment_type(),array('local','development'),true)){fwrite(STDERR,"Phase 2A.2-I Schema 14 fixture refused.\n");exit(1);}
if((string)DZN_PLATFORM_SCHEMA_VERSION!=='14'||DZN_PLATFORM_BUILD_ID!=='phase2a2h-canonical-enrolment-foundation-20260913.1')throw new RuntimeException('Exact Schema 14 base required');
use Delnavazan\Platform\Core\Application\{BookingRequestSubmissionService,CatalogueService,CoordinationCaseService,FinalAcceptanceService,ProposalAcceptanceService,ProposalService,StudentAcceptanceAuthorityService,StudentIdentityResolutionService,TeacherAcceptingStateService,TeacherAvailabilityAssentService,TeacherAvailabilityService,TeacherService,TeachingEligibilityService};
use Delnavazan\Platform\Core\Infrastructure\Repository\EnrolmentRepository;
global$wpdb;$p=$wpdb->prefix.'dzn_';$actor=get_current_user_id();$at=gmdate('Y-m-d H:i:s');$suffix=substr(hash('sha256',wp_generate_uuid4()),0,10);
function dzn_2a2i_fixture_assert(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);}
$catalogue=new CatalogueService();$instrument=$catalogue->instrument(array('slug'=>'phase-i-'.$suffix,'name_fa'=>'آزمون','name_en'=>'Synthetic Phase I','status'=>'active'));
$course1=$catalogue->course(array('instrument_id'=>$instrument,'name_fa'=>'آزمون یک','name_en'=>'Synthetic I One','course_type'=>'introductory','status'=>'active','default_duration_minutes'=>30,'default_buffer_minutes'=>15));
$course2=$catalogue->course(array('instrument_id'=>$instrument,'name_fa'=>'آزمون دو','name_en'=>'Synthetic I Two','course_type'=>'introductory','status'=>'active','default_duration_minutes'=>30,'default_buffer_minutes'=>15));
$teacher=(new TeacherService())->create(array('display_name'=>'Synthetic Phase I Teacher','email'=>'teacher-'.$suffix.'@phase-2a2i.invalid'));
$wpdb->insert($p.'teacher_onboarding_states',array('teacher_id'=>$teacher,'state'=>'active','readiness_state'=>'ready','version'=>1,'created_at'=>$at,'updated_at'=>$at,'created_by'=>$actor,'updated_by'=>$actor));
foreach(array($course1,$course2)as$course)(new TeachingEligibilityService())->setEligibility(array('teacher_id'=>$teacher,'course_id'=>$course,'status'=>'active','reason_code'=>'synthetic_fixture'));
(new TeacherAcceptingStateService())->set(array('teacher_id'=>$teacher,'state'=>'accepting','reason_code'=>'synthetic_fixture'));
(new TeacherAvailabilityService())->setProfile(array('teacher_id'=>$teacher,'timezone'=>'UTC','status'=>'active','reason_code'=>'synthetic_fixture'));

$make=function(string$label,int$course,?int$studentId=null,?int$principalId=null)use($instrument,$teacher,$actor,$at,$suffix,$wpdb,$p):array{
    $requestResult=(new BookingRequestSubmissionService())->submitPublic(array('requested_instrument_id'=>$instrument,'selected_intro_course_id'=>$course,'full_name'=>'Synthetic I '.$label,'email'=>$label.'-'.$suffix.'@phase-2a2i.invalid','mobile'=>'+61400000000','country'=>'AU','city'=>'Brisbane','timezone'=>'UTC','communication_language'=>'en','whatsapp_same_as_mobile'=>true,'whatsapp_number'=>'','privacy_notice_accepted'=>true,'privacy_notice_version'=>'2026-09-05','requested_times'=>array(array('local_date'=>gmdate('Y-m-d',strtotime('+14 days')),'local_start_time'=>'09:00','timezone'=>'UTC'))),'dzn-2a2i-request-'.$label.'-'.$suffix);
    $request=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$p}booking_requests WHERE reference_code=%s",$requestResult['request_reference']));$coordination=new CoordinationCaseService();$case=$coordination->open($request,'admin_opened');$candidate=$coordination->addCandidate($case['case_id'],$teacher,'manual_search','manual_review');
    $assent=(new TeacherAvailabilityAssentService())->recordAdministratorAttestation(array('candidate_id'=>$candidate['candidate_id'],'candidate_version'=>$candidate['version'],'teacher_id'=>$teacher,'course_id'=>$course,'delivery_mode'=>'online','location_scope'=>'not_applicable','frequency_per_week'=>1,'expected_duration_minutes'=>30,'commencement_window_start'=>gmdate('Y-m-d H:i:s',strtotime('+14 days')),'commencement_window_end'=>gmdate('Y-m-d H:i:s',strtotime('+21 days')),'valid_until'=>gmdate('Y-m-d H:i:s',strtotime('+60 days')),'timezone'=>'UTC','conditions_code'=>'none','evidence_channel'=>'message_reference','evidence_at'=>gmdate('Y-m-d H:i:s',strtotime('-1 minute')),'attribution_basis'=>'direct_teacher_statement'));
    $issued=(new ProposalService())->issueInitial($candidate['candidate_id'],$assent['fingerprint'],'dzn-2a2i-proposal-'.$label.'-'.substr(hash('sha256',wp_generate_uuid4()),0,30));$version=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}proposal_versions WHERE id=%d",$issued['version_id']));$provisional=(new ProposalAcceptanceService())->record($issued['family_uid'],$issued['option_uid'],(int)$issued['version_number'],(string)$version->prospective_subject_ref,'message_reference',$at,'dzn-2a2i-provisional-'.$label.'-'.substr(hash('sha256',wp_generate_uuid4()),0,30));
    $identity=new StudentIdentityResolutionService();if($studentId===null){$identity->createAndResolve($request,array('display_name'=>'Synthetic I '.$label),'synthetic_fixture','synthetic_fixture',$at,$actor);$studentId=(int)$wpdb->get_var($wpdb->prepare("SELECT student_id FROM {$p}booking_requests WHERE id=%d",$request));$principalId=wp_insert_user(array('user_login'=>'dzn-i-'.$label.'-'.$suffix,'user_pass'=>wp_generate_password(32,true,true),'user_email'=>$label.'-'.$suffix.'@principal.phase-2a2i.invalid'));if(is_wp_error($principalId))throw new RuntimeException('Synthetic principal creation failed');$principalId=(int)$principalId;$authority=new StudentAcceptanceAuthorityService();$authority->classify($studentId,'adult','synthetic_fixture','synthetic_fixture',$at,$actor);$authority->establishPrincipal($studentId,$principalId,'synthetic_fixture','synthetic_fixture',$at,$actor);}else{$identity->resolveExisting($request,$studentId,'synthetic_fixture','synthetic_fixture',$at,$actor);}
    $provisionalUid=(string)$wpdb->get_var($wpdb->prepare("SELECT uid FROM {$p}proposal_acceptance_events WHERE id=%d",$provisional['event_id']));$accepted=(new FinalAcceptanceService())->accept($request,(int)$case['case_id'],$issued['family_uid'],$issued['option_uid'],(int)$issued['version_number'],$provisionalUid,$studentId,(int)$principalId,'affirmed','message_reference',$at,'dzn-2a2i-final-'.$label.'-'.substr(hash('sha256',wp_generate_uuid4()),0,30));
    return array('arrangement_id'=>(int)$accepted['arrangement_id'],'request_id'=>$request,'student_id'=>$studentId,'course_id'=>$course,'teacher_id'=>$teacher,'principal_id'=>(int)$principalId);
};

$fixture=array();$fixture['main']=$make('main',$course1);$fixture['return']=$make('return',$course1,$fixture['main']['student_id'],$fixture['main']['principal_id']);
$fixture['legacy']=$make('legacy',$course2);$now=gmdate('Y-m-d H:i:s');(new EnrolmentRepository())->insertLegacyBootstrap(array('uid'=>str_pad('ILEGACY',26,'0'),'reference_code'=>null,'student_id'=>$fixture['legacy']['student_id'],'teacher_id'=>$teacher,'course_id'=>$course2,'status'=>'active','record_model'=>'legacy_phase1','created_at'=>$now,'updated_at'=>$now,'created_by'=>$actor,'updated_by'=>$actor));
$fixture['inactive_student']=$make('inactive-student',$course2);$wpdb->update($p.'students',array('status'=>'inactive'),array('id'=>$fixture['inactive_student']['student_id']));
$fixture['privacy']=$make('privacy',$course2);
$fixture['atomic_enrolment']=$make('atomic-enrolment',$course2);$fixture['atomic_event']=$make('atomic-event',$course2);$fixture['atomic_command']=$make('atomic-command',$course2);
$fixture['race_a1']=$make('race-a1',$course2);$fixture['race_a2']=$make('race-a2',$course2,$fixture['race_a1']['student_id'],$fixture['race_a1']['principal_id']);
$fixture['race_b']=$make('race-b',$course2);
$fixture['unrelated_a']=$make('unrelated-a',$course1);$fixture['unrelated_b']=$make('unrelated-b',$course2);
$fixture['same_student_course1']=$make('same-student-c1',$course1);$fixture['same_student_course2']=$make('same-student-c2',$course2,$fixture['same_student_course1']['student_id'],$fixture['same_student_course1']['principal_id']);
$fixture['privacy_first']=$make('privacy-first',$course1);$fixture['conversion_first']=$make('conversion-first',$course2);
update_option('dzn_phase_2a2i_fixture',$fixture,false);echo"Phase 2A.2-I Schema 14 fixture prepared sources=".count($fixture)."\n";
