<?php
/** Disposable exact-lineage, authority, idempotency, immutability and privacy runtime. */
if(getenv('DZN_PHASE_2A2G_RUNTIME_TEST')!=='isolated'||!defined('WP_CLI')||!WP_CLI||!in_array(wp_get_environment_type(),array('local','development'),true)){fwrite(STDERR,"Phase 2A.2-G runtime refused.\n");exit(1);}
use Delnavazan\Platform\Core\Application\BookingRequestPrivacyService;
use Delnavazan\Platform\Core\Application\FinalAcceptanceService;
use Delnavazan\Platform\Core\Application\IdempotencyConflictException;
use Delnavazan\Platform\Core\Application\ProposalAcceptanceService;
use Delnavazan\Platform\Core\Application\ProposalService;
use Delnavazan\Platform\Core\Application\StudentAcceptanceAuthorityService;
use Delnavazan\Platform\Core\Application\StudentIdentityResolutionService;
global $wpdb;$p=$wpdb->prefix.'dzn_';
function dzn_2a2g_assert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$fixture=get_option('dzn_phase_2a2e_concurrency_fixture');dzn_2a2g_assert(is_array($fixture)&&isset($fixture['a']),'Proposal fixture unavailable');$target=$fixture['a'];$actor=get_current_user_id();$at=gmdate('Y-m-d H:i:s');
$provisional=(new ProposalAcceptanceService())->record($target['family_uid'],$target['option_uid'],(int)$target['version_number'],'booking_request:'.(int)$target['request_id'],'message_reference',$at,'dzn-2a2g-provisional-'.substr(hash('sha256',wp_generate_uuid4()),0,30));
$student=(new StudentIdentityResolutionService())->createAndResolve((int)$target['request_id'],array('display_name'=>'Synthetic Phase 2A.2-G Student'),'human_review','synthetic_fixture',$at,$actor);
$request=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}booking_requests WHERE id=%d",$target['request_id']));dzn_2a2g_assert($request&&(int)$request->student_id>0,'Student resolution failed');$studentId=(int)$request->student_id;
$authority=new StudentAcceptanceAuthorityService();$authority->classify($studentId,'adult','human_review','synthetic_fixture',$at,$actor);$authority->establishPrincipal($studentId,$actor,'human_review','synthetic_fixture',$at,$actor);
$key='dzn-2a2g-final-'.substr(hash('sha256',wp_generate_uuid4()),0,30);$service=new FinalAcceptanceService();$created=$service->accept((int)$target['request_id'],(int)$wpdb->get_var($wpdb->prepare("SELECT coordination_case_id FROM {$p}proposal_families WHERE uid=%s",$target['family_uid'])),$target['family_uid'],$target['option_uid'],(int)$target['version_number'],(string)$wpdb->get_var($wpdb->prepare("SELECT uid FROM {$p}proposal_acceptance_events WHERE id=%d",$provisional['event_id'])),$studentId,$actor,'affirmed','message_reference',$at,$key);$replay=$service->accept((int)$target['request_id'],(int)$wpdb->get_var($wpdb->prepare("SELECT coordination_case_id FROM {$p}proposal_families WHERE uid=%s",$target['family_uid'])),$target['family_uid'],$target['option_uid'],(int)$target['version_number'],(string)$wpdb->get_var($wpdb->prepare("SELECT uid FROM {$p}proposal_acceptance_events WHERE id=%d",$provisional['event_id'])),$studentId,$actor,'affirmed','message_reference',$at,$key);
dzn_2a2g_assert($created['created']&&!$created['idempotent']&&!$replay['created']&&$replay['idempotent']&&$created['arrangement_id']===$replay['arrangement_id'],'Exact final-acceptance replay failed');
$conflict=false;try{$service->accept((int)$target['request_id'],(int)$wpdb->get_var($wpdb->prepare("SELECT coordination_case_id FROM {$p}proposal_families WHERE uid=%s",$target['family_uid'])),$target['family_uid'],$target['option_uid'],(int)$target['version_number'],(string)$wpdb->get_var($wpdb->prepare("SELECT uid FROM {$p}proposal_acceptance_events WHERE id=%d",$provisional['event_id'])),$studentId,$actor,'affirmed','phone',$at,$key);}catch(IdempotencyConflictException){$conflict=true;}dzn_2a2g_assert($conflict,'Conflicting final-acceptance key was accepted');
$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}accepted_service_arrangements WHERE id=%d",$created['arrangement_id']),ARRAY_A);dzn_2a2g_assert($row&&$row['confirmation_value']==='affirmed'&&$row['authority_route']==='adult_self'&&$row['version_fingerprint']!==''&&$row['arrangement_fingerprint']!=='','Frozen arrangement evidence incomplete');foreach(array('first_name','last_name','display_name','email','mobile','whatsapp','phone','address','updated_at')as$field)dzn_2a2g_assert(!array_key_exists($field,$row),'Arrangement contains prohibited field '.$field);
$familyId=(int)$row['proposal_family_id'];$outcomes=$wpdb->get_results($wpdb->prepare("SELECT outcome FROM {$p}proposal_option_outcome_events WHERE proposal_family_id=%d",$familyId));dzn_2a2g_assert(count($outcomes)>0&&count(array_filter($outcomes,static fn($r)=>$r->outcome==='accepted'))===1&&count($outcomes)===(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}proposal_options WHERE proposal_family_id=%d",$familyId)),'Sibling outcomes are incomplete');
$versionsBefore=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}proposal_versions WHERE proposal_family_id=%d",$familyId));$issuanceRejected=false;try{(new ProposalService())->issueReplacement((int)$target['option_id'],(int)$target['version_number'],(string)$row['arrangement_fingerprint'],'dzn-2a2g-after-final-'.substr(hash('sha256',wp_generate_uuid4()),0,30),'operator_correction');}catch(Throwable){$issuanceRejected=true;}dzn_2a2g_assert($issuanceRejected&&(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}proposal_versions WHERE proposal_family_id=%d",$familyId))===$versionsBefore,'Proposal issuance remained open after final acceptance');
(new BookingRequestPrivacyService())->erase((int)$target['request_id'],$actor,'synthetic_runtime');$erased=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}booking_requests WHERE id=%d",$target['request_id']));dzn_2a2g_assert($erased&&$erased->privacy_erased_at!==null&&(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}accepted_service_arrangements WHERE id=%d",$created['arrangement_id']))===1,'Post-acceptance privacy erasure changed final evidence');$postEraseReplay=$service->accept((int)$target['request_id'],(int)$row['coordination_case_id'],$target['family_uid'],$target['option_uid'],(int)$target['version_number'],(string)$wpdb->get_var($wpdb->prepare("SELECT uid FROM {$p}proposal_acceptance_events WHERE id=%d",$provisional['event_id'])),$studentId,$actor,'affirmed','message_reference',$at,$key);dzn_2a2g_assert($postEraseReplay['idempotent'],'Post-erasure authoritative replay failed');
echo "Phase 2A.2-G isolated runtime passed\n";
