<?php
/** Phase 2A.2-M0 canonical Enrolment lifecycle authority source contract. */
$root=dirname(__DIR__);$plugin=file_get_contents($root.'/delnavazan-platform.php');$migration=file_get_contents($root.'/src/Core/Infrastructure/Migration/Migrator.php');$service=file_get_contents($root.'/src/Core/Application/CanonicalEnrolmentLifecycleService.php');$repository=file_get_contents($root.'/src/Core/Infrastructure/Repository/CanonicalEnrolmentLifecycleRepository.php');$validator=file_get_contents($root.'/src/Core/Application/CanonicalEnrolmentLifecycleValidator.php');$read=file_get_contents($root.'/src/Core/Application/CoreReadService.php');$screen=file_get_contents($root.'/src/Admin/Controller/ScreenController.php');
foreach(array("DZN_PLATFORM_SCHEMA_VERSION', '19'",'phase2a2m0-enrolment-lifecycle-authority-20260917.1','019_canonical_enrolment_lifecycle_authority','enrolment_lifecycle_commands','ENGINE=InnoDB')as$n)if(!str_contains($plugin.$migration,$n))throw new RuntimeException('Missing M0 identity/schema: '.$n);
foreach(array('dzn_manage_canonical_enrolment_lifecycle','canonical_enrolment_lifecycle_v1','command_key_digest','command_payload_digest','expected_from_state','result_state','result_event_id')as$n)if(!str_contains($migration.$service,$n))throw new RuntimeException('Missing lifecycle command contract: '.$n);
foreach(array("'activate'=>array('authorised','current')","'pause'=>array('current','paused')","'resume'=>array('paused','current')", "array('authorised','current','paused')")as$n)if(!str_contains($service,$n))throw new RuntimeException('Missing explicit lifecycle operation: '.$n);
foreach(array("\$from === 'authorised'","\$from === 'current'","\$from === 'paused'",'legalTransition')as$n)if(!str_contains($validator,$n))throw new RuntimeException('Missing lifecycle graph validation: '.$n);
foreach(array('SET TRANSACTION ISOLATION LEVEL READ COMMITTED','enrolment_identity_roots','FOR UPDATE','ORDER BY sequence_number,id','ORDER BY assignment_sequence,id')as$n)if(!str_contains($repository,$n))throw new RuntimeException('Missing lock order: '.$n);
foreach(array('applicable_term_exists','applicable_teacher_assignment_exists','subordinate_term_integrity_conflict','subordinate_assignment_integrity_conflict')as$n)if(!str_contains($service,$n))throw new RuntimeException('Missing closure guard: '.$n);
foreach(array('activate_canonical_enrolment','pause_canonical_enrolment','resume_canonical_enrolment','close_canonical_enrolment')as$n)if(!str_contains($screen,$n))throw new RuntimeException('Missing admin invocation: '.$n);
foreach(array("record_model ?? 'legacy_phase1'","CanonicalEnrolmentLifecycleValidator::valid(\$enrolment, \$history)",'data_integrity_conflict')as$n)if(!str_contains($read,$n))throw new RuntimeException('Protected canonical lifecycle read does not fail closed: '.$n);
if(!str_contains($screen,'Canonical lifecycle history failed integrity validation.'))throw new RuntimeException('Admin lifecycle integrity error path missing');
$ddl=substr($migration,strpos($migration,'CREATE TABLE {$p}enrolment_lifecycle_commands'),strpos($migration,'private static function private_digest')-strpos($migration,'CREATE TABLE {$p}enrolment_lifecycle_commands'));
foreach(array('raw_key','updated_at','evidence_reference varchar')as$n)if(str_contains($ddl,$n))throw new RuntimeException('Mutable/raw lifecycle command evidence: '.$n);
foreach(array('canonical_lesson','dzn_manage_canonical_lessons')as$n)if(str_contains($service.$repository.$migration,$n))throw new RuntimeException('Lesson authority introduced: '.$n);
echo "Phase 2A.2-M0 source contract passed\n";
