<?php
/** Focused conversion/readiness/privacy/idempotency/rollback runtime proof. */
if(getenv('DZN_PHASE_2A2I_RUNTIME_TEST')!=='isolated'||!defined('WP_CLI')||!WP_CLI||!in_array(wp_get_environment_type(),array('local','development'),true)){fwrite(STDERR,"Phase 2A.2-I isolated runtime refused.\n");exit(1);}
use Delnavazan\Platform\Core\Application\{BookingRequestPrivacyService,EnrolmentConversionIdempotency,EnrolmentConversionReadinessService,EnrolmentConversionService,IdempotencyConflictException};
global$wpdb;$p=$wpdb->prefix.'dzn_';$f=get_option('dzn_phase_2a2i_fixture');$actor=get_current_user_id();
function dzn_2a2i_assert(bool$ok,string$message):void{if(!$ok)throw new RuntimeException($message);}
function dzn_2a2i_key(string$label):string{return'dzn-2a2i-'.$label.'-'.substr(hash('sha256',$label.'-'.wp_generate_uuid4()),0,40);}
function dzn_2a2i_counts():array{global$wpdb;$prefix=$wpdb->prefix.'dzn_';return array((int)$wpdb->get_var("SELECT COUNT(*) FROM {$prefix}enrolments WHERE record_model='canonical_student_course_v1'"),(int)$wpdb->get_var("SELECT COUNT(*) FROM {$prefix}enrolment_lifecycle_events"),(int)$wpdb->get_var("SELECT COUNT(*) FROM {$prefix}enrolment_conversion_commands"));}
dzn_2a2i_assert(is_array($f),'Phase I fixture missing');$ready=new EnrolmentConversionReadinessService();$service=new EnrolmentConversionService();
$actorId=$actor;wp_set_current_user(0);$unauthorized=false;try{$ready->assess((int)$f['main']['arrangement_id']);}catch(RuntimeException$e){$unauthorized=$e->getMessage()==='Unauthorized';}finally{wp_set_current_user($actorId);}dzn_2a2i_assert($unauthorized,'Readiness capability was not enforced');
dzn_2a2i_assert($ready->assess((int)$f['main']['arrangement_id'])==='ready','Ready source not classified ready');dzn_2a2i_assert($ready->assess((int)$f['legacy']['arrangement_id'])==='legacy_review_required','Legacy target not blocked');dzn_2a2i_assert($ready->assess((int)$f['inactive_student']['arrangement_id'])==='student_not_current','Inactive Student not blocked');dzn_2a2i_assert($ready->assess(999999999)==='source_integrity_conflict','Missing source not classified');
$key=dzn_2a2i_key('main');$created=$service->convert((int)$f['main']['arrangement_id'],$key);$replay=$service->convert((int)$f['main']['arrangement_id'],$key);$otherKey=$service->convert((int)$f['main']['arrangement_id'],dzn_2a2i_key('main-other'));
dzn_2a2i_assert($created['created']&&!$created['idempotent']&&!$created['already_converted'],'Initial conversion response invalid');dzn_2a2i_assert(!$replay['created']&&$replay['idempotent']&&$replay['enrolment_id']===$created['enrolment_id'],'Same-command replay invalid');dzn_2a2i_assert($otherKey['already_converted']&&!$otherKey['created']&&!$otherKey['idempotent']&&$otherKey['enrolment_id']===$created['enrolment_id'],'Different-key already-converted result invalid');
$conflict=false;try{$service->convert((int)$f['return']['arrangement_id'],$key);}catch(IdempotencyConflictException){$conflict=true;}dzn_2a2i_assert($conflict,'Same key with different source did not conflict');
$enrolment=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}enrolments WHERE id=%d",$created['enrolment_id']));$event=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}enrolment_lifecycle_events WHERE enrolment_id=%d",$created['enrolment_id']));
dzn_2a2i_assert($enrolment&&$enrolment->record_model==='canonical_student_course_v1'&&$enrolment->status==='canonical'&&$enrolment->lifecycle_state==='authorised'&&(int)$enrolment->applicable_slot===1&&(int)$enrolment->student_id===(int)$f['main']['student_id']&&(int)$enrolment->course_id===(int)$f['main']['course_id']&&(int)$enrolment->teacher_id===(int)$f['main']['teacher_id']&&(int)$enrolment->accepted_service_arrangement_id===(int)$f['main']['arrangement_id'],'Canonical target facts invalid');
dzn_2a2i_assert($event&&(int)$event->event_sequence===1&&$event->from_state===null&&$event->to_state==='authorised'&&$event->reason_code==='accepted_service_arrangement_conversion'&&$event->evidence_channel==='platform_conversion_command','Initial lifecycle event invalid');dzn_2a2i_assert($ready->assess((int)$f['main']['arrangement_id'])==='already_converted','Converted readiness invalid');

$closedAt=gmdate('Y-m-d H:i:s',strtotime('+1 second'));dzn_2a2i_assert($wpdb->update($p.'enrolments',array('lifecycle_state'=>'closed','applicable_slot'=>null),array('id'=>$created['enrolment_id']))===1,'Closure fixture update failed');dzn_2a2i_assert($wpdb->insert($p.'enrolment_lifecycle_events',array('uid'=>str_pad('ICLOSE',26,'0'),'enrolment_id'=>$created['enrolment_id'],'event_sequence'=>2,'from_state'=>'authorised','to_state'=>'closed','lineage_meaning'=>null,'reason_code'=>'synthetic_closure','evidence_channel'=>'runtime_test','evidence_reference'=>'phase-i-closed','occurred_at'=>$closedAt,'recorded_at'=>$closedAt,'recorded_by'=>$actor,'created_at'=>$closedAt,'created_by'=>$actor))===1,'Closure event fixture failed');
dzn_2a2i_assert($ready->assess((int)$f['return']['arrangement_id'])==='ready','Return-after-closure not ready');$returned=$service->convert((int)$f['return']['arrangement_id'],dzn_2a2i_key('return'));$returnRow=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}enrolments WHERE id=%d",$returned['enrolment_id']));dzn_2a2i_assert($returnRow&&(int)$returnRow->predecessor_enrolment_id===$created['enrolment_id']&&$returnRow->lineage_meaning==='return_after_closure','Closure-evidence predecessor selection failed');

(new BookingRequestPrivacyService())->erase((int)$f['privacy']['request_id'],$actor,'synthetic_runtime');$erasedBefore=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}booking_requests WHERE id=%d",$f['privacy']['request_id']));dzn_2a2i_assert($erasedBefore&&$erasedBefore->privacy_erased_at!==null&&$ready->assess((int)$f['privacy']['arrangement_id'])==='ready','Retained final source became unready after erasure');$privacyResult=$service->convert((int)$f['privacy']['arrangement_id'],dzn_2a2i_key('privacy'));$erasedAfter=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}booking_requests WHERE id=%d",$f['privacy']['request_id']));$contact=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}booking_request_contact_snapshots WHERE booking_request_id=%d",$f['privacy']['request_id']));$privacyEnrolment=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}enrolments WHERE id=%d",$privacyResult['enrolment_id']),ARRAY_A);dzn_2a2i_assert($erasedAfter->privacy_erased_at===$erasedBefore->privacy_erased_at&&$contact&&$contact->email===null&&$contact->full_name===null,'Conversion reversed privacy erasure');foreach(array('email','phone','mobile','full_name','whatsapp','address')as$field)dzn_2a2i_assert(!array_key_exists($field,$privacyEnrolment),'Enrolment copied prohibited PII '.$field);

foreach(array('atomic_enrolment'=>'dzn_phase_2a2i_after_enrolment_insert','atomic_event'=>'dzn_phase_2a2i_after_lifecycle_event_insert','atomic_command'=>'dzn_phase_2a2i_after_command_insert')as$name=>$hook){$before=dzn_2a2i_counts();$failure=static function(){throw new RuntimeException('synthetic_failure');};add_action($hook,$failure);$failed=false;try{$service->convert((int)$f[$name]['arrangement_id'],dzn_2a2i_key($name));}catch(RuntimeException$e){$failed=$e->getMessage()==='synthetic_failure';}remove_action($hook,$failure);dzn_2a2i_assert($failed&&dzn_2a2i_counts()===$before,'Atomic rollback failed at '.$hook);}

$command=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}enrolment_conversion_commands WHERE enrolment_id=%d",$created['enrolment_id']),ARRAY_A);$wpdb->suppress_errors(true);$duplicateCommand=$wpdb->insert($p.'enrolment_conversion_commands',array_replace($command,array('id'=>null,'uid'=>str_pad('IDUPCMD',26,'0'))))===false;$duplicateSource=$wpdb->insert($p.'enrolment_conversion_commands',array_replace($command,array('id'=>null,'uid'=>str_pad('IDUPSRC',26,'0'),'command_key_digest'=>hash('sha256','other-command'))))===false;$duplicateEnrolment=$wpdb->insert($p.'enrolment_conversion_commands',array_replace($command,array('id'=>null,'uid'=>str_pad('IDUPENR',26,'0'),'command_key_digest'=>hash('sha256','third-command'),'accepted_service_arrangement_id'=>$f['atomic_enrolment']['arrangement_id'])))===false;$duplicateApplicable=$wpdb->insert($p.'enrolments',array('uid'=>str_pad('IDUPAPP',26,'0'),'student_id'=>$returnRow->student_id,'teacher_id'=>$returnRow->teacher_id,'course_id'=>$returnRow->course_id,'status'=>'canonical','record_model'=>'canonical_student_course_v1','accepted_service_arrangement_id'=>$f['atomic_event']['arrangement_id'],'lifecycle_state'=>'authorised','applicable_slot'=>1,'created_at'=>gmdate('Y-m-d H:i:s'),'updated_at'=>gmdate('Y-m-d H:i:s')))===false;$duplicateEvent=$wpdb->insert($p.'enrolment_lifecycle_events',array('uid'=>str_pad('IDUPEVT',26,'0'),'enrolment_id'=>$created['enrolment_id'],'event_sequence'=>2,'from_state'=>'authorised','to_state'=>'closed','reason_code'=>'duplicate','evidence_channel'=>'runtime_test','evidence_reference'=>'duplicate','occurred_at'=>$closedAt,'recorded_at'=>$closedAt,'recorded_by'=>$actor,'created_at'=>$closedAt,'created_by'=>$actor))===false;$wpdb->suppress_errors(false);dzn_2a2i_assert($duplicateCommand&&$duplicateSource&&$duplicateEnrolment&&$duplicateApplicable&&$duplicateEvent,'Database final arbitration incomplete');
echo"readiness=pass\nconversion=pass\nreplay_and_already_converted=pass\nidempotency_conflict=pass\nreturn_after_closure=pass\nprivacy_after_final=pass\natomicity=pass\ndatabase_uniqueness=pass\nPhase 2A.2-I isolated runtime passed\n";
