<?php
$root=dirname(__DIR__);$plugin=file_get_contents($root.'/delnavazan-platform.php');$migration=file_get_contents($root.'/src/Core/Infrastructure/Migration/Migrator.php');$assessment=file_get_contents($root.'/src/Core/Application/EnrolmentConversionAssessment.php');$readiness=file_get_contents($root.'/src/Core/Application/EnrolmentConversionReadinessService.php');$service=file_get_contents($root.'/src/Core/Application/EnrolmentConversionService.php');$idempotency=file_get_contents($root.'/src/Core/Application/EnrolmentConversionIdempotency.php');$repository=file_get_contents($root.'/src/Core/Infrastructure/Repository/EnrolmentConversionRepository.php');$enrolments=file_get_contents($root.'/src/Core/Infrastructure/Repository/EnrolmentRepository.php');$runtime=file_get_contents($root.'/tests/phase-2a2i-isolated-runtime.php');$fixture=file_get_contents($root.'/tests/phase-2a2i-schema14-fixture.php');
if(!str_contains($plugin,"DZN_PLATFORM_SCHEMA_VERSION', '15'")&&!str_contains($plugin,"DZN_PLATFORM_SCHEMA_VERSION', '16'")&&!str_contains($plugin,"DZN_PLATFORM_SCHEMA_VERSION', '17'")&&!str_contains($plugin,"DZN_PLATFORM_SCHEMA_VERSION', '18'")&&!str_contains($plugin,"DZN_PLATFORM_SCHEMA_VERSION', '19'"))throw new RuntimeException('Missing compatible Phase I+ schema identity');
if(!str_contains($plugin,'phase2a2i-enrolment-conversion-authority-20260914.1')&&!str_contains($plugin,'phase2a2j-teacher-assignment-foundation-20260915.1')&&!str_contains($plugin,'phase2a2k-canonical-term-foundation-20260916.1')&&!str_contains($plugin,'phase2a2l-canonical-term-authority-20260916.1')&&!str_contains($plugin,'phase2a2m0-enrolment-lifecycle-authority-20260917.1'))throw new RuntimeException('Missing compatible Phase I+ build identity');
foreach(array('015_enrolment_conversion_authority','enrolment_conversion_commands','enrolment_identity_roots','verify_enrolment_conversion_schema','dzn_convert_service_arrangements_to_enrolments')as$n)if(!str_contains($plugin.$migration,$n))throw new RuntimeException('Missing Phase I identity/schema/capability: '.$n);
foreach(array('ready','already_converted','legacy_review_required','canonical_conflict','source_integrity_conflict','student_not_current','course_not_current','source_not_final','data_integrity_conflict')as$n)if(!str_contains($assessment.$readiness,$n))throw new RuntimeException('Missing readiness classification: '.$n);
foreach(array('sourceGraphForUpdate','identityResolution','capacityClassification','materializeAndLockIdentityRoot','dzn_phase_2a2i_source_lineage_locked','dzn_phase_2a2i_identity_root_locked','dzn_phase_2a2i_conversion_locks_held','insertCanonical','insertLifecycleEvent','insertCommand','accepted_service_arrangement_conversion','platform_conversion_command','return_after_closure')as$n)if(!str_contains($service.$repository,$n))throw new RuntimeException('Missing conversion/lock invariant: '.$n);
foreach(array('booking_requests','coordination_cases','proposal_families','proposal_options','proposal_versions','proposal_acceptance_events','proposal_option_outcome_events','accepted_service_arrangements','enrolment_identity_roots','students','courses','teachers','enrolments','enrolment_lifecycle_events')as$n)if(!str_contains($repository,$n))throw new RuntimeException('Missing lock graph node: '.$n);
foreach(array('wp_salt(\'dzn_enrolment_conversion\')','strlen($raw) < 24','strlen($raw) > 255','convert_accepted_service_arrangement_to_enrolment_v1')as$n)if(!str_contains($idempotency,$n))throw new RuntimeException('Missing digest-only idempotency invariant: '.$n);
if(str_contains($service,'EnrolmentRepository()->insert')||str_contains($service,'insertLegacyBootstrap')||!str_contains($enrolments,'Generic Enrolment repository insertion is disabled'))throw new RuntimeException('Generic/canonical writer boundary reopened');
foreach(array('TeacherAssignmentService','teacher_assignment_commands','createTerm','createLesson','amelia_','wp_amelia','platform_payments','platform_outbox','register_rest_route')as$n)if(stripos($service.$readiness.$repository,$n)!==false)throw new RuntimeException('Phase I exceeded conversion boundary: '.$n);
$commandSchema=substr($migration,strpos($migration,'CREATE TABLE {$p}enrolment_conversion_commands'));$commandSchema=substr($commandSchema,0,strpos($commandSchema,'private static function private_digest'));foreach(array('updated_at','status','raw_key','email','phone','full_name')as$n)if(stripos($commandSchema,$n)!==false)throw new RuntimeException('Conversion evidence is mutable or contains prohibited data: '.$n);
foreach(array('dzn_phase_2a2i_after_enrolment_insert','dzn_phase_2a2i_after_lifecycle_event_insert','dzn_phase_2a2i_after_command_insert')as$n)if(!str_contains($service,$n))throw new RuntimeException('Atomic failure boundary missing: '.$n);
foreach(array('validExistingResult','validCanonicalAggregate','validInitialConversionEvidence','validLifecycle','identity_resolution_sequence','capacity_classification','Contaminated Enrolment conversion result')as$n)if(!str_contains($assessment.$service,$n))throw new RuntimeException('Missing reviewed integrity correction: '.$n);
foreach(array('lifecycle_progression_replay=pass','applicable_slot_validation=pass','main-current','main-paused','main-closed','replay_progression_contaminated')as$n)if(!str_contains($runtime.$fixture,$n))throw new RuntimeException('Missing final lifecycle correction coverage: '.$n);
echo"Phase 2A.2-I source contract passed\n";
