<?php
/** Separate WP-CLI acceptance worker with a deterministic post-lock barrier. */
if(getenv('DZN_PHASE_2A2E_RUNTIME_TEST')!=='isolated'||!defined('WP_CLI')||!WP_CLI||!in_array(wp_get_environment_type(),array('local','development'),true)){fwrite(STDERR,"Phase 2A.2-E worker refused.\n");exit(1);}
use Delnavazan\Platform\Core\Application\ProposalAcceptanceService;
use Delnavazan\Platform\Core\Application\ProposalService;
use Delnavazan\Platform\Core\Application\BookingRequestPrivacyService;
use Delnavazan\Platform\Core\Application\IdempotencyConflictException;
$state=get_option('dzn_phase_2a2e_race_state');if(!is_array($state))throw new RuntimeException('Acceptance race state unavailable');$name=(string)getenv('DZN_PHASE_2A2E_WORKER');$mode=(string)getenv('DZN_PHASE_2A2E_MODE');$action=(string)getenv('DZN_PHASE_2A2E_ACTION');if(!preg_match('/^(?:[abcdx][12])$/',$name)||!in_array($mode,array('a','b','c1','c2','d1','d2','x'),true)||!in_array($action,array('acceptance','issuance','erasure'),true))throw new RuntimeException('Worker identity unavailable');
$gate=(string)(getenv('DZN_PHASE_2A2E_GATE_DIR')?:'/gate');if(!is_dir($gate)||!is_writable($gate))throw new RuntimeException('Concurrency gate directory unavailable');file_put_contents($gate.'/'.$name.'.started',getmypid()."\n");
$hold=static function()use($gate,$name){file_put_contents($gate.'/'.$name.'.locked',microtime(true)."\n");for($i=0;$i<300&&!file_exists($gate.'/release');$i++)usleep(100000);if(!file_exists($gate.'/release'))throw new RuntimeException('Barrier release unavailable');};
if(($state['holder']??'')===$name){$hook=$action==='acceptance'?'dzn_phase_2a2e_acceptance_locks_held':($action==='issuance'?'dzn_phase_2a2e_proposal_locks_held':'dzn_phase_2a2e_privacy_locks_held');add_action($hook,$hold);}
try{if($action==='acceptance'){$payload=$state[$name]??null;if(!is_array($payload))throw new RuntimeException('Worker payload unavailable');$target=array_merge(array_intersect_key($state,array_flip(array('family_uid','option_uid','version_number','prospective_subject_ref'))),$payload);foreach(array('family_uid','option_uid','version_number','prospective_subject_ref','channel')as$field)if(empty($target[$field]))throw new RuntimeException('Worker target unavailable: '.$field);$out=(new ProposalAcceptanceService())->record($target['family_uid'],$target['option_uid'],(int)$target['version_number'],$target['prospective_subject_ref'],$target['channel'],$state['evidence_at'],$state['key']);echo 'outcome=success event='.(int)$out['event_id'].' idempotent='.($out['idempotent']?'1':'0')."\n";}elseif($action==='issuance'){$out=(new ProposalService())->issueReplacement((int)$state['option_id'],(int)$state['expected_version'],$state['replacement_fingerprint'],$state['issuance_key'],'material_facts_changed');echo 'outcome=issued version='.(int)$out['version_id']."\n";}else{(new BookingRequestPrivacyService())->erase((int)$state['request_id'],get_current_user_id(),'runtime_test');echo "outcome=erased\n";}}catch(IdempotencyConflictException){echo "outcome=conflict\n";}catch(Throwable $e){echo 'outcome=rejected class='.get_class($e)."\n";}
