<?php
/** Phase 2A.2-L canonical Term authority source contract. */
$root=dirname(__DIR__);$plugin=file_get_contents($root.'/delnavazan-platform.php');$migration=file_get_contents($root.'/src/Core/Infrastructure/Migration/Migrator.php');$service=file_get_contents($root.'/src/Core/Application/CanonicalTermAuthorityService.php');$repository=file_get_contents($root.'/src/Core/Infrastructure/Repository/CanonicalTermAuthorityRepository.php');$idempotency=file_get_contents($root.'/src/Core/Application/CanonicalTermIdempotency.php');$legacy=file_get_contents($root.'/src/Core/Application/TermService.php');$screen=file_get_contents($root.'/src/Admin/Controller/ScreenController.php');
if(!str_contains($plugin,"DZN_PLATFORM_SCHEMA_VERSION', '18'")&&!str_contains($plugin,"DZN_PLATFORM_SCHEMA_VERSION', '19'"))throw new RuntimeException('Missing compatible Phase L+ schema');
if(!str_contains($plugin,'phase2a2l-canonical-term-authority-20260916.1')&&!str_contains($plugin,'phase2a2m0-enrolment-lifecycle-authority-20260917.1'))throw new RuntimeException('Missing compatible Phase L+ build');
foreach(array('018_canonical_term_authority','install_canonical_term_authority','verify_canonical_term_authority_schema','term_commands')as$n)if(!str_contains($plugin.$migration,$n))throw new RuntimeException('Missing Phase L identity/schema: '.$n);
foreach(array('dzn_manage_canonical_terms','canonical_term_v1','command_key_digest','command_payload_digest','expected_term_id','expected_from_state','result_term_id','result_state','ENGINE=InnoDB')as$n)if(!str_contains($migration.$service,$n))throw new RuntimeException('Missing canonical Term authority: '.$n);
foreach(array('SET TRANSACTION ISOLATION LEVEL READ COMMITTED','FOR UPDATE','enrolment_sequence','enrolment_applicable','command_key_digest','duplicateConstraint')as$n)if(!str_contains($repository.$migration,$n))throw new RuntimeException('Missing concurrency arbitration: '.$n);
if(!str_contains($service,'$expectedLatestTermId,$expectedLatestState,\'authorised\''))throw new RuntimeException('Successor expected state is not persisted');
foreach(array('canonical_term_created','activate','close','cancel','stale_term_aggregate','stale_term_state','applicable_term_exists','data_integrity_conflict','observedPosition','aggregatePosition')as$n)if(!str_contains($service,$n))throw new RuntimeException('Missing command rule: '.$n);
foreach(array('canonical-term-command:','canonical-term-evidence:','hash_hmac','payloadDigest')as$n)if(!str_contains($idempotency,$n))throw new RuntimeException('Missing digest rule: '.$n);
foreach(array('raw_key','evidence_reference varchar','updated_at')as$n)if(str_contains(substr($migration,strpos($migration,'CREATE TABLE {$p}term_commands'),strpos($migration,'private static function private_digest')-strpos($migration,'CREATE TABLE {$p}term_commands')),$n))throw new RuntimeException('Mutable/raw command evidence: '.$n);
if(!str_contains($legacy,"record_model'] = 'legacy_phase1'")||!str_contains($screen,"'create_canonical_term'")||!str_contains($screen,"'activate_canonical_term'")||!str_contains($screen,"'close_canonical_term'")||!str_contains($screen,"'cancel_canonical_term'"))throw new RuntimeException('Legacy/admin command separation missing');
foreach(array('TeacherAssignment','LessonService','payment gating','register_rest_route','platform_outbox')as$n)if(str_contains($service.$repository,$n))throw new RuntimeException('Excluded authority introduced: '.$n);
$race=file_get_contents($root.'/tests/phase-2a2l-concurrency-runner.sh').file_get_contents($root.'/tests/phase-2a2l-concurrency-worker.php').file_get_contents($root.'/tests/phase-2a2l-concurrency-verify.php');foreach(array('same_key','different_key','competing_create','activate_activate','activate_cancel','close_cancel','close_create','cancel_create','unrelated','dzn_phase_2a2l_term_locks_held','stale_successor_absent','post_terminal_successor')as$n)if(!str_contains($race,$n))throw new RuntimeException('Missing concurrency scenario: '.$n);
echo "Phase 2A.2-L source contract passed\n";
