<?php
if (getenv('DZN_PHASE_2A2J_RUNTIME_TEST') !== 'concurrency' || !defined('WP_CLI') || !WP_CLI) { fwrite(STDERR, "Phase 2A.2-J verifier refused.\n"); exit(1); }
global $wpdb; $p = $wpdb->prefix . 'dzn_'; $state = get_option('dzn_phase_2a2j_race_state'); $enrolment = (int) $state['enrolment_id'];
$mode = (string) $state['mode'];
$assignments = (int) $wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}teacher_assignments WHERE enrolment_id=%d", $enrolment));
$current = $wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}teacher_assignments WHERE enrolment_id=%d AND applicable_slot=1", $enrolment));
$events = (int) $wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}teacher_assignment_lifecycle_events e INNER JOIN {$p}teacher_assignments a ON a.id=e.assignment_id WHERE a.enrolment_id=%d", $enrolment));
$commands = (int) $wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}teacher_assignment_commands WHERE enrolment_id=%d", $enrolment));
if ($mode === 'u1_unrelated_roots') { $roots = (int) $wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}enrolment_identity_roots WHERE (student_id=%d AND course_id=%d) OR (student_id=%d AND course_id=%d)", get_option('dzn_phase_2a2j_fixture')['sources'][0]['student_id'], get_option('dzn_phase_2a2j_fixture')['sources'][0]['course_id'], get_option('dzn_phase_2a2j_fixture')['sources'][1]['student_id'], get_option('dzn_phase_2a2j_fixture')['sources'][1]['course_id'])); if ($roots !== 2) throw new RuntimeException('Unrelated identity roots final state invalid'); echo "race={$mode} verifier=pass roots={$roots}\n"; exit; }
if ($mode === 'u2_shared_teacher') { $other = (int) $state['other_enrolment_id']; $otherAssignments = (int) $wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}teacher_assignments WHERE enrolment_id=%d", $other)); $otherCurrent = $wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}teacher_assignments WHERE enrolment_id=%d AND applicable_slot=1", $other)); if ($assignments !== 1 || $otherAssignments !== 1 || !$current || !$otherCurrent || (int) $current->teacher_id !== (int) $state['teacher_initial'] || (int) $otherCurrent->teacher_id !== (int) $state['teacher_initial']) throw new RuntimeException('Shared-Teacher unrelated Enrolments final state invalid'); echo "race={$mode} verifier=pass assignments=2 shared_teacher={$state['teacher_initial']}\n"; exit; }
if (in_array($mode, array('a_same_teacher_keys','e_initial_archive','f_initial_close'), true) && ($assignments !== 1 || !$current || $events !== 1 || $commands !== 1 || (int) $current->teacher_id !== (int) $state['teacher_initial'])) throw new RuntimeException('Initial race final state invalid');
if (in_array($mode, array('c_replace_end','d1_replace_diff','d2_replace_same','e_replace_archive','f_replace_close'), true) && ($assignments !== 2 || !$current || (int) $current->teacher_id !== (int) $state['teacher_one'] || $events !== 3 || $commands !== 2)) throw new RuntimeException('Replacement race final state invalid');
if (in_array($mode, array('e_archive_initial','f_close_initial'), true) && ($assignments !== 0 || $current || $events !== 0 || $commands !== 0)) throw new RuntimeException('Authoritative state first did not prevent initial Assignment');
if (in_array($mode, array('e_archive_replace','f_close_replace'), true) && ($assignments !== 1 || !$current || (int) $current->teacher_id !== (int) $state['teacher_initial'] || $events !== 1 || $commands !== 1)) throw new RuntimeException('Authoritative state first did not prevent replacement');
if (in_array($mode, array('e_initial_archive','e_replace_archive'), true)) { $teacher = $mode === 'e_initial_archive' ? (int) $state['teacher_initial'] : (int) $state['teacher_one']; $row = $wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}teachers WHERE id=%d", $teacher)); if (!$row || $row->status !== 'active' || $row->archived_at !== null) throw new RuntimeException('Assignment/archive race archived authoritative Teacher'); }
if (in_array($mode, array('e_archive_initial','e_archive_replace'), true)) { $teacher = $mode === 'e_archive_initial' ? (int) $state['teacher_initial'] : (int) $state['teacher_one']; $row = $wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}teachers WHERE id=%d", $teacher)); if (!$row || $row->status !== 'archived' || $row->archived_at === null) throw new RuntimeException('Archive-first ordering did not remain authoritative'); }
if (in_array($mode, array('f_initial_close','f_replace_close'), true)) { $row = $wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}enrolments WHERE id=%d", $enrolment)); if (!$row || $row->lifecycle_state !== 'closed' || $row->applicable_slot !== null) throw new RuntimeException('Assignment/closure ordering final state invalid'); }
if (in_array($mode, array('f_close_initial','f_close_replace'), true)) { $row = $wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}enrolments WHERE id=%d", $enrolment)); if (!$row || $row->lifecycle_state !== 'closed' || $row->applicable_slot !== null) throw new RuntimeException('Closure-first ordering final state invalid'); }
$method = new ReflectionMethod(\Delnavazan\Platform\Core\Application\TeacherAssignmentService::class, 'assignInitial'); if ($method->getNumberOfParameters() !== 2) throw new RuntimeException('Initial Teacher authority unexpectedly accepts a competing Teacher');
echo "race={$mode} verifier=pass assignments={$assignments} events={$events} commands={$commands} competing_initial_teacher=not_applicable_exact_source_only\n";
