<?php
namespace Delnavazan\Platform\Core\Infrastructure\Repository;

/** Phase 2A.1-D persistence only. It never stores raw idempotency or client signals. */
final class BookingRequestIntakeRepository {
    private string $prefix;
    public function __construct() { global $wpdb; $this->prefix = $wpdb->prefix . 'dzn_'; }
    public function reserveSubmissionKey(string $keyDigest, string $payloadDigest, string $expiresAt, string $now): object {
        return $this->privateWrite( function () use ( $keyDigest, $payloadDigest, $expiresAt, $now ) { global $wpdb;
            $sql = $wpdb->prepare( "INSERT INTO {$this->prefix}booking_request_submission_keys (key_digest,payload_digest,state,booking_request_id,response_reference,expires_at,created_at,updated_at) VALUES (%s,%s,'processing',NULL,NULL,%s,%s,%s) ON DUPLICATE KEY UPDATE key_digest=VALUES(key_digest)", $keyDigest, $payloadDigest, $expiresAt, $now, $now );
            $affected = $wpdb->query( $sql ); if ( $affected === false ) throw new \RuntimeException( 'Idempotency persistence failed' );
            $row = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$this->prefix}booking_request_submission_keys WHERE key_digest=%s FOR UPDATE", $keyDigest ) );
            if ( ! $row ) throw new \RuntimeException( 'Idempotency persistence failed' ); $row->created_new = $affected === 1; return $row;
        } );
    }
    public function completeSubmissionKey(int $id, int $requestId, string $reference, string $now): void { $this->privateWrite( function () use ( $id, $requestId, $reference, $now ) { global $wpdb;
        $changed = $wpdb->update( $this->prefix . 'booking_request_submission_keys', array( 'state' => 'completed', 'booking_request_id' => $requestId, 'response_reference' => $reference, 'updated_at' => $now ), array( 'id' => $id, 'state' => 'processing', 'booking_request_id' => null ) ); if ( $changed !== 1 ) throw new \RuntimeException( 'Idempotency completion failed' );
    } ); }
    public function restartExpiredSubmissionKey(int $id, string $payloadDigest, string $expiresAt, string $now): void { $this->privateWrite( function () use($id,$payloadDigest,$expiresAt,$now) { global $wpdb; $changed=$wpdb->query($wpdb->prepare("UPDATE {$this->prefix}booking_request_submission_keys SET payload_digest=%s,state='processing',booking_request_id=NULL,response_reference=NULL,expires_at=%s,updated_at=%s WHERE id=%d AND state='completed' AND expires_at<%s",$payloadDigest,$expiresAt,$now,$id,$now));if($changed!==1)throw new \RuntimeException('Idempotency operation unavailable'); } ); }
    public function matchingContactRequests(array $digests, int $excludeRequest): array { global $wpdb; $matches = array(); foreach ( array( 'email' => 'email_digest', 'mobile' => 'mobile_digest', 'whatsapp' => 'whatsapp_digest' ) as $type => $column ) { if ( empty( $digests[$column] ) ) continue; $sql = $wpdb->prepare( "SELECT booking_request_id FROM {$this->prefix}booking_request_contact_snapshots WHERE {$column}=%s AND booking_request_id<>%d", $digests[$column], $excludeRequest ); foreach ( $wpdb->get_col( $sql ) as $candidate ) $matches[] = array( 'candidate_id' => (int) $candidate, 'type' => $type, 'digest' => $digests[$column] ); } return $matches; }
    public function createDuplicateFlag(int $requestId, int $candidateId, string $type, string $digest, string $now): void { $this->privateWrite( function () use ( $requestId, $candidateId, $type, $digest, $now ) { global $wpdb; $sql = $wpdb->prepare( "INSERT INTO {$this->prefix}booking_request_duplicate_flags (booking_request_id,candidate_booking_request_id,signal_type,signal_digest,status,created_at,updated_at,version) VALUES (%d,%d,%s,%s,'open',%s,%s,1) ON DUPLICATE KEY UPDATE id=id", $requestId, $candidateId, $type, $digest, $now, $now ); if ( $wpdb->query( $sql ) === false ) throw new \RuntimeException( 'Duplicate review persistence failed' ); } ); }
    public function requestForUpdate(int $id): ?object { global $wpdb; return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$this->prefix}booking_requests WHERE id=%d FOR UPDATE", $id ) ); }
    public function eraseRequestPii(int $requestId, int $actorId, string $reason, string $integrityDigest, string $now): void { $this->privateWrite( function () use ( $requestId, $actorId, $reason, $integrityDigest, $now ) { global $wpdb;
        $changed = $wpdb->update( $this->prefix . 'booking_requests', array( 'reference_code' => null, 'lifecycle_status' => 'closed', 'resolution_state' => 'privacy_erased', 'privacy_erased_at' => $now, 'privacy_erased_by' => $actorId, 'privacy_erasure_reason' => $reason, 'updated_at' => $now, 'updated_by' => $actorId ), array( 'id' => $requestId, 'lifecycle_status' => 'submitted', 'resolution_state' => 'unresolved', 'privacy_erased_at' => null ) ); if ( $changed !== 1 ) throw new \InvalidArgumentException( 'Booking Request cannot be erased' );
        $clear = array( 'full_name'=>null,'email'=>null,'mobile'=>null,'country'=>null,'city'=>null,'timezone'=>null,'communication_language'=>null,'whatsapp_same_as_mobile'=>null,'whatsapp_number'=>null,'privacy_notice_version'=>null,'privacy_notice_accepted'=>null,'privacy_notice_accepted_at'=>null,'email_digest'=>null,'mobile_digest'=>null,'whatsapp_digest'=>null );
        if ( $wpdb->update( $this->prefix . 'booking_request_contact_snapshots', $clear, array( 'booking_request_id' => $requestId ) ) === false ) throw new \RuntimeException( 'Privacy erasure failed' );
        if ( $wpdb->query( $wpdb->prepare( "UPDATE {$this->prefix}booking_request_duplicate_flags SET status='closed_by_erasure',closed_at=%s,updated_at=%s WHERE (booking_request_id=%d OR candidate_booking_request_id=%d) AND status='open'", $now, $now, $requestId, $requestId ) ) === false ) throw new \RuntimeException( 'Privacy erasure failed' );
        if ( $wpdb->query( $wpdb->prepare( "UPDATE {$this->prefix}booking_request_submission_keys SET state='revoked',payload_digest=NULL,booking_request_id=NULL,response_reference=NULL,updated_at=%s WHERE booking_request_id=%d", $now, $requestId ) ) === false ) throw new \RuntimeException( 'Privacy erasure failed' );
        if ( $wpdb->insert( $this->prefix . 'booking_request_privacy_tombstones', array( 'booking_request_id'=>$requestId,'erased_at'=>$now,'erased_by'=>$actorId,'reason_code'=>$reason,'integrity_digest'=>$integrityDigest ) ) === false ) throw new \RuntimeException( 'Privacy erasure failed' );
    } ); }
    public function reviewDuplicateFlag(int $requestId, int $id, string $status, string $reason, int $actorId, string $now): void { $this->privateWrite( function () use ($requestId,$id,$status,$reason,$actorId,$now) { global $wpdb; $changed=$wpdb->query($wpdb->prepare("UPDATE {$this->prefix}booking_request_duplicate_flags SET status=%s,review_reason=%s,reviewed_at=%s,reviewed_by=%d,updated_at=%s,version=version+1 WHERE id=%d AND booking_request_id=%d AND status='open'",$status,$reason,$now,$actorId,$now,$id,$requestId)); if($changed!==1)throw new \InvalidArgumentException('Duplicate review is no longer available'); } ); }
    public function duplicateFlags(int $requestId): array { global $wpdb; return $wpdb->get_results($wpdb->prepare("SELECT id,candidate_booking_request_id,signal_type,status,review_reason,reviewed_at,reviewed_by,created_at FROM {$this->prefix}booking_request_duplicate_flags WHERE booking_request_id=%d ORDER BY id",$requestId)); }
    private function privateWrite(callable $operation): mixed { global $wpdb; $previous=$wpdb->suppress_errors(true); try{return $operation();}finally{$wpdb->suppress_errors($previous);} }
}
