<?php
namespace Delnavazan\Platform\Core\Infrastructure\Repository;

/** Persistence boundary for the 2A.0 identity and invitation aggregate. */
final class PrincipalInvitationRepository {
    private string $prefix;
    public function __construct(){ global $wpdb; $this->prefix=$wpdb->prefix.'dzn_'; }
    public function begin():void{global $wpdb;if($wpdb->query('START TRANSACTION')===false)throw new \RuntimeException('Transaction start failed');}
    public function commit():void{global $wpdb;if($wpdb->query('COMMIT')===false)throw new \RuntimeException('Transaction commit failed');}
    public function rollback():void{global $wpdb;$wpdb->query('ROLLBACK');}
    public function teacherForUpdate(int $id):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}teachers WHERE id=%d FOR UPDATE",$id));}
    public function invitationForTeacher(int $teacherId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}teacher_invitations WHERE teacher_id=%d FOR UPDATE",$teacherId));}
    public function invitationForIdForUpdate(int $id):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}teacher_invitations WHERE id=%d FOR UPDATE",$id));}
    public function generationForUpdate(int $id):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}teacher_invitation_generations WHERE id=%d FOR UPDATE",$id));}
    public function generationForSecretForUpdate(string $secretDigest):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT g.*,i.id AS parent_invitation_id,i.status AS parent_status,i.current_generation_number,i.recipient_digest AS parent_recipient_digest FROM {$this->prefix}teacher_invitation_generations g INNER JOIN {$this->prefix}teacher_invitations i ON i.id=g.invitation_id WHERE g.secret_digest=%s FOR UPDATE",$secretDigest));}
    public function deliveryOutboxForGenerationForUpdate(int $generationId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}platform_outbox WHERE generation_id=%d AND event_type='teacher_invitation.delivery_requested' ORDER BY id DESC LIMIT 1 FOR UPDATE",$generationId));}
    public function attemptForCommand(string $key):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}account_claim_attempts WHERE command_key=%s FOR UPDATE",$key));}
    /** CAS transition prevents a callback from replacing a durable claim principal. */
    public function transitionProvisioningAttempt(int $id,string $state,?int $wordpressUserId,?string $reason,string $now):int{global $wpdb;$principal=$wordpressUserId===null?'NULL':(string)(int)$wordpressUserId;$sql=$wpdb->prepare("UPDATE {$this->prefix}account_claim_attempts SET wordpress_user_id={$principal},state=%s,recovery_reason=%s,updated_at=%s WHERE id=%d AND state='provisioning_pending' AND wordpress_user_id IS NULL",$state,$reason,$now,$id);$n=$wpdb->query($sql);if($n===false)throw new \RuntimeException('Provisioning result persistence failed: '.$wpdb->last_error);return$n;}
    public function eventExists(string $key):bool{global $wpdb;return(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$this->prefix}platform_audit_events WHERE idempotency_key=%s",$key));}
    public function insert(string $table,array $data):int{global $wpdb;if($wpdb->insert($this->prefix.$table,$data)===false)throw new \RuntimeException('Persistence failed: '.$wpdb->last_error);return(int)$wpdb->insert_id;}
    public function update(string $table,array $data,array $where):int{global $wpdb;$n=$wpdb->update($this->prefix.$table,$data,$where);if($n===false)throw new \RuntimeException('Persistence failed: '.$wpdb->last_error);return$n;}
    public function supersedeUnclaimedGenerations(int $invitationId,string $now):int{return $this->transitionUnclaimedGenerations($invitationId,'superseded','superseded_at',$now);}
    public function revokeUnclaimedGenerations(int $invitationId,string $now):int{return $this->transitionUnclaimedGenerations($invitationId,'revoked','revoked_at',$now);}
    public function cancelPendingDeliveryOutboxes(int $invitationId,string $now):int{global $wpdb;$n=$wpdb->query($wpdb->prepare("UPDATE {$this->prefix}platform_outbox SET status='cancelled',processed_at=%s WHERE invitation_id=%d AND status IN ('pending','prepared')",$now,$invitationId));if($n===false)throw new \RuntimeException('Delivery outbox cancellation failed: '.$wpdb->last_error);return$n;}
    public function activateQueuedGeneration(int $generationId,string $digest,string $now):int{global $wpdb;$n=$wpdb->query($wpdb->prepare("UPDATE {$this->prefix}teacher_invitation_generations SET secret_digest=%s,status='active',delivery_prepared_at=%s,delivery_attempt_count=delivery_attempt_count+1 WHERE id=%d AND status='queued_for_delivery' AND secret_digest IS NULL",$digest,$now,$generationId));if($n===false)throw new \RuntimeException('Invitation delivery preparation failed: '.$wpdb->last_error);return$n;}
    public function markDeliveryPrepared(int $outboxId,string $now):int{global $wpdb;$n=$wpdb->query($wpdb->prepare("UPDATE {$this->prefix}platform_outbox SET status='prepared',leased_at=%s,attempt_count=attempt_count+1 WHERE id=%d AND status='pending'",$now,$outboxId));if($n===false)throw new \RuntimeException('Delivery outbox preparation failed: '.$wpdb->last_error);return$n;}
    public function anonymizeTerminalRecipientSnapshots(int $invitationId):int{global $wpdb;$n=$wpdb->query($wpdb->prepare("UPDATE {$this->prefix}teacher_invitation_generations SET recipient_snapshot=NULL,recipient_digest=NULL WHERE invitation_id=%d AND status IN ('claimed','revoked','superseded')",$invitationId));if($n===false)throw new \RuntimeException('Invitation recipient cleanup failed: '.$wpdb->last_error);return$n;}
    public function anonymizeInvitationRecipientDigest(int $invitationId):int{return $this->update('teacher_invitations',['recipient_digest'=>hash('sha256','dzn-anonymized-invitation:'.$invitationId)],['id'=>$invitationId]);}
    public function hasNonterminalGeneration(int $invitationId):bool{global $wpdb;return(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$this->prefix}teacher_invitation_generations WHERE invitation_id=%d AND status NOT IN ('claimed','revoked','superseded') LIMIT 1 FOR UPDATE",$invitationId));}
    public function onboardingForTeacher(int $teacherId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}teacher_onboarding_states WHERE teacher_id=%d FOR UPDATE",$teacherId));}
    public function activeTeacherLinkForUser(int $userId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}teacher_principal_links WHERE wordpress_user_id=%d AND status='active' FOR UPDATE",$userId));}
    public function activeTeacherLinkForTeacher(int $teacherId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}teacher_principal_links WHERE teacher_id=%d AND status='active' FOR UPDATE",$teacherId));}
    public function activeStudentLinkForUser(int $userId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}student_principal_links WHERE wordpress_user_id=%d AND status='active'",$userId));}
    public function audit(string $aggregate,int $id,string $event,?int $actor,string $key,?string $detail=null):void{$this->insert('platform_audit_events',['aggregate_type'=>$aggregate,'aggregate_id'=>$id,'event_type'=>$event,'actor_type'=>$actor?'user':'system','actor_id'=>$actor,'safe_detail'=>$detail,'idempotency_key'=>$key,'occurred_at'=>current_time('mysql',true)]);}
    public function outbox(int $invitationId,int $generationId,string $event,string $key):void{$this->insert('platform_outbox',['aggregate_type'=>'teacher_invitation','aggregate_id'=>$invitationId,'event_type'=>$event,'invitation_id'=>$invitationId,'generation_id'=>$generationId,'idempotency_key'=>$key,'status'=>'pending','available_at'=>current_time('mysql',true),'created_at'=>current_time('mysql',true)]);}
    public function hasActiveTeacherAuthority(int $userId,int $teacherId):bool{global $wpdb;return(bool)$wpdb->get_var($wpdb->prepare("SELECT l.id FROM {$this->prefix}teacher_principal_links l INNER JOIN {$this->prefix}teacher_onboarding_states o ON o.teacher_id=l.teacher_id INNER JOIN {$this->prefix}teachers t ON t.id=l.teacher_id WHERE l.wordpress_user_id=%d AND l.teacher_id=%d AND l.status='active' AND o.state='active' AND o.readiness_state='ready' AND t.status='active' AND t.archived_at IS NULL LIMIT 1",$userId,$teacherId));}
    public function adminRows():array{global $wpdb;return $wpdb->get_results("SELECT t.id teacher_id,t.display_name,t.status teacher_status,o.state onboarding_state,l.wordpress_user_id,l.status principal_status,i.current_generation_number,i.status invitation_status FROM {$this->prefix}teachers t LEFT JOIN {$this->prefix}teacher_onboarding_states o ON o.teacher_id=t.id LEFT JOIN {$this->prefix}teacher_principal_links l ON l.teacher_id=t.id AND l.status='active' LEFT JOIN {$this->prefix}teacher_invitations i ON i.teacher_id=t.id ORDER BY t.id DESC LIMIT 100");}
    private function transitionUnclaimedGenerations(int $invitationId,string $status,string $atColumn,string $now):int{global $wpdb;$n=$wpdb->query($wpdb->prepare("UPDATE {$this->prefix}teacher_invitation_generations SET status=%s,{$atColumn}=%s WHERE invitation_id=%d AND status IN ('queued_for_delivery','active')",$status,$now,$invitationId));if($n===false)throw new \RuntimeException('Invitation generation transition failed: '.$wpdb->last_error);return$n;}
}
