<?php
namespace Delnavazan\Platform\Core\Infrastructure\Repository;
final class ProposalRepository {
    private string $p; public function __construct(){global $wpdb;$this->p=$wpdb->prefix.'dzn_';}
    public function claim(string $key,string $payload,string $now):object{global $wpdb;$wpdb->query($wpdb->prepare("INSERT INTO {$this->p}proposal_issuance_keys(key_digest,payload_digest,state,created_at,updated_at) VALUES(%s,%s,'processing',%s,%s) ON DUPLICATE KEY UPDATE key_digest=VALUES(key_digest)",$key,$payload,$now,$now));$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->p}proposal_issuance_keys WHERE key_digest=%s FOR UPDATE",$key));if(!$row)throw new \RuntimeException('Proposal idempotency persistence failed');return$row;}
    public function family(int $id):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->p}proposal_families WHERE id=%d FOR UPDATE",$id));}
    public function familyByObjective(int $case,string $fingerprint):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->p}proposal_families WHERE coordination_case_id=%d AND objective_fingerprint=%s FOR UPDATE",$case,$fingerprint));}
    public function createFamily(array $d):int{global $wpdb;if($wpdb->insert($this->p.'proposal_families',$d)===false)throw new \RuntimeException('Proposal Family persistence failed');return(int)$wpdb->insert_id;}
    public function option(int $family,int $teacher):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->p}proposal_options WHERE family_id=%d AND teacher_id=%d FOR UPDATE",$family,$teacher));}
    public function createOption(array $d):int{global $wpdb;if($wpdb->insert($this->p.'proposal_options',$d)===false)throw new \RuntimeException('Proposal Option persistence failed');return(int)$wpdb->insert_id;}
    public function currentVersion(int $option):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->p}proposal_versions WHERE option_id=%d AND state='issued' ORDER BY version_number DESC LIMIT 1 FOR UPDATE",$option));}
    public function nextVersion(int $option):int{global $wpdb;return 1+(int)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(MAX(version_number),0) FROM {$this->p}proposal_versions WHERE option_id=%d FOR UPDATE",$option));}
    public function createVersion(array $d):int{global $wpdb;if($wpdb->insert($this->p.'proposal_versions',$d)===false)throw new \RuntimeException('Proposal Version persistence failed');return(int)$wpdb->insert_id;}
    public function supersede(object $row,int $successor):void{global $wpdb;if($wpdb->update($this->p.'proposal_versions',array('state'=>'superseded','superseded_by_version_id'=>$successor),array('id'=>$row->id,'state'=>'issued'))!==1)throw new \RuntimeException('Proposal Version changed concurrently');}
    public function complete(object $key,int $family,int $option,int $version,string $ref,string $now):void{global $wpdb;if($wpdb->update($this->p.'proposal_issuance_keys',array('state'=>'completed','family_id'=>$family,'option_id'=>$option,'proposal_version_id'=>$version,'response_reference'=>$ref,'updated_at'=>$now),array('id'=>$key->id,'state'=>'processing'))!==1)throw new \RuntimeException('Proposal idempotency changed concurrently');}
    public function version(int $id):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->p}proposal_versions WHERE id=%d",$id));}
    public function audit(int $version,int $actor,string $detail,string $key,string $now):void{global $wpdb;if($wpdb->insert($this->p.'platform_audit_events',array('aggregate_type'=>'proposal_version','aggregate_id'=>$version,'event_type'=>'proposal_version.issued','actor_type'=>'user','actor_id'=>$actor,'reason_code'=>'issued','safe_detail'=>$detail,'idempotency_key'=>$key,'occurred_at'=>$now))===false)throw new \RuntimeException('Proposal audit persistence failed');}
    public function invalidateForPrivacyErasure(int $request,int $actor,string $now,callable $key):void{global $wpdb;$rows=$wpdb->get_results($wpdb->prepare("SELECT v.* FROM {$this->p}proposal_versions v INNER JOIN {$this->p}proposal_families f ON f.id=v.family_id WHERE f.booking_request_id=%d AND v.state='issued' ORDER BY v.id FOR UPDATE",$request));foreach($rows as$row){if($wpdb->update($this->p.'proposal_versions',array('state'=>'invalidated'),array('id'=>$row->id,'state'=>'issued'))===1)$this->audit((int)$row->id,$actor,'privacy_erased',$key('proposal:'.$row->id),$now);}}
}
