<?php
namespace Delnavazan\Platform\Core\Infrastructure\Repository;

/** Persistence for Phase 2A.2-F. Evidence references are opaque identifiers, never contact data or documents. */
final class StudentIdentityAuthorityRepository {
    private string $prefix;
    public function __construct(){global $wpdb;$this->prefix=$wpdb->prefix.'dzn_';}
    public function requestForUpdate(int $id):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}booking_requests WHERE id=%d FOR UPDATE",$id));}
    public function studentForUpdate(int $id):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}students WHERE id=%d FOR UPDATE",$id));}
    public function wordpressUserForUpdate(int $id):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT ID FROM {$wpdb->users} WHERE ID=%d FOR UPDATE",$id));}
    public function currentResolutionForUpdate(int $requestId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT e.* FROM {$this->prefix}booking_requests r LEFT JOIN {$this->prefix}booking_request_identity_resolution_events e ON e.id=r.current_identity_resolution_id WHERE r.id=%d FOR UPDATE",$requestId));}
    public function insertResolution(array $data):int{global $wpdb;if(false===$wpdb->insert($this->prefix.'booking_request_identity_resolution_events',$data))throw new \RuntimeException('Identity resolution persistence failed');return(int)$wpdb->insert_id;}
    public function setResolutionProjection(int $requestId,int $eventId,?int $studentId,int $actor,string $now):void{global $wpdb;$sql=$studentId===null?$wpdb->prepare("UPDATE {$this->prefix}booking_requests SET current_identity_resolution_id=%d,student_id=NULL,updated_at=%s,updated_by=%d WHERE id=%d AND lifecycle_status='submitted' AND resolution_state='unresolved' AND privacy_erased_at IS NULL",$eventId,$now,$actor,$requestId):$wpdb->prepare("UPDATE {$this->prefix}booking_requests SET current_identity_resolution_id=%d,student_id=%d,updated_at=%s,updated_by=%d WHERE id=%d AND lifecycle_status='submitted' AND resolution_state='unresolved' AND privacy_erased_at IS NULL",$eventId,$studentId,$now,$actor,$requestId);$changed=$wpdb->query($sql);if($changed!==1)throw new \InvalidArgumentException('Booking Request identity is no longer resolvable');}
    public function nextResolutionSequence(int $requestId):int{global $wpdb;return 1+(int)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(MAX(resolution_sequence),0) FROM {$this->prefix}booking_request_identity_resolution_events WHERE booking_request_id=%d",$requestId));}
    public function createStudent(array $data):int{global $wpdb;if(false===$wpdb->insert($this->prefix.'students',$data))throw new \RuntimeException('Student creation failed');return(int)$wpdb->insert_id;}
    public function currentCapacityForUpdate(int $studentId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT c.* FROM {$this->prefix}students s LEFT JOIN {$this->prefix}student_acceptance_capacity_classifications c ON c.id=s.current_acceptance_capacity_classification_id WHERE s.id=%d FOR UPDATE",$studentId));}
    public function insertCapacity(array $data):int{global $wpdb;if(false===$wpdb->insert($this->prefix.'student_acceptance_capacity_classifications',$data))throw new \RuntimeException('Capacity classification persistence failed');return(int)$wpdb->insert_id;}
    public function setCapacityProjection(int $studentId,int $classificationId,int $actor,string $now):void{global $wpdb;$changed=$wpdb->query($wpdb->prepare("UPDATE {$this->prefix}students SET current_acceptance_capacity_classification_id=%d,updated_at=%s,updated_by=%d WHERE id=%d AND archived_at IS NULL AND status='active'",$classificationId,$now,$actor,$studentId));if($changed!==1)throw new \InvalidArgumentException('Student is not active');}
    public function activePrincipalForStudentForUpdate(int $studentId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}student_principal_links WHERE student_id=%d AND active_slot=1 FOR UPDATE",$studentId));}
    public function nextPrincipalSequence(int $studentId):int{global $wpdb;return 1+(int)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(MAX(link_sequence),0) FROM {$this->prefix}student_principal_links WHERE student_id=%d",$studentId));}
    public function activePrincipalForUserForUpdate(int $userId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}student_principal_links WHERE wordpress_user_id=%d AND active_slot=1 FOR UPDATE",$userId));}
    public function insertPrincipal(array $data):int{global $wpdb;if(false===$wpdb->insert($this->prefix.'student_principal_links',$data))throw new \RuntimeException('Student principal persistence failed');return(int)$wpdb->insert_id;}
    public function revokePrincipal(int $id,int $version,int $actor,string $reason,string $now):void{global $wpdb;$changed=$wpdb->query($wpdb->prepare("UPDATE {$this->prefix}student_principal_links SET status='revoked',active_slot=NULL,version=version+1,revoked_at=%s,revoked_by=%d,reason_code=%s,updated_at=%s,updated_by=%d WHERE id=%d AND status='active' AND active_slot=1 AND version=%d",$now,$actor,$reason,$now,$actor,$id,$version));if($changed!==1)throw new \InvalidArgumentException('Student principal link is no longer current');}
    public function activeGrantForUpdate(int $studentId,int $userId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}student_acceptance_authority_grants WHERE student_id=%d AND acting_wordpress_user_id=%d AND authority_scope='service_acceptance' AND active_slot=1 FOR UPDATE",$studentId,$userId));}
    public function activeGuardianForUserForUpdate(int $userId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}student_acceptance_authority_grants WHERE acting_wordpress_user_id=%d AND authority_type='guardian_representative' AND authority_scope='service_acceptance' AND state='active' AND active_slot=1 FOR UPDATE",$userId));}
    public function grantForUpdate(int $id):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}student_acceptance_authority_grants WHERE id=%d FOR UPDATE",$id));}
    public function insertGrant(array $data):int{global $wpdb;if(false===$wpdb->insert($this->prefix.'student_acceptance_authority_grants',$data))throw new \RuntimeException('Acceptance authority persistence failed');return(int)$wpdb->insert_id;}
    public function revokeGrant(int $id,int $version,int $actor,string $reason,string $now):void{global $wpdb;$changed=$wpdb->query($wpdb->prepare("UPDATE {$this->prefix}student_acceptance_authority_grants SET state='revoked',active_slot=NULL,version=version+1,revoked_at=%s,revoked_by=%d,reason_code=%s,updated_at=%s,updated_by=%d WHERE id=%d AND state='active' AND active_slot=1 AND version=%d",$now,$actor,$reason,$now,$actor,$id,$version));if($changed!==1)throw new \InvalidArgumentException('Acceptance authority grant is no longer current');}
    public function markGrantSuperseded(int $id,int $version,int $actor,string $reason,string $now):void{global $wpdb;$changed=$wpdb->query($wpdb->prepare("UPDATE {$this->prefix}student_acceptance_authority_grants SET state='superseded',active_slot=NULL,version=version+1,superseded_at=%s,reason_code=%s,updated_at=%s,updated_by=%d WHERE id=%d AND state='active' AND active_slot=1 AND version=%d",$now,$reason,$now,$actor,$id,$version));if($changed!==1)throw new \InvalidArgumentException('Acceptance authority grant is no longer current');}
    public function setSupersedingGrant(int $id,int $nextId):void{global $wpdb;if($wpdb->update($this->prefix.'student_acceptance_authority_grants',array('superseded_by_grant_id'=>$nextId),array('id'=>$id,'state'=>'superseded'))!==1)throw new \RuntimeException('Acceptance authority supersession persistence failed');}
    public function privacyResolutionConsistent(object $request):bool{if($request->student_id===null&&$request->current_identity_resolution_id===null)return true;if($request->current_identity_resolution_id===null)return false;global $wpdb;if($request->student_id===null)return(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$this->prefix}booking_request_identity_resolution_events WHERE id=%d AND booking_request_id=%d AND student_id IS NULL AND outcome IN ('unresolved','ambiguous','rejected')",$request->current_identity_resolution_id,$request->id));return(bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$this->prefix}booking_request_identity_resolution_events WHERE id=%d AND booking_request_id=%d AND student_id=%d AND outcome='resolved'",$request->current_identity_resolution_id,$request->id,$request->student_id));}
    public function eligibilityRows(int $requestId,int $userId,string $now):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT r.id,r.student_id,r.lifecycle_status,r.resolution_state,r.privacy_erased_at,r.current_identity_resolution_id,e.outcome,e.student_id AS event_student_id,s.status AS student_status,s.archived_at,s.current_acceptance_capacity_classification_id,c.classification,p.id AS principal_id,g.id AS guardian_grant_id FROM {$this->prefix}booking_requests r LEFT JOIN {$this->prefix}booking_request_identity_resolution_events e ON e.id=r.current_identity_resolution_id LEFT JOIN {$this->prefix}students s ON s.id=r.student_id LEFT JOIN {$this->prefix}student_acceptance_capacity_classifications c ON c.id=s.current_acceptance_capacity_classification_id LEFT JOIN {$this->prefix}student_principal_links p ON p.student_id=s.id AND p.wordpress_user_id=%d AND p.status='active' AND p.active_slot=1 LEFT JOIN {$this->prefix}student_acceptance_authority_grants g ON g.student_id=s.id AND g.acting_wordpress_user_id=%d AND g.authority_type='guardian_representative' AND g.authority_scope='service_acceptance' AND g.state='active' AND g.active_slot=1 AND g.effective_from<=%s AND (g.effective_until IS NULL OR g.effective_until>%s) WHERE r.id=%d",$userId,$userId,$now,$now,$requestId));}
    public function rows(string $table,int $limit=100):array{global $wpdb;$allowed=array('booking_request_identity_resolution_events','student_acceptance_capacity_classifications','student_principal_links','student_acceptance_authority_grants');if(!in_array($table,$allowed,true))return array();return $wpdb->get_results("SELECT * FROM {$this->prefix}{$table} ORDER BY id DESC LIMIT ".max(1,min($limit,100)));}
}
