<?php
namespace Delnavazan\Platform\Core\Infrastructure\Repository;

/** Fixed-table persistence for the Phase 2A.1-A authoritative facts. */
final class TeachingEligibilityRepository {
    private string $prefix;
    public function __construct(){global $wpdb;$this->prefix=$wpdb->prefix.'dzn_';}
    public function begin():void{global $wpdb;if($wpdb->query('START TRANSACTION')===false)throw new \RuntimeException('Transaction start failed');}
    public function commit():void{global $wpdb;if($wpdb->query('COMMIT')===false)throw new \RuntimeException('Transaction commit failed');}
    public function rollback():void{global $wpdb;$wpdb->query('ROLLBACK');}
    public function instrumentForUpdate(int $id):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}instruments WHERE id=%d FOR UPDATE",$id));}
    public function courseForUpdate(int $id):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}courses WHERE id=%d FOR UPDATE",$id));}
    public function teacherForUpdate(int $id):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}teachers WHERE id=%d FOR UPDATE",$id));}
    public function onboardingForUpdate(int $teacherId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}teacher_onboarding_states WHERE teacher_id=%d FOR UPDATE",$teacherId));}
    public function eligibilityForUpdate(int $teacherId,int $courseId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}teacher_course_eligibilities WHERE teacher_id=%d AND course_id=%d FOR UPDATE",$teacherId,$courseId));}
    public function defaultForUpdate(int $instrumentId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}instrument_intro_course_defaults WHERE instrument_id=%d FOR UPDATE",$instrumentId));}
    public function acceptingForUpdate(int $teacherId):?object{global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->prefix}teacher_accepting_states WHERE teacher_id=%d FOR UPDATE",$teacherId));}
    public function saveEligibility(int $teacherId,int $courseId,string $status,?string $from,?string $until,?string $reason,string $now,?int $actor):int{global $wpdb;$current=$this->eligibilityForUpdate($teacherId,$courseId);if($current){$n=$wpdb->update($this->prefix.'teacher_course_eligibilities',['status'=>$status,'effective_from'=>$from,'effective_until'=>$until,'reason_code'=>$reason,'version'=>(int)$current->version+1,'updated_at'=>$now,'updated_by'=>$actor],['id'=>$current->id,'version'=>$current->version]);if($n!==1)throw new \RuntimeException('Eligibility changed concurrently');return(int)$current->id;}$ok=$wpdb->insert($this->prefix.'teacher_course_eligibilities',['teacher_id'=>$teacherId,'course_id'=>$courseId,'status'=>$status,'effective_from'=>$from,'effective_until'=>$until,'version'=>1,'reason_code'=>$reason,'created_at'=>$now,'updated_at'=>$now,'created_by'=>$actor,'updated_by'=>$actor]);if($ok===false)throw new \RuntimeException('Eligibility persistence failed: '.$wpdb->last_error);return(int)$wpdb->insert_id;}
    public function saveDefault(int $instrumentId,int $courseId,string $status,?string $reason,string $now,?int $actor):int{global $wpdb;$current=$this->defaultForUpdate($instrumentId);if($current){$n=$wpdb->update($this->prefix.'instrument_intro_course_defaults',['course_id'=>$courseId,'status'=>$status,'reason_code'=>$reason,'version'=>(int)$current->version+1,'updated_at'=>$now,'updated_by'=>$actor],['id'=>$current->id,'version'=>$current->version]);if($n!==1)throw new \RuntimeException('Default changed concurrently');return(int)$current->id;}$ok=$wpdb->insert($this->prefix.'instrument_intro_course_defaults',['instrument_id'=>$instrumentId,'course_id'=>$courseId,'status'=>$status,'version'=>1,'reason_code'=>$reason,'created_at'=>$now,'updated_at'=>$now,'created_by'=>$actor,'updated_by'=>$actor]);if($ok===false)throw new \RuntimeException('Default persistence failed: '.$wpdb->last_error);return(int)$wpdb->insert_id;}
    public function saveAccepting(int $teacherId,string $state,?string $reason,string $now,?int $actor):int{global $wpdb;$current=$this->acceptingForUpdate($teacherId);if($current){$n=$wpdb->update($this->prefix.'teacher_accepting_states',['state'=>$state,'reason_code'=>$reason,'version'=>(int)$current->version+1,'updated_at'=>$now,'updated_by'=>$actor],['id'=>$current->id,'version'=>$current->version]);if($n!==1)throw new \RuntimeException('Accepting state changed concurrently');return(int)$current->id;}$ok=$wpdb->insert($this->prefix.'teacher_accepting_states',['teacher_id'=>$teacherId,'state'=>$state,'version'=>1,'reason_code'=>$reason,'created_at'=>$now,'updated_at'=>$now,'created_by'=>$actor,'updated_by'=>$actor]);if($ok===false)throw new \RuntimeException('Accepting state persistence failed: '.$wpdb->last_error);return(int)$wpdb->insert_id;}
    public function effectiveEligibility(int $teacherId,int $courseId,string $now):bool{global $wpdb;$sql="SELECT e.id FROM {$this->prefix}teacher_course_eligibilities e INNER JOIN {$this->prefix}teachers t ON t.id=e.teacher_id INNER JOIN {$this->prefix}courses c ON c.id=e.course_id INNER JOIN {$this->prefix}teacher_onboarding_states o ON o.teacher_id=t.id INNER JOIN {$this->prefix}teacher_accepting_states a ON a.teacher_id=t.id WHERE e.teacher_id=%d AND e.course_id=%d AND e.status='active' AND (e.effective_from IS NULL OR e.effective_from<=%s) AND (e.effective_until IS NULL OR e.effective_until>%s) AND t.status='active' AND t.archived_at IS NULL AND c.status='active' AND c.archived_at IS NULL AND o.state='active' AND o.readiness_state='ready' AND a.state IN ('accepting','limited') LIMIT 1";return(bool)$wpdb->get_var($wpdb->prepare($sql,$teacherId,$courseId,$now,$now));}
    public function resolveDefault(int $instrumentId):?object{global $wpdb;$sql="SELECT d.* FROM {$this->prefix}instrument_intro_course_defaults d INNER JOIN {$this->prefix}instruments i ON i.id=d.instrument_id INNER JOIN {$this->prefix}courses c ON c.id=d.course_id WHERE d.instrument_id=%d AND d.status='active' AND i.status='active' AND i.archived_at IS NULL AND c.status='active' AND c.archived_at IS NULL AND c.course_type='introductory' AND c.instrument_id=d.instrument_id LIMIT 1";return $wpdb->get_row($wpdb->prepare($sql,$instrumentId));}
    public function rows(string $table):array{global $wpdb;$allowed=['teacher_course_eligibilities','instrument_intro_course_defaults','teacher_accepting_states'];if(!in_array($table,$allowed,true))throw new \InvalidArgumentException('Unsupported eligibility table');return $wpdb->get_results("SELECT * FROM {$this->prefix}{$table} ORDER BY id DESC LIMIT 100");}
}
