<?php
namespace Delnavazan\Platform\Core\Infrastructure\Repository;

/** Fixed-table persistence for authoritative local-wall-clock availability facts. */
final class TeacherAvailabilityRepository {
    private string $prefix;
    public function __construct() { global $wpdb; $this->prefix = $wpdb->prefix . 'dzn_'; }
    public function begin(): void { global $wpdb; if ( $wpdb->query( 'START TRANSACTION' ) === false ) throw new \RuntimeException( 'Transaction start failed' ); }
    public function commit(): void { global $wpdb; if ( $wpdb->query( 'COMMIT' ) === false ) throw new \RuntimeException( 'Transaction commit failed' ); }
    public function rollback(): void { global $wpdb; $wpdb->query( 'ROLLBACK' ); }
    public function teacherForUpdate(int $id): ?object { global $wpdb; return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$this->prefix}teachers WHERE id=%d FOR UPDATE", $id ) ); }
    public function acceptingForUpdate(int $teacher): ?object { global $wpdb; return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$this->prefix}teacher_accepting_states WHERE teacher_id=%d FOR UPDATE", $teacher ) ); }
    public function profileForUpdate(int $teacher): ?object { global $wpdb; return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$this->prefix}teacher_availability_profiles WHERE teacher_id=%d FOR UPDATE", $teacher ) ); }
    public function profile(int $teacher): ?object { global $wpdb; return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$this->prefix}teacher_availability_profiles WHERE teacher_id=%d", $teacher ) ); }
    public function childrenExist(int $profile): bool { global $wpdb; return (bool) $wpdb->get_var( $wpdb->prepare( "SELECT 1 FROM {$this->prefix}teacher_availability_rules WHERE profile_id=%d LIMIT 1", $profile ) ) || (bool) $wpdb->get_var( $wpdb->prepare( "SELECT 1 FROM {$this->prefix}teacher_availability_exceptions WHERE profile_id=%d LIMIT 1", $profile ) ); }
    public function ruleForUpdate(int $id): ?object { global $wpdb; return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$this->prefix}teacher_availability_rules WHERE id=%d FOR UPDATE", $id ) ); }
    public function exceptionForUpdate(int $id): ?object { global $wpdb; return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$this->prefix}teacher_availability_exceptions WHERE id=%d FOR UPDATE", $id ) ); }
    public function exactRuleForUpdate(array $d): ?object { global $wpdb; return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$this->prefix}teacher_availability_rules WHERE teacher_id=%d AND weekday=%d AND local_start_time=%s AND local_end_time=%s AND state=%s AND timezone=%s FOR UPDATE", $d['teacher_id'], $d['weekday'], $d['local_start_time'], $d['local_end_time'], $d['state'], $d['timezone'] ) ); }
    public function exactExceptionForUpdate(array $d): ?object { global $wpdb; return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$this->prefix}teacher_availability_exceptions WHERE teacher_id=%d AND local_date=%s AND all_day=%d AND local_start_time=%s AND local_end_time=%s AND state=%s AND timezone=%s FOR UPDATE", $d['teacher_id'], $d['local_date'], $d['all_day'], $d['local_start_time'], $d['local_end_time'], $d['state'], $d['timezone'] ) ); }
    public function saveProfile(int $teacher, string $timezone, string $status, ?string $reason, string $now, ?int $actor): int { global $wpdb; $current = $this->profileForUpdate( $teacher ); if ( $current ) { $n = $wpdb->update( $this->prefix . 'teacher_availability_profiles', array( 'timezone' => $timezone, 'status' => $status, 'reason_code' => $reason, 'version' => (int) $current->version + 1, 'updated_at' => $now, 'updated_by' => $actor ), array( 'id' => $current->id, 'version' => $current->version ) ); if ( $n !== 1 ) throw new \RuntimeException( 'Availability profile changed concurrently' ); return (int) $current->id; } $ok = $wpdb->insert( $this->prefix . 'teacher_availability_profiles', array( 'teacher_id' => $teacher, 'timezone' => $timezone, 'status' => $status, 'version' => 1, 'reason_code' => $reason, 'created_at' => $now, 'updated_at' => $now, 'created_by' => $actor, 'updated_by' => $actor ) ); if ( $ok === false ) throw new \RuntimeException( 'Availability profile persistence failed' ); return (int) $wpdb->insert_id; }
    public function saveRule(array $d, string $now, ?int $actor): int { return $this->saveChild( 'teacher_availability_rules', 'ruleForUpdate', 'exactRuleForUpdate', $d, $now, $actor ); }
    public function saveException(array $d, string $now, ?int $actor): int { return $this->saveChild( 'teacher_availability_exceptions', 'exceptionForUpdate', 'exactExceptionForUpdate', $d, $now, $actor ); }
    private function saveChild(string $table, string $byId, string $exact, array $d, string $now, ?int $actor): int { global $wpdb; $current = ! empty( $d['id'] ) ? $this->{$byId}( (int) $d['id'] ) : $this->{$exact}( $d ); if ( $current ) { if ( (int) $current->teacher_id !== (int) $d['teacher_id'] || (int) $current->profile_id !== (int) $d['profile_id'] ) throw new \InvalidArgumentException( 'Availability fact does not belong to Teacher profile' ); unset( $d['id'] ); $d += array(); $d['version'] = (int) $current->version + 1; $d['updated_at'] = $now; $d['updated_by'] = $actor; $n = $wpdb->update( $this->prefix . $table, $d, array( 'id' => $current->id, 'version' => $current->version ) ); if ( $n !== 1 ) throw new \RuntimeException( 'Availability fact changed concurrently' ); return (int) $current->id; } unset( $d['id'] ); $d['version'] = 1; $d['created_at'] = $now; $d['updated_at'] = $now; $d['created_by'] = $actor; $d['updated_by'] = $actor; $ok = $wpdb->insert( $this->prefix . $table, $d ); if ( $ok === false ) throw new \RuntimeException( 'Availability fact persistence failed' ); return (int) $wpdb->insert_id; }
    public function activeRules(int $teacher): array { global $wpdb; return $wpdb->get_results( $wpdb->prepare( "SELECT * FROM {$this->prefix}teacher_availability_rules WHERE teacher_id=%d AND status='active' ORDER BY id", $teacher ) ); }
    public function activeExceptions(int $teacher, string $from, string $until): array { global $wpdb; return $wpdb->get_results( $wpdb->prepare( "SELECT * FROM {$this->prefix}teacher_availability_exceptions WHERE teacher_id=%d AND status='active' AND local_date BETWEEN %s AND %s ORDER BY id", $teacher, $from, $until ) ); }
    public function evaluableTeacher(int $teacher): bool { global $wpdb; return (bool) $wpdb->get_var( $wpdb->prepare( "SELECT t.id FROM {$this->prefix}teachers t INNER JOIN {$this->prefix}teacher_accepting_states a ON a.teacher_id=t.id WHERE t.id=%d AND t.status='active' AND t.archived_at IS NULL AND a.state IN ('accepting','limited') LIMIT 1", $teacher ) ); }
    public function rows(string $table): array { global $wpdb; $allowed = array( 'teacher_availability_profiles', 'teacher_availability_rules', 'teacher_availability_exceptions' ); if ( ! in_array( $table, $allowed, true ) ) throw new \InvalidArgumentException( 'Unsupported availability table' ); return $wpdb->get_results( "SELECT * FROM {$this->prefix}{$table} ORDER BY id DESC LIMIT 100" ); }
}
