<?php
namespace Delnavazan\Platform\Core\Infrastructure\Migration;
final class Migrator {
	private const OPTION = 'dzn_platform_schema_version'; private const LOCK = 'dzn_platform_migration_lock';
	public static function activate(): void {
		if ( get_option( self::OPTION ) === DZN_PLATFORM_SCHEMA_VERSION ) { return; }
		$token = wp_generate_uuid4(); $lock = get_option( self::LOCK );
		if ( $lock && isset( $lock['at'] ) && time() - (int) $lock['at'] < 900 ) { return; }
		update_option( self::LOCK, array( 'token' => $token, 'at' => time() ), false );
		try { self::install(); update_option( self::OPTION, DZN_PLATFORM_SCHEMA_VERSION, false ); }
		finally { $current = get_option( self::LOCK ); if ( is_array( $current ) && ( $current['token'] ?? '' ) === $token ) { delete_option( self::LOCK ); } }
	}
	private static function install(): void {
		global $wpdb; require_once ABSPATH . 'wp-admin/includes/upgrade.php'; $p = $wpdb->prefix . 'dzn_'; $c = $wpdb->get_charset_collate();
		$tables = array(
		"CREATE TABLE {$p}teachers (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NOT NULL,status varchar(32) NOT NULL,persian_name varchar(191) NULL,english_name varchar(191) NULL,display_name varchar(191) NOT NULL,email varchar(254) NULL,phone varchar(32) NULL,whatsapp_phone varchar(32) NULL,country_code char(2) NULL,city varchar(191) NULL,timezone varchar(64) NULL,timezone_source varchar(32) NULL,locale varchar(16) NULL,calendar_preference varchar(16) NULL,wordpress_user_id bigint unsigned NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY (id),UNIQUE KEY uid (uid),UNIQUE KEY reference_code (reference_code),KEY status (status),KEY email (email),KEY wordpress_user_id (wordpress_user_id),KEY archived_at (archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}students LIKE {$p}teachers",
		"CREATE TABLE {$p}instruments (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NOT NULL,slug varchar(191) NOT NULL,name_fa varchar(191) NULL,name_en varchar(191) NULL,status varchar(32) NOT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY uid(uid),UNIQUE KEY reference_code(reference_code),UNIQUE KEY slug(slug),KEY status(status),KEY archived_at(archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}courses (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NOT NULL,instrument_id bigint unsigned NOT NULL,name_fa varchar(191) NOT NULL,name_en varchar(191) NOT NULL,course_type varchar(32) NOT NULL,status varchar(32) NOT NULL,default_duration_minutes smallint unsigned NOT NULL,default_buffer_minutes smallint unsigned NOT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY uid(uid),UNIQUE KEY reference_code(reference_code),KEY instrument_id(instrument_id),KEY status(status),KEY course_type(course_type),KEY archived_at(archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}enrolments (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NOT NULL,student_id bigint unsigned NOT NULL,teacher_id bigint unsigned NOT NULL,course_id bigint unsigned NOT NULL,status varchar(32) NOT NULL,started_at datetime NULL,ended_at datetime NULL,preferred_weekday tinyint unsigned NULL,preferred_local_time time NULL,schedule_timezone varchar(64) NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY uid(uid),UNIQUE KEY reference_code(reference_code),KEY student_id(student_id),KEY teacher_id(teacher_id),KEY course_id(course_id),KEY status(status),KEY archived_at(archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}terms (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NOT NULL,enrolment_id bigint unsigned NOT NULL,sequence_number smallint unsigned NOT NULL,status varchar(32) NOT NULL,lesson_allocation smallint unsigned NOT NULL,replacement_allowance smallint unsigned NOT NULL,starts_at datetime NULL,ends_at datetime NULL,activated_at datetime NULL,completed_at datetime NULL,payment_state varchar(32) NOT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY uid(uid),UNIQUE KEY reference_code(reference_code),UNIQUE KEY enrolment_sequence(enrolment_id,sequence_number),KEY status(status),KEY archived_at(archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}lessons (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NOT NULL,student_id bigint unsigned NOT NULL,teacher_id bigint unsigned NOT NULL,course_id bigint unsigned NOT NULL,enrolment_id bigint unsigned NULL,term_id bigint unsigned NULL,lesson_type varchar(32) NOT NULL,status varchar(32) NOT NULL,sequence_number smallint unsigned NULL,current_schedule_version_id bigint unsigned NULL,replacement_for_lesson_id bigint unsigned NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,cancelled_at datetime NULL,completed_at datetime NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY uid(uid),UNIQUE KEY reference_code(reference_code),KEY student_id(student_id),KEY teacher_id(teacher_id),KEY course_id(course_id),KEY enrolment_id(enrolment_id),KEY term_id(term_id),KEY status(status),KEY lesson_type(lesson_type),KEY archived_at(archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}lesson_schedule_versions (id bigint unsigned NOT NULL AUTO_INCREMENT,lesson_id bigint unsigned NOT NULL,version_number smallint unsigned NOT NULL,starts_at_utc datetime NOT NULL,ends_at_utc datetime NOT NULL,schedule_timezone varchar(64) NOT NULL,local_wall_date date NOT NULL,local_wall_time time NOT NULL,reason varchar(255) NULL,changed_by bigint unsigned NULL,created_at datetime NOT NULL,superseded_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY lesson_version(lesson_id,version_number),KEY starts_at_utc(starts_at_utc),KEY ends_at_utc(ends_at_utc),KEY lesson_current(lesson_id,superseded_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}operational_exceptions (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,exception_type varchar(32) NOT NULL,severity varchar(32) NOT NULL,entity_type varchar(32) NULL,entity_id bigint unsigned NULL,fingerprint varchar(255) NOT NULL,status varchar(32) NOT NULL,summary varchar(255) NOT NULL,safe_detail text NULL,error_code varchar(255) NULL,detected_at datetime NOT NULL,last_seen_at datetime NOT NULL,resolved_at datetime NULL,resolved_by bigint unsigned NULL,resolution_note text NULL,retry_available tinyint(1) NOT NULL DEFAULT 0,retry_count smallint unsigned NOT NULL DEFAULT 0,PRIMARY KEY(id),UNIQUE KEY uid(uid),KEY fingerprint_status(fingerprint,status),KEY status(status)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}teacher_profile_links (id bigint unsigned NOT NULL AUTO_INCREMENT,teacher_id bigint unsigned NOT NULL,profile_source varchar(32) NOT NULL,profile_id bigint unsigned NOT NULL,created_at datetime NOT NULL,created_by bigint unsigned NULL,removed_at datetime NULL,removed_by bigint unsigned NULL,PRIMARY KEY(id),KEY teacher_id(teacher_id),KEY profile(profile_source,profile_id),KEY removed_at(removed_at)) ENGINE=InnoDB $c"
		); foreach ( $tables as $sql ) { dbDelta( $sql ); }
	}
}
