<?php
namespace Delnavazan\Platform\Core\Infrastructure\Migration;
final class Migrator {
	private const OPTION = 'dzn_platform_schema_version'; private const LOCK = 'dzn_platform_migration_lock'; private const COMPLETED = 'dzn_platform_completed_migrations';
	public static function on_activation(): void { self::install_capabilities(); self::maybe_upgrade(); }
	public static function maybe_upgrade(): void {
		if ( (string) get_option( self::OPTION ) === (string) DZN_PLATFORM_SCHEMA_VERSION ) { self::verify_current_schema(); return; }
		self::install_capabilities();
		$token = wp_generate_uuid4(); $lock = get_option( self::LOCK );
		if ( $lock && isset( $lock['at'] ) && time() - (int) $lock['at'] >= 900 ) { delete_option( self::LOCK ); }
		if ( ! add_option( self::LOCK, array( 'token' => $token, 'at' => time() ), '', 'no' ) ) { return; }
		try { foreach(array('001_initial_core_schema'=>array(__CLASS__,'install'),'002_principal_invitation_foundation'=>array(__CLASS__,'install_principal_invitation_foundation'),'003_invitation_recipient_snapshot'=>array(__CLASS__,'install_invitation_recipient_snapshot'),'004_teaching_eligibility_foundation'=>array(__CLASS__,'install_teaching_eligibility_foundation')) as $id=>$migration){$done=(array)get_option(self::COMPLETED,array());if(in_array($id,$done,true))continue;call_user_func($migration);self::verify_schema();if($id==='002_principal_invitation_foundation'||$id==='003_invitation_recipient_snapshot'){self::verify_principal_invitation_schema();self::verify_delivery_preparation_schema();}if($id==='004_teaching_eligibility_foundation')self::verify_teaching_eligibility_schema();$done[]=$id;update_option(self::COMPLETED,$done,false);} update_option( self::OPTION, DZN_PLATFORM_SCHEMA_VERSION, false ); }
		finally { $current = get_option( self::LOCK ); if ( is_array( $current ) && ( $current['token'] ?? '' ) === $token ) { delete_option( self::LOCK ); } }
	}
	/** A version option is never proof that the concurrency-critical schema exists. */
	private static function verify_current_schema(): void {
		$required = array( '001_initial_core_schema', '002_principal_invitation_foundation', '003_invitation_recipient_snapshot', '004_teaching_eligibility_foundation' );
		$completed = (array) get_option( self::COMPLETED, array() );
		foreach ( $required as $migration ) if ( ! in_array( $migration, $completed, true ) ) throw new \RuntimeException( 'Migration verification failed: completed migration ' . $migration );
		self::verify_schema(); self::verify_principal_invitation_schema(); self::verify_delivery_preparation_schema(); self::verify_teaching_eligibility_schema();
	}
	private static function install(): void {
		global $wpdb; require_once ABSPATH . 'wp-admin/includes/upgrade.php'; $p = $wpdb->prefix . 'dzn_'; $c = $wpdb->get_charset_collate();
		$tables = array(
		"CREATE TABLE {$p}teachers (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NULL,status varchar(32) NOT NULL,persian_name varchar(191) NULL,english_name varchar(191) NULL,display_name varchar(191) NOT NULL,email varchar(254) NULL,phone varchar(32) NULL,whatsapp_phone varchar(32) NULL,country_code char(2) NULL,city varchar(191) NULL,timezone varchar(64) NULL,timezone_source varchar(32) NULL,locale varchar(16) NULL,calendar_preference varchar(16) NULL,wordpress_user_id bigint unsigned NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY (id),UNIQUE KEY uid (uid),UNIQUE KEY reference_code (reference_code),KEY status (status),KEY email (email),KEY wordpress_user_id (wordpress_user_id),KEY archived_at (archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}students (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NULL,status varchar(32) NOT NULL,first_name varchar(191) NULL,last_name varchar(191) NULL,display_name varchar(191) NOT NULL,email varchar(254) NULL,phone varchar(32) NULL,whatsapp_phone varchar(32) NULL,country_code char(2) NULL,city varchar(191) NULL,timezone varchar(64) NULL,timezone_source varchar(32) NULL,locale varchar(16) NULL,calendar_preference varchar(16) NULL,wordpress_user_id bigint unsigned NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY uid(uid),UNIQUE KEY reference_code(reference_code),KEY status(status),KEY email(email),KEY wordpress_user_id(wordpress_user_id),KEY archived_at(archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}instruments (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NULL,slug varchar(191) NOT NULL,name_fa varchar(191) NULL,name_en varchar(191) NULL,status varchar(32) NOT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY uid(uid),UNIQUE KEY reference_code(reference_code),UNIQUE KEY slug(slug),KEY status(status),KEY archived_at(archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}courses (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NULL,instrument_id bigint unsigned NOT NULL,name_fa varchar(191) NOT NULL,name_en varchar(191) NOT NULL,course_type varchar(32) NOT NULL,status varchar(32) NOT NULL,default_duration_minutes smallint unsigned NOT NULL,default_buffer_minutes smallint unsigned NOT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY uid(uid),UNIQUE KEY reference_code(reference_code),KEY instrument_id(instrument_id),KEY status(status),KEY course_type(course_type),KEY archived_at(archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}enrolments (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NULL,student_id bigint unsigned NOT NULL,teacher_id bigint unsigned NOT NULL,course_id bigint unsigned NOT NULL,status varchar(32) NOT NULL,started_at datetime NULL,ended_at datetime NULL,preferred_weekday tinyint unsigned NULL,preferred_local_time time NULL,schedule_timezone varchar(64) NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY uid(uid),UNIQUE KEY reference_code(reference_code),KEY student_id(student_id),KEY teacher_id(teacher_id),KEY course_id(course_id),KEY status(status),KEY schedule_timezone(schedule_timezone),KEY archived_at(archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}terms (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NULL,enrolment_id bigint unsigned NOT NULL,sequence_number smallint unsigned NOT NULL,status varchar(32) NOT NULL,lesson_allocation smallint unsigned NOT NULL,replacement_allowance smallint unsigned NOT NULL,starts_at datetime NULL,ends_at datetime NULL,activated_at datetime NULL,completed_at datetime NULL,payment_state varchar(32) NOT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY uid(uid),UNIQUE KEY reference_code(reference_code),UNIQUE KEY enrolment_sequence(enrolment_id,sequence_number),KEY enrolment_id(enrolment_id),KEY status(status),KEY payment_state(payment_state),KEY archived_at(archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}lessons (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,reference_code varchar(32) NULL,student_id bigint unsigned NOT NULL,teacher_id bigint unsigned NOT NULL,course_id bigint unsigned NOT NULL,enrolment_id bigint unsigned NULL,term_id bigint unsigned NULL,lesson_type varchar(32) NOT NULL,status varchar(32) NOT NULL,sequence_number smallint unsigned NULL,current_schedule_version_id bigint unsigned NULL,replacement_for_lesson_id bigint unsigned NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,cancelled_at datetime NULL,completed_at datetime NULL,archived_at datetime NULL,archived_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY uid(uid),UNIQUE KEY reference_code(reference_code),KEY student_id(student_id),KEY teacher_id(teacher_id),KEY course_id(course_id),KEY enrolment_id(enrolment_id),KEY term_id(term_id),KEY status(status),KEY lesson_type(lesson_type),KEY current_schedule_version_id(current_schedule_version_id),KEY replacement_for_lesson_id(replacement_for_lesson_id),KEY archived_at(archived_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}lesson_schedule_versions (id bigint unsigned NOT NULL AUTO_INCREMENT,lesson_id bigint unsigned NOT NULL,version_number smallint unsigned NOT NULL,starts_at_utc datetime NOT NULL,ends_at_utc datetime NOT NULL,schedule_timezone varchar(64) NOT NULL,local_wall_date date NOT NULL,local_wall_time time NOT NULL,reason varchar(255) NULL,changed_by bigint unsigned NULL,created_at datetime NOT NULL,superseded_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY lesson_version(lesson_id,version_number),KEY starts_at_utc(starts_at_utc),KEY ends_at_utc(ends_at_utc),KEY lesson_current(lesson_id,superseded_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}operational_exceptions (id bigint unsigned NOT NULL AUTO_INCREMENT,uid char(26) NOT NULL,exception_type varchar(64) NOT NULL,severity varchar(16) NOT NULL,entity_type varchar(32) NULL,entity_id bigint unsigned NULL,fingerprint char(64) NOT NULL,status varchar(32) NOT NULL,summary varchar(255) NOT NULL,safe_detail text NULL,error_code varchar(64) NULL,detected_at datetime NOT NULL,last_seen_at datetime NOT NULL,resolved_at datetime NULL,resolved_by bigint unsigned NULL,resolution_note text NULL,retry_available tinyint(1) NOT NULL DEFAULT 0,retry_count smallint unsigned NOT NULL DEFAULT 0,PRIMARY KEY(id),UNIQUE KEY uid(uid),KEY status(status),KEY severity(severity),KEY exception_type(exception_type),KEY fingerprint(fingerprint),KEY entity(entity_type,entity_id),KEY detected_at(detected_at),KEY last_seen_at(last_seen_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}teacher_profile_links (id bigint unsigned NOT NULL AUTO_INCREMENT,teacher_id bigint unsigned NOT NULL,profile_source varchar(32) NOT NULL,profile_id bigint unsigned NOT NULL,created_at datetime NOT NULL,created_by bigint unsigned NULL,removed_at datetime NULL,removed_by bigint unsigned NULL,PRIMARY KEY(id),KEY teacher_id(teacher_id),KEY profile(profile_source,profile_id),KEY removed_at(removed_at)) ENGINE=InnoDB $c"
		); foreach ( $tables as $sql ) { dbDelta( $sql ); }
	}
	private static function verify_schema():void { global $wpdb; $p=$wpdb->prefix.'dzn_'; $tables=array('teachers','students','instruments','courses','enrolments','terms','lessons','lesson_schedule_versions','operational_exceptions','teacher_profile_links'); foreach($tables as $table){ if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$p.$table))!==$p.$table) throw new \RuntimeException('Migration verification failed: missing '.$table); } foreach(array('teachers','students','instruments','courses','enrolments','terms','lessons') as $table){ $column=$wpdb->get_row("SHOW COLUMNS FROM {$p}{$table} LIKE 'reference_code'"); if(!$column||$column->Null!=='YES'||!self::has_index($p.$table,'reference_code',true)||!self::has_index($p.$table,'uid',true)) throw new \RuntimeException('Migration verification failed: identity contract'); } foreach(array(array('instruments','slug',true),array('terms','enrolment_sequence',true),array('lesson_schedule_versions','lesson_version',true),array('enrolments','schedule_timezone',false),array('terms','enrolment_id',false),array('terms','payment_state',false),array('lessons','current_schedule_version_id',false),array('lessons','replacement_for_lesson_id',false),array('operational_exceptions','fingerprint',false),array('operational_exceptions','entity',false)) as $spec){if(!self::has_index($p.$spec[0],$spec[1],$spec[2]))throw new \RuntimeException('Migration verification failed: index '.$spec[1]);} foreach(array('exception_type'=>'varchar(64)','severity'=>'varchar(16)','fingerprint'=>'char(64)','error_code'=>'varchar(64)') as $column=>$type){$row=$wpdb->get_row("SHOW COLUMNS FROM {$p}operational_exceptions LIKE '{$column}'");if(!$row||strtolower($row->Type)!==$type)throw new \RuntimeException('Migration verification failed: exception column '.$column);} }
	private static function install_principal_invitation_foundation(): void {
		global $wpdb; require_once ABSPATH . 'wp-admin/includes/upgrade.php'; $p=$wpdb->prefix.'dzn_'; $c=$wpdb->get_charset_collate();
		$tables=array(
		"CREATE TABLE {$p}teacher_onboarding_states (id bigint unsigned NOT NULL AUTO_INCREMENT,teacher_id bigint unsigned NOT NULL,state varchar(32) NOT NULL,readiness_state varchar(32) NOT NULL,version bigint unsigned NOT NULL DEFAULT 1,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY teacher_id(teacher_id),KEY state(state)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}teacher_principal_links (id bigint unsigned NOT NULL AUTO_INCREMENT,teacher_id bigint unsigned NOT NULL,wordpress_user_id bigint unsigned NOT NULL,status varchar(16) NOT NULL,linked_at datetime NOT NULL,linked_by bigint unsigned NULL,revoked_at datetime NULL,revoked_by bigint unsigned NULL,reason_code varchar(64) NULL,PRIMARY KEY(id),UNIQUE KEY teacher_id(teacher_id),UNIQUE KEY wordpress_user_id(wordpress_user_id),KEY status(status)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}student_principal_links (id bigint unsigned NOT NULL AUTO_INCREMENT,student_id bigint unsigned NOT NULL,wordpress_user_id bigint unsigned NOT NULL,status varchar(16) NOT NULL,linked_at datetime NOT NULL,linked_by bigint unsigned NULL,revoked_at datetime NULL,revoked_by bigint unsigned NULL,reason_code varchar(64) NULL,PRIMARY KEY(id),UNIQUE KEY student_id(student_id),UNIQUE KEY wordpress_user_id(wordpress_user_id),KEY status(status)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}teacher_invitations (id bigint unsigned NOT NULL AUTO_INCREMENT,teacher_id bigint unsigned NOT NULL,recipient_digest char(64) NOT NULL,current_generation_number int unsigned NOT NULL DEFAULT 0,status varchar(24) NOT NULL,version bigint unsigned NOT NULL DEFAULT 1,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY teacher_id(teacher_id),KEY status(status)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}teacher_invitation_generations (id bigint unsigned NOT NULL AUTO_INCREMENT,invitation_id bigint unsigned NOT NULL,generation_number int unsigned NOT NULL,recipient_snapshot varchar(320) NULL,recipient_digest char(64) NULL,secret_digest char(64) NULL,status varchar(24) NOT NULL,expires_at datetime NOT NULL,delivery_prepared_at datetime NULL,delivery_attempt_count smallint unsigned NOT NULL DEFAULT 0,claimed_at datetime NULL,revoked_at datetime NULL,superseded_at datetime NULL,delivery_key char(64) NOT NULL,created_at datetime NOT NULL,created_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY invitation_generation(invitation_id,generation_number),UNIQUE KEY secret_digest(secret_digest),UNIQUE KEY delivery_key(delivery_key),KEY status_expires(status,expires_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}student_account_invitations (id bigint unsigned NOT NULL AUTO_INCREMENT,student_id bigint unsigned NOT NULL,recipient_digest char(64) NOT NULL,current_generation_number int unsigned NOT NULL DEFAULT 0,status varchar(24) NOT NULL,version bigint unsigned NOT NULL DEFAULT 1,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY student_id(student_id),KEY status(status)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}student_account_invitation_generations (id bigint unsigned NOT NULL AUTO_INCREMENT,invitation_id bigint unsigned NOT NULL,generation_number int unsigned NOT NULL,secret_digest char(64) NOT NULL,status varchar(24) NOT NULL,expires_at datetime NOT NULL,claimed_at datetime NULL,revoked_at datetime NULL,superseded_at datetime NULL,delivery_key char(64) NOT NULL,created_at datetime NOT NULL,created_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY invitation_generation(invitation_id,generation_number),UNIQUE KEY secret_digest(secret_digest),UNIQUE KEY delivery_key(delivery_key),KEY status_expires(status,expires_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}account_claim_attempts (id bigint unsigned NOT NULL AUTO_INCREMENT,invitation_id bigint unsigned NOT NULL,generation_id bigint unsigned NOT NULL,domain varchar(16) NOT NULL,command_key char(64) NOT NULL,wordpress_user_id bigint unsigned NULL,state varchar(40) NOT NULL,provisioning_marker char(64) NULL,recovery_reason varchar(64) NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,finalized_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY command_key(command_key),UNIQUE KEY generation_owner(generation_id),KEY state(state),KEY recovery(state,updated_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}platform_audit_events (id bigint unsigned NOT NULL AUTO_INCREMENT,aggregate_type varchar(32) NOT NULL,aggregate_id bigint unsigned NOT NULL,event_type varchar(64) NOT NULL,actor_type varchar(16) NOT NULL,actor_id bigint unsigned NULL,reason_code varchar(64) NULL,safe_detail text NULL,idempotency_key char(64) NOT NULL,occurred_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY idempotency_key(idempotency_key),KEY aggregate(aggregate_type,aggregate_id),KEY event_type(event_type),KEY occurred_at(occurred_at)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}platform_outbox (id bigint unsigned NOT NULL AUTO_INCREMENT,aggregate_type varchar(32) NOT NULL,aggregate_id bigint unsigned NOT NULL,event_type varchar(64) NOT NULL,invitation_id bigint unsigned NULL,generation_id bigint unsigned NULL,idempotency_key char(64) NOT NULL,status varchar(16) NOT NULL,available_at datetime NOT NULL,leased_at datetime NULL,processed_at datetime NULL,attempt_count smallint unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY idempotency_key(idempotency_key),KEY available(status,available_at),KEY invitation_generation(invitation_id,generation_id)) ENGINE=InnoDB $c"
		); foreach($tables as $sql){dbDelta($sql); if($wpdb->last_error!=='')throw new \RuntimeException('Migration operation failed: '.$wpdb->last_error);}
	}
	/**
	 * Adds the immutable Core-owned recipient binding for databases that completed
	 * 002 before these fields were introduced. dbDelta() did not reliably add
	 * these nullable fields to that existing table, so this is deliberately
	 * introspection-driven and only alters columns that are genuinely absent.
	 */
	private static function install_invitation_recipient_snapshot(): void {
		global $wpdb;
		$table = $wpdb->prefix . 'dzn_teacher_invitation_generations';
		$columns = array(
			'recipient_snapshot' => 'recipient_snapshot varchar(320) NULL',
			'recipient_digest' => 'recipient_digest char(64) NULL',
		);

		foreach ( $columns as $name => $definition ) {
			$column = $wpdb->get_row( $wpdb->prepare( "SHOW COLUMNS FROM {$table} LIKE %s", $name ) );
			if ( $column ) {
				continue;
			}
			$result = $wpdb->query( "ALTER TABLE {$table} ADD COLUMN {$definition}" );
			if ( $result === false ) {
				throw new \RuntimeException( 'Migration operation failed: ' . $wpdb->last_error );
			}
		}
	}
	private static function install_teaching_eligibility_foundation(): void {
		global $wpdb; require_once ABSPATH . 'wp-admin/includes/upgrade.php'; $p=$wpdb->prefix.'dzn_'; $c=$wpdb->get_charset_collate();
		$tables=array(
		"CREATE TABLE {$p}teacher_course_eligibilities (id bigint unsigned NOT NULL AUTO_INCREMENT,teacher_id bigint unsigned NOT NULL,course_id bigint unsigned NOT NULL,status varchar(16) NOT NULL,effective_from datetime NULL,effective_until datetime NULL,version bigint unsigned NOT NULL DEFAULT 1,reason_code varchar(64) NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY teacher_course(teacher_id,course_id),KEY teacher_status(teacher_id,status),KEY course_status(course_id,status),KEY effective(status,effective_from,effective_until)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}instrument_intro_course_defaults (id bigint unsigned NOT NULL AUTO_INCREMENT,instrument_id bigint unsigned NOT NULL,course_id bigint unsigned NOT NULL,status varchar(16) NOT NULL,version bigint unsigned NOT NULL DEFAULT 1,reason_code varchar(64) NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY instrument_id(instrument_id),KEY course_status(course_id,status)) ENGINE=InnoDB $c",
		"CREATE TABLE {$p}teacher_accepting_states (id bigint unsigned NOT NULL AUTO_INCREMENT,teacher_id bigint unsigned NOT NULL,state varchar(16) NOT NULL,version bigint unsigned NOT NULL DEFAULT 1,reason_code varchar(64) NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,created_by bigint unsigned NULL,updated_by bigint unsigned NULL,PRIMARY KEY(id),UNIQUE KEY teacher_id(teacher_id),KEY state(state)) ENGINE=InnoDB $c"
		); foreach($tables as $sql){dbDelta($sql);if($wpdb->last_error!=='')throw new \RuntimeException('Migration operation failed: '.$wpdb->last_error);}
	}
	private static function verify_principal_invitation_schema(): void { global $wpdb; $p=$wpdb->prefix.'dzn_'; $spec=array('teacher_onboarding_states'=>array('teacher_id','state'),'teacher_principal_links'=>array('teacher_id','wordpress_user_id'),'student_principal_links'=>array('student_id','wordpress_user_id'),'teacher_invitations'=>array('teacher_id','recipient_digest'),'teacher_invitation_generations'=>array('recipient_snapshot','recipient_digest','secret_digest','delivery_key'),'student_account_invitations'=>array('student_id','recipient_digest'),'student_account_invitation_generations'=>array('secret_digest','delivery_key'),'account_claim_attempts'=>array('command_key','generation_id','state'),'platform_audit_events'=>array('idempotency_key','event_type'),'platform_outbox'=>array('idempotency_key','status')); foreach($spec as $table=>$columns){if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$p.$table))!==$p.$table)throw new \RuntimeException('Migration verification failed: missing '.$table); foreach($columns as $column){if(!$wpdb->get_row("SHOW COLUMNS FROM {$p}{$table} LIKE '{$column}'"))throw new \RuntimeException('Migration verification failed: missing '.$table.'.'.$column);}} foreach(array(array('teacher_principal_links','teacher_id',true),array('teacher_principal_links','wordpress_user_id',true),array('student_principal_links','student_id',true),array('student_principal_links','wordpress_user_id',true),array('teacher_invitations','teacher_id',true),array('teacher_invitation_generations','invitation_generation',true),array('teacher_invitation_generations','secret_digest',true),array('teacher_invitation_generations','delivery_key',true),array('student_account_invitations','student_id',true),array('student_account_invitation_generations','invitation_generation',true),array('student_account_invitation_generations','secret_digest',true),array('student_account_invitation_generations','delivery_key',true),array('account_claim_attempts','command_key',true),array('account_claim_attempts','generation_owner',true),array('platform_audit_events','idempotency_key',true),array('platform_outbox','idempotency_key',true)) as $index){if(!self::has_index($p.$index[0],$index[1],$index[2]))throw new \RuntimeException('Migration verification failed: principal index '.$index[0].'.'.$index[1]);}}
	private static function has_index(string $table,string $index,bool $unique):bool { global $wpdb; $row=$wpdb->get_row($wpdb->prepare("SHOW INDEX FROM {$table} WHERE Key_name=%s",$index)); return $row && (!$unique || (int)$row->Non_unique===0); }
	private static function verify_delivery_preparation_schema(): void { global $wpdb; $table=$wpdb->prefix.'dzn_teacher_invitation_generations'; foreach(array('recipient_snapshot'=>'varchar(320)','recipient_digest'=>'char(64)','secret_digest'=>'char(64)') as $column=>$type){$row=$wpdb->get_row("SHOW COLUMNS FROM {$table} LIKE '{$column}'");if(!$row||strtolower($row->Type)!==$type||$row->Null!=='YES')throw new \RuntimeException('Migration verification failed: invitation recipient/secret field '.$column);} foreach(array('delivery_prepared_at','delivery_attempt_count') as $column){if(!$wpdb->get_row("SHOW COLUMNS FROM {$table} LIKE '{$column}'"))throw new \RuntimeException('Migration verification failed: missing delivery preparation field '.$column);} }
	private static function verify_teaching_eligibility_schema():void{global $wpdb;$p=$wpdb->prefix.'dzn_';$tables=array('teacher_course_eligibilities'=>array('teacher_id','course_id','status','version'),'instrument_intro_course_defaults'=>array('instrument_id','course_id','status','version'),'teacher_accepting_states'=>array('teacher_id','state','version'));foreach($tables as $table=>$columns){if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$p.$table))!==$p.$table)throw new \RuntimeException('Migration verification failed: missing '.$table);foreach($columns as $column)if(!$wpdb->get_row("SHOW COLUMNS FROM {$p}{$table} LIKE '{$column}'"))throw new \RuntimeException('Migration verification failed: missing '.$table.'.'.$column);}foreach(array(array('teacher_course_eligibilities','teacher_course',true),array('teacher_course_eligibilities','teacher_status',false),array('teacher_course_eligibilities','course_status',false),array('instrument_intro_course_defaults','instrument_id',true),array('instrument_intro_course_defaults','course_status',false),array('teacher_accepting_states','teacher_id',true))as$index)if(!self::has_index($p.$index[0],$index[1],$index[2]))throw new \RuntimeException('Migration verification failed: teaching eligibility index '.$index[0].'.'.$index[1]);}
	private static function install_capabilities():void{$role=get_role('administrator');if(!$role)return;foreach(array('dzn_manage_platform','dzn_manage_students','dzn_manage_teachers','dzn_manage_courses','dzn_manage_enrolments','dzn_manage_terms','dzn_manage_lessons','dzn_manage_exceptions','dzn_view_diagnostics','dzn_manage_onboarding','dzn_issue_teacher_invitations','dzn_revoke_teacher_invitations','dzn_view_onboarding_audit','dzn_relink_teacher_principal','dzn_manage_teaching_eligibility')as$cap)$role->add_cap($cap); if(!get_role('dzn_teacher'))add_role('dzn_teacher','Delnavazan Teacher',array('read'=>true));}
}
