<?php
namespace Delnavazan\Platform\Admin\Controller;
final class AdminDashboardController {
 public static function register():void{add_action('wp_dashboard_setup',[self::class,'widgets']);}
 public static function widgets():void{if(!current_user_can('dzn_view_diagnostics'))return;wp_add_dashboard_widget('dzn_academy_snapshot','Delnavazan · Academy snapshot',[self::class,'snapshot']);wp_add_dashboard_widget('dzn_attention_snapshot','Delnavazan · Needs attention',[self::class,'attention']);wp_add_dashboard_widget('dzn_readiness_snapshot','Delnavazan · Launch readiness',[self::class,'readiness']);}
 public static function snapshot():void{global $wpdb;$p=$wpdb->prefix.'dzn_';$facts=['Students'=>"SELECT COUNT(*) FROM {$p}students WHERE archived_at IS NULL",'Teachers'=>"SELECT COUNT(*) FROM {$p}teachers WHERE archived_at IS NULL",'Open booking requests'=>"SELECT COUNT(*) FROM {$p}booking_requests WHERE privacy_erased_at IS NULL AND resolution_state='unresolved'",'Active enrolments'=>"SELECT COUNT(*) FROM {$p}enrolments WHERE archived_at IS NULL AND lifecycle_state='active'"];echo '<table class="widefat striped"><tbody>';foreach($facts as$l=>$q)echo '<tr><th>'.esc_html($l).'</th><td><strong>'.(int)$wpdb->get_var($q).'</strong></td></tr>';echo '</tbody></table><p><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=dzn-workspace')).'">Open Delnavazan workspace</a></p>';}
 public static function attention():void{global $wpdb;$p=$wpdb->prefix.'dzn_';$facts=[['Operational exceptions',"SELECT COUNT(*) FROM {$p}operational_exceptions WHERE status='open'",'dzn-exception'],['Teacher onboarding review',"SELECT COUNT(*) FROM {$p}teacher_onboarding_states WHERE state='pending_review'",'dzn-onboarding'],['Requests needing coordination',"SELECT COUNT(*) FROM {$p}booking_requests br LEFT JOIN {$p}coordination_cases cc ON cc.booking_request_id=br.id WHERE br.privacy_erased_at IS NULL AND br.resolution_state='unresolved' AND cc.id IS NULL",'dzn-academy-operations']];echo '<table class="widefat striped"><tbody>';foreach($facts as[$l,$q,$page]){echo '<tr><th><a href="'.esc_url(admin_url('admin.php?page='.$page)).'">'.esc_html($l).'</a></th><td><strong>'.(int)$wpdb->get_var($q).'</strong></td></tr>';}echo '</tbody></table><p class="description">Only unresolved work is shown here. Open the linked authority screen to investigate or act.</p>';}
 public static function readiness():void{global $wpdb;$p=$wpdb->prefix.'dzn_';$readyTeachers=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}teacher_onboarding_states o INNER JOIN {$p}teachers t ON t.id=o.teacher_id WHERE o.state='active' AND o.readiness_state='ready' AND t.status='active' AND t.archived_at IS NULL");$products=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}commercial_products WHERE status='active' AND archived_at IS NULL");$prices=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}commercial_prices WHERE status='active' AND archived_at IS NULL");$statements=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}finance_statements WHERE state IN ('draft','issued')");$rows=[['Ready teachers',$readyTeachers,'dzn-academy-coverage'],['Active commercial products',$products,'dzn-commercial-catalogue'],['Active regional prices',$prices,'dzn-commercial-catalogue'],['Live teacher statements',$statements,'dzn-finance-statements']];echo '<table class="widefat striped"><tbody>';foreach($rows as[$l,$n,$page])echo '<tr><th><a href="'.esc_url(admin_url('admin.php?page='.$page)).'">'.esc_html($l).'</a></th><td><strong>'.(int)$n.'</strong></td></tr>';echo '</tbody></table><p class="description">Readiness indicators only; zero is not automatically an error. Configuration and real operational data determine what is required.</p>';}
}
