<?php
namespace Delnavazan\Platform\Admin\Controller;

use Delnavazan\Platform\Core\Application\CoordinationCaseService;
use Delnavazan\Platform\Core\Application\TeacherAvailabilityAssentService;
use Delnavazan\Platform\Core\Infrastructure\Repository\CoordinationCaseRepository;
use Delnavazan\Platform\Core\Infrastructure\Repository\TeacherAvailabilityAssentRepository;

/** Protected internal operating surface; deliberately contains no proposal or assignment controls. */
final class CoordinationCaseController {
    private const CAPABILITY = 'dzn_manage_booking_request_coordination';
    public static function handlePost(): void {
        if ( ( $_SERVER['REQUEST_METHOD'] ?? '' ) !== 'POST' ) return;
        if ( ! current_user_can( self::CAPABILITY ) || ! current_user_can( 'dzn_view_booking_requests' ) ) wp_die( 'Access denied.', 'Delnavazan', array( 'response' => 403 ) );
        $action = self::string( $_POST['dzn_coordination_action'] ?? null ); if ( $action === '' ) return;
        try {
            $service = new CoordinationCaseService();
            if ( $action === 'open' ) { $request = self::id( $_POST['booking_request_id'] ?? null ); check_admin_referer( 'dzn_coordination_open' ); $service->open( $request, self::string( $_POST['reason'] ?? null ) ); }
            elseif ( $action === 'add_candidate' ) { $case = self::id( $_POST['case_id'] ?? null ); check_admin_referer( 'dzn_coordination_candidate_' . $case ); $service->addCandidate( $case, self::id( $_POST['teacher_id'] ?? null ), self::string( $_POST['source'] ?? null ), self::string( $_POST['reason'] ?? null ) ); }
            elseif ( $action === 'transition_case' ) { $case = self::id( $_POST['case_id'] ?? null ); check_admin_referer( 'dzn_coordination_case_state_' . $case ); $service->transition( $case, self::id( $_POST['version'] ?? null ), self::string( $_POST['state'] ?? null ), self::string( $_POST['reason'] ?? null ) ); }
            elseif ( $action === 'transition_candidate' ) { $candidate = self::id( $_POST['candidate_id'] ?? null ); check_admin_referer( 'dzn_coordination_candidate_state_' . $candidate ); $service->transitionCandidate( $candidate, self::id( $_POST['version'] ?? null ), self::string( $_POST['status'] ?? null ), self::string( $_POST['reason'] ?? null ) ); }
            elseif ( $action === 'record_teacher_assent' ) { check_admin_referer( 'dzn_teacher_assent_record' ); ( new TeacherAvailabilityAssentService() )->recordAdministratorAttestation( self::assentInput() ); }
            elseif ( $action === 'withdraw_teacher_assent' ) { $assent = self::id( $_POST['assent_id'] ?? null ); check_admin_referer( 'dzn_teacher_assent_state_' . $assent ); ( new TeacherAvailabilityAssentService() )->withdraw( $assent, self::id( $_POST['version'] ?? null ), self::string( $_POST['reason'] ?? null ) ); }
            elseif ( $action === 'invalidate_teacher_assent' ) { $assent = self::id( $_POST['assent_id'] ?? null ); check_admin_referer( 'dzn_teacher_assent_state_' . $assent ); ( new TeacherAvailabilityAssentService() )->invalidate( $assent, self::id( $_POST['version'] ?? null ), self::string( $_POST['reason'] ?? null ) ); }
            else throw new \InvalidArgumentException( 'Unsupported coordination action' );
            self::redirect( false );
        } catch ( \Throwable ) { self::redirect( true ); }
    }
    public static function screen(): void {
        if ( ! current_user_can( self::CAPABILITY ) || ! current_user_can( 'dzn_view_booking_requests' ) ) { echo '<div class="wrap"><p>Access denied.</p></div>'; return; }
        $repo = new CoordinationCaseRepository(); $caseId = self::idOrZero( $_GET['case_id'] ?? null );
        echo '<div class="wrap"><h1>Booking Request Coordination</h1>';
        if ( $caseId > 0 && ( $case = $repo->caseForRead( $caseId ) ) ) { self::detail( $repo, $case ); echo '</div>'; return; }
        echo '<p>Protected coordination records advisory candidates and bounded Teacher Availability Assent. Assent is not identity, assignment, capacity reservation, proposal, acceptance, conversion, booking, or payment authority.</p><h2>Open coordination</h2><form method="post">'; wp_nonce_field( 'dzn_coordination_open' ); echo '<input type="hidden" name="dzn_coordination_action" value="open"><p><label>Booking Request ID<br><input name="booking_request_id" type="number" min="1" required></label></p><p><label>Reason<br><select name="reason"><option value="admin_opened">admin_opened</option><option value="manual_review">manual_review</option></select></label></p><button class="button button-primary">Open coordination</button></form>';
        echo '<h2>Recent cases</h2><table class="widefat striped"><thead><tr><th>Reference</th><th>Booking Request</th><th>State</th><th>Version</th><th>Updated</th></tr></thead><tbody>';
        foreach ( $repo->rows() as $row ) { $url = add_query_arg( array( 'page' => 'dzn-booking-request-coordination', 'case_id' => $row->id ), admin_url( 'admin.php' ) ); echo '<tr><td><a href="' . esc_url( $url ) . '">' . esc_html( (string) $row->reference_code ) . '</a></td><td>' . esc_html( (string) $row->booking_request_id ) . '</td><td>' . esc_html( (string) $row->state ) . '</td><td>' . esc_html( (string) $row->version ) . '</td><td>' . esc_html( (string) $row->updated_at ) . '</td></tr>'; }
        echo '</tbody></table></div>';
    }
    private static function detail( CoordinationCaseRepository $repo, object $case ): void {
        echo '<p><a href="' . esc_url( admin_url( 'admin.php?page=dzn-booking-request-coordination' ) ) . '">← Back</a></p><h2>' . esc_html( (string) $case->reference_code ) . '</h2><p>Booking Request #' . esc_html( (string) $case->booking_request_id ) . ' · State ' . esc_html( (string) $case->state ) . ' · Version ' . esc_html( (string) $case->version ) . '</p>';
        echo '<h3>Change advisory case state</h3><form method="post">'; wp_nonce_field( 'dzn_coordination_case_state_' . $case->id ); echo '<input type="hidden" name="dzn_coordination_action" value="transition_case"><input type="hidden" name="case_id" value="' . esc_attr( (string) $case->id ) . '"><input type="hidden" name="version" value="' . esc_attr( (string) $case->version ) . '"><select name="state">'; foreach ( array( 'candidate_search', 'manual_search', 'waiting_for_availability', 'withdrawn', 'declined', 'unable_to_arrange', 'abandoned' ) as $state ) echo '<option value="' . esc_attr( $state ) . '">' . esc_html( $state ) . '</option>'; echo '</select> <select name="reason"><option value="manual_review">manual_review</option><option value="unable_to_arrange">unable_to_arrange</option><option value="abandoned">abandoned</option><option value="withdrawn">withdrawn</option><option value="declined">declined</option></select><button class="button">Save state</button></form>';
        echo '<h3>Add advisory candidate</h3><form method="post">'; wp_nonce_field( 'dzn_coordination_candidate_' . $case->id ); echo '<input type="hidden" name="dzn_coordination_action" value="add_candidate"><input type="hidden" name="case_id" value="' . esc_attr( (string) $case->id ) . '"><input name="teacher_id" type="number" min="1" required> <select name="source">'; foreach ( array( 'advisory_match', 'manual_search', 'student_or_guardian_preference', 'teacher_referral', 'operational_referral', 'approved_exception' ) as $source ) echo '<option value="' . esc_attr( $source ) . '">' . esc_html( $source ) . '</option>'; echo '</select> <select name="reason"><option value="advisory_match">advisory_match</option><option value="manual_review">manual_review</option><option value="approved_exception">approved_exception</option></select><button class="button">Add candidate</button></form>';
        echo '<h3>Candidate considerations</h3><table class="widefat striped"><thead><tr><th>ID</th><th>Teacher</th><th>Source</th><th>Advisory status</th><th>Version</th><th>Update</th></tr></thead><tbody>';
        foreach ( $repo->candidates( (int) $case->id ) as $candidate ) { echo '<tr><td>' . esc_html( (string) $candidate->id ) . '</td><td>' . esc_html( (string) $candidate->teacher_id ) . '</td><td>' . esc_html( (string) $candidate->source ) . '</td><td>' . esc_html( (string) $candidate->status ) . '</td><td>' . esc_html( (string) $candidate->version ) . '</td><td><form method="post">'; wp_nonce_field( 'dzn_coordination_candidate_state_' . $candidate->id ); echo '<input type="hidden" name="dzn_coordination_action" value="transition_candidate"><input type="hidden" name="candidate_id" value="' . esc_attr( (string) $candidate->id ) . '"><input type="hidden" name="version" value="' . esc_attr( (string) $candidate->version ) . '"><select name="status">'; foreach ( array( 'under_discussion', 'not_available', 'not_suitable', 'withdrawn_from_consideration', 'superseded', 'closed' ) as $status ) echo '<option value="' . esc_attr( $status ) . '">' . esc_html( $status ) . '</option>'; echo '</select> <select name="reason"><option value="candidate_review">candidate_review</option><option value="not_available">not_available</option><option value="not_suitable">not_suitable</option><option value="withdrawn">withdrawn</option></select><button class="button">Save</button></form></td></tr>'; }
        echo '</tbody></table>';
        if ( current_user_can( 'dzn_manage_teacher_availability_assent' ) ) self::assentControls( $case );
    }
    private static function assentControls( object $case ): void {
        $repo = new TeacherAvailabilityAssentRepository();
        echo '<h3>Teacher Availability Assent</h3><p>Record only privacy-minimised, attributable evidence for frozen pre-issue facts. A recorded assent does not reserve capacity or create an assignment, proposal, acceptance, enrolment, Lesson, payment, or notification.</p>';
        echo '<form method="post">'; wp_nonce_field( 'dzn_teacher_assent_record' ); echo '<input type="hidden" name="dzn_coordination_action" value="record_teacher_assent"><input type="hidden" name="case_id" value="' . esc_attr( (string) $case->id ) . '"><p><label>Candidate ID <input name="candidate_id" type="number" min="1" required></label> <label>Candidate version <input name="candidate_version" type="number" min="1" required></label> <label>Teacher ID <input name="teacher_id" type="number" min="1" required></label></p><p><label>Prospective-subject reference <input name="prospective_subject_ref" required></label> <label>Course ID (or unresolved specification) <input name="course_id" type="number" min="1"></label> <label>Unresolved Course specification <input name="unresolved_course_spec"></label></p><p><label>Delivery <select name="delivery_mode"><option value="online">online</option><option value="in_person">in_person</option><option value="hybrid">hybrid</option></select></label> <label>Location scope <input name="location_scope" required></label> <label>Frequency per week <input name="frequency_per_week" type="number" min="1" max="14" required></label> <label>Duration minutes <input name="expected_duration_minutes" type="number" min="15" max="480" required></label></p><p><label>Schedule constraints <input name="schedule_constraints" required></label> <label>Commencement start UTC <input name="commencement_window_start" placeholder="YYYY-MM-DD HH:MM:SS" required></label> <label>Commencement end UTC <input name="commencement_window_end" placeholder="YYYY-MM-DD HH:MM:SS" required></label> <label>Timezone <input name="timezone" value="Asia/Tehran" required></label></p><p><label>Conditions code <input name="conditions_code"></label> <label>Validity end UTC <input name="valid_until" placeholder="YYYY-MM-DD HH:MM:SS"></label> <label>Review-by UTC <input name="review_by" placeholder="YYYY-MM-DD HH:MM:SS"></label></p><p><label>Attribution basis <input name="attribution_basis" required></label> <label>Evidence channel <select name="evidence_channel"><option value="in_person">in_person</option><option value="phone">phone</option><option value="email_reference">email_reference</option><option value="message_reference">message_reference</option><option value="other_reference">other_reference</option></select></label> <label>Evidence reference <input name="evidence_reference" required></label> <label>Evidence UTC <input name="evidence_at" placeholder="YYYY-MM-DD HH:MM:SS" required></label> <label>Uncertainty code <input name="uncertainty_code"></label></p><p><label>Replace assent ID (optional) <input name="supersede_assent_id" type="number" min="1"></label> <label>Replace assent version <input name="supersede_assent_version" type="number" min="1"></label> <button class="button button-primary">Record attested assent</button></p></form>';
        $rows = $repo->assents( (int) $case->id ); echo '<table class="widefat striped"><thead><tr><th>ID</th><th>Teacher</th><th>State</th><th>Validity / review</th><th>Fingerprint</th><th>Version</th><th>Action</th></tr></thead><tbody>';
        foreach ( $rows as $assent ) { echo '<tr><td>' . esc_html( (string) $assent->id ) . '</td><td>' . esc_html( (string) $assent->teacher_id ) . '</td><td>' . esc_html( (string) $assent->state ) . '</td><td>' . esc_html( (string) ( $assent->valid_until ?: '—' ) ) . ' / ' . esc_html( (string) ( $assent->review_by ?: '—' ) ) . '</td><td><code>' . esc_html( substr( (string) $assent->arrangement_fingerprint, 0, 16 ) ) . '…</code></td><td>' . esc_html( (string) $assent->version ) . '</td><td>';
            if ( $assent->state === 'recorded' ) { echo '<form method="post">'; wp_nonce_field( 'dzn_teacher_assent_state_' . $assent->id ); echo '<input type="hidden" name="assent_id" value="' . esc_attr( (string) $assent->id ) . '"><input type="hidden" name="version" value="' . esc_attr( (string) $assent->version ) . '"><select name="dzn_coordination_action"><option value="withdraw_teacher_assent">Teacher withdrawal</option><option value="invalidate_teacher_assent">Invalidate</option></select><select name="reason"><option value="teacher_withdrew">teacher_withdrew</option><option value="operational_unavailable">operational_unavailable</option><option value="eligibility_changed">eligibility_changed</option><option value="attribution_unreliable">attribution_unreliable</option><option value="material_facts_changed">material_facts_changed</option></select><button class="button">Apply</button></form>'; }
            echo '</td></tr>'; }
        echo '</tbody></table>';
    }
    private static function assentInput(): array { $fields = array( 'candidate_id','candidate_version','teacher_id','prospective_subject_ref','course_id','unresolved_course_spec','delivery_mode','location_scope','frequency_per_week','expected_duration_minutes','schedule_constraints','commencement_window_start','commencement_window_end','timezone','conditions_code','valid_until','review_by','attribution_basis','evidence_channel','evidence_reference','evidence_at','uncertainty_code','supersede_assent_id','supersede_assent_version' ); $out = array(); foreach ( $fields as $field ) $out[$field] = self::text( $_POST[$field] ?? null ); return $out; }
    private static function string( mixed $value ): string { return is_string( $value ) ? sanitize_key( wp_unslash( $value ) ) : ''; }
    private static function text( mixed $value ): string { return is_string( $value ) ? trim( sanitize_text_field( wp_unslash( $value ) ) ) : ''; }
    private static function id( mixed $value ): int { if ( ! is_string( $value ) || ! ctype_digit( $value ) || (int) $value < 1 ) throw new \InvalidArgumentException( 'Invalid identifier' ); return (int) $value; }
    private static function idOrZero( mixed $value ): int { return is_string( $value ) && ctype_digit( $value ) ? (int) $value : 0; }
    private static function redirect( bool $error ): never { $url = add_query_arg( array( 'page' => 'dzn-booking-request-coordination', 'dzn_notice' => $error ? 'Operation failed; no change was saved.' : 'Saved', 'dzn_error' => $error ? '1' : '0' ), admin_url( 'admin.php' ) ); wp_safe_redirect( $url ); exit; }
}
