<?php
namespace Delnavazan\Platform\Admin\Controller;
final class Menu {
	public static function register(): void { add_action('admin_menu', array(__CLASS__,'menu')); add_action('admin_init', array(__CLASS__,'caps')); }
	public static function caps(): void { $role=get_role('administrator'); if(!$role)return; foreach(array('dzn_manage_platform','dzn_manage_students','dzn_manage_teachers','dzn_manage_courses','dzn_manage_enrolments','dzn_manage_terms','dzn_manage_lessons','dzn_manage_exceptions','dzn_view_diagnostics') as $cap)$role->add_cap($cap); }
	public static function menu(): void { add_menu_page('Delnavazan','Delnavazan','dzn_manage_platform','dzn-platform',array(__CLASS__,'status'),'dashicons-networking',58); foreach(array('Teachers'=>'teachers','Students'=>'students','Instruments'=>'instruments','Courses'=>'courses','Enrolments'=>'enrolments','Terms'=>'terms','Lessons'=>'lessons','Exceptions'=>'operational_exceptions') as $name=>$slug)add_submenu_page('dzn-platform',$name,$name,'dzn_manage_platform','dzn-'.$slug,array(__CLASS__,'placeholder')); }
	public static function status(): void { global $wpdb; $tables=array('teachers','students','instruments','courses','enrolments','terms','lessons','lesson_schedule_versions','operational_exceptions','teacher_profile_links'); echo '<div class="wrap"><h1>Delnavazan Core Status</h1><p>Platform '.esc_html(DZN_PLATFORM_VERSION).' · Schema '.esc_html(get_option('dzn_platform_schema_version','not installed')).'</p><ul>'; foreach($tables as $t){$n=$wpdb->prefix.'dzn_'.$t; echo '<li>'.esc_html($n).': '.( $wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$n))===$n?'ready':'missing').'</li>'; } echo '</ul></div>'; }
	public static function placeholder(): void { echo '<div class="wrap"><h1>Delnavazan Core</h1><p>Phase 1 controlled validation surface.</p></div>'; }
}
