<?php
namespace Delnavazan\Platform\Admin\Controller;
final class StaffAccessController {
 private const BUNDLES=[
  'students'=>['label'=>'Students','caps'=>['dzn_manage_students','dzn_view_student_acceptance_eligibility','dzn_manage_enrolments']],
  'teachers'=>['label'=>'Teachers','caps'=>['dzn_manage_teachers','dzn_manage_onboarding','dzn_issue_teacher_invitations','dzn_revoke_teacher_invitations','dzn_view_onboarding_audit','dzn_manage_teaching_eligibility','dzn_manage_teacher_availability']],
  'bookings'=>['label'=>'Bookings & teaching','caps'=>['dzn_view_booking_requests','dzn_prepare_booking_request_matches','dzn_manage_booking_request_coordination','dzn_manage_terms','dzn_manage_lessons','dzn_manage_canonical_attendance_review']],
  'communications'=>['label'=>'Communications','caps'=>['dzn_view_notification_authority']],
  'finance'=>['label'=>'Finance','caps'=>['dzn_view_finance_authority','dzn_view_payment_execution_authority']],
 ];
 public static function register():void{add_action('admin_menu',[self::class,'menu']);}
 public static function menu():void{$h=add_submenu_page('dzn-platform','Staff Access','Staff Access','manage_options','dzn-staff-access',[self::class,'screen']);if($h)add_action('load-'.$h,[self::class,'post']);}
 public static function post():void{if(($_SERVER['REQUEST_METHOD']??'')!=='POST')return;check_admin_referer('dzn_staff_access');$uid=absint($_POST['user_id']??0);$user=get_user_by('id',$uid);if(!$user||user_can($user,'manage_options')){self::go('Choose a non-administrator staff account.',true);return;}$selected=array_map('sanitize_key',(array)($_POST['bundles']??[]));foreach(self::BUNDLES as$key=>$b)foreach($b['caps'] as$cap)$selected&&in_array($key,$selected,true)?$user->add_cap($cap):$user->remove_cap($cap);$user->add_cap('dzn_view_diagnostics');self::go('Staff access updated.',false,$uid);}
 public static function screen():void{$selected=absint($_GET['user_id']??0);$selectedUser=$selected?get_user_by('id',$selected):false;echo '<div class="wrap"><h1>Staff access</h1><p>Give a staff member access by work area instead of making them a WordPress Administrator. Administrator accounts are deliberately not editable here.</p>';if(isset($_GET['dzn_notice']))echo '<div class="notice notice-'.(($_GET['dzn_error']??'')==='1'?'error':'success').'"><p>'.esc_html(sanitize_text_field(wp_unslash($_GET['dzn_notice']))).'</p></div>';echo '<form method="get" style="margin:16px 0"><input type="hidden" name="page" value="dzn-staff-access"><label><strong>Staff account </strong><select name="user_id" onchange="this.form.submit()"><option value="">Choose account</option>';foreach(get_users(['orderby'=>'display_name']) as$u)if(!user_can($u,'manage_options'))echo '<option value="'.(int)$u->ID.'" '.selected($selected,(int)$u->ID,false).'>'.esc_html($u->display_name.' ('.$u->user_email.')').'</option>';echo '</select></label></form>';if(!$selectedUser){echo '<p>Select a staff account to review its current access before changing anything.</p></div>';return;}echo '<form method="post">';wp_nonce_field('dzn_staff_access');echo '<input type="hidden" name="user_id" value="'.(int)$selectedUser->ID.'"><table class="form-table"><tr><th>Selected account</th><td>'.esc_html($selectedUser->display_name.' ('.$selectedUser->user_email.')').'</td></tr><tr><th>Access areas</th><td>';foreach(self::BUNDLES as$key=>$b){$has=true;foreach($b['caps'] as$cap)if(!user_can($selectedUser,$cap)){$has=false;break;}echo '<label style="display:block;margin:8px 0"><input type="checkbox" name="bundles[]" value="'.esc_attr($key).'" '.checked($has,true,false).'> '.esc_html($b['label']).($has?' <strong>— currently granted</strong>':'').'</label>';}echo '<p class="description">Saving replaces this screen’s managed access bundles for the selected account. It does not grant WordPress Administrator access.</p></td></tr></table><button class="button button-primary">Save staff access</button></form></div>';}
 private static function go(string $m,bool $e=false,int $uid=0):void{wp_safe_redirect(add_query_arg(['page'=>'dzn-staff-access','user_id'=>$uid?:null,'dzn_notice'=>$m,'dzn_error'=>$e?'1':'0'],admin_url('admin.php')));exit;}
}
