<?php
namespace Delnavazan\Platform\Admin\Controller;
use Delnavazan\Platform\Core\Application\{TeachingEligibilityService,InstrumentIntroCourseDefaultService,TeacherAcceptingStateService};
use Delnavazan\Platform\Core\Infrastructure\Repository\TeachingEligibilityRepository;

/** Narrow administrator-only management surface; it deliberately has no public route. */
final class TeachingEligibilityController {
    public static function handlePost():void{if(($_SERVER['REQUEST_METHOD']??'')!=='POST')return;if(!current_user_can('dzn_manage_teaching_eligibility'))wp_die('Access denied.','Delnavazan',['response'=>403]);$post=wp_unslash($_POST);$action=sanitize_key($post['dzn_action']??'');if(!in_array($action,['set_teacher_course_eligibility','set_instrument_intro_default','set_teacher_accepting_state'],true))return;check_admin_referer('dzn_platform_'.$action);try{$id=match($action){'set_teacher_course_eligibility'=>(new TeachingEligibilityService())->setEligibility($post),'set_instrument_intro_default'=>(new InstrumentIntroCourseDefaultService())->set($post),'set_teacher_accepting_state'=>(new TeacherAcceptingStateService())->set($post)};self::redirect('Saved #'.$id);}catch(\Throwable){self::redirect('Operation failed; no change was saved.',true);}}
    public static function screen():void{if(!current_user_can('dzn_manage_teaching_eligibility')){echo '<div class="wrap"><p>Access denied.</p></div>';return;}$repo=new TeachingEligibilityRepository();echo '<div class="wrap"><h1>Teaching eligibility</h1><p>These Core facts are authoritative. They do not use Amelia, Hamnavaz, profile text, or contact matching.</p>';self::messages();self::form('set_teacher_course_eligibility','Teacher/Course eligibility',[['teacher_id','Teacher ID'],['course_id','Course ID'],['status','Status: active or inactive'],['effective_from','Effective UTC (YYYY-MM-DD HH:MM:SS)'],['effective_until','Effective until UTC (optional)'],['reason_code','Reason code']]);self::table('Teacher/Course eligibility',$repo->rows('teacher_course_eligibilities'));self::form('set_instrument_intro_default','Instrument default Intro Course',[['instrument_id','Instrument ID'],['course_id','Intro Course ID'],['status','Status: active or inactive'],['reason_code','Reason code']]);self::table('Instrument defaults',$repo->rows('instrument_intro_course_defaults'));self::form('set_teacher_accepting_state','Teacher accepting state',[['teacher_id','Teacher ID'],['state','State: accepting, limited, or paused'],['reason_code','Reason code']]);self::table('Teacher accepting states',$repo->rows('teacher_accepting_states'));echo '</div>';}
    private static function form(string $action,string $title,array $fields):void{echo '<h2>'.esc_html($title).'</h2><form method="post">';wp_nonce_field('dzn_platform_'.$action);echo '<input type="hidden" name="dzn_action" value="'.esc_attr($action).'">';foreach($fields as[$name,$label])echo '<p><label>'.esc_html($label).'<br><input class="regular-text" name="'.esc_attr($name).'"></label></p>';submit_button('Save');echo '</form>';}
    private static function table(string $title,array $rows):void{echo '<h3>'.esc_html($title).'</h3>';if(!$rows){echo '<p>No records.</p>';return;}$fields=array_keys(get_object_vars($rows[0]));echo '<table class="widefat striped"><thead><tr>';foreach($fields as$f)echo '<th>'.esc_html($f).'</th>';echo '</tr></thead><tbody>';foreach($rows as$row){echo '<tr>';foreach($fields as$f)echo '<td>'.esc_html((string)($row->$f??'')).'</td>';echo '</tr>';}echo '</tbody></table>';}
    private static function messages():void{if(!isset($_GET['dzn_notice']))return;echo '<div class="notice '.esc_attr((($_GET['dzn_error']??'')==='1')?'notice-error':'notice-success').'">'.esc_html(sanitize_text_field(wp_unslash($_GET['dzn_notice']))).'</div>';}
    private static function redirect(string $notice,bool $error=false):never{$url=add_query_arg(['page'=>'dzn-teaching-eligibility','dzn_notice'=>$notice,'dzn_error'=>$error?'1':'0'],admin_url('admin.php'));nocache_headers();if(wp_safe_redirect($url))exit;wp_die(esc_html($notice),'Delnavazan',['response'=>$error?500:200]);}
}
