<?php
namespace Delnavazan\Platform\Admin\Controller;

use Delnavazan\Platform\Core\Application\TeacherAvailabilityService;
use Delnavazan\Platform\Core\Infrastructure\Repository\TeacherAvailabilityRepository;

/** Protected management surface for Core availability facts only. */
final class TeacherAvailabilityController {
    public static function handlePost(): void {
        if ( ( $_SERVER['REQUEST_METHOD'] ?? '' ) !== 'POST' ) return;
        if ( ! current_user_can( 'dzn_manage_teacher_availability' ) ) wp_die( 'Access denied.', 'Delnavazan', array( 'response' => 403 ) );
        $post = wp_unslash( $_POST ); $action = sanitize_key( $post['dzn_action'] ?? '' );
        if ( ! in_array( $action, array( 'set_availability_profile', 'set_availability_rule', 'set_availability_exception' ), true ) ) return;
        check_admin_referer( 'dzn_platform_' . $action );
        try { $service = new TeacherAvailabilityService(); $id = match ( $action ) { 'set_availability_profile' => $service->setProfile( $post ), 'set_availability_rule' => $service->setRecurringRule( $post ), 'set_availability_exception' => $service->setDatedException( $post ) }; self::redirect( 'Saved #' . $id ); } catch ( \Throwable ) { self::redirect( 'Operation failed; no change was saved.', true ); }
    }
    public static function screen(): void {
        if ( ! current_user_can( 'dzn_manage_teacher_availability' ) ) { echo '<div class="wrap"><p>Access denied.</p></div>'; return; }
        $repo = new TeacherAvailabilityRepository(); echo '<div class="wrap"><h1>Teacher availability</h1><p>Core local-wall-clock facts only. They do not use Amelia, Google Calendar, profiles, or historical bookings.</p>'; self::messages(); self::form( 'set_availability_profile', 'Teacher timezone profile', array( array( 'teacher_id', 'Teacher ID' ), array( 'timezone', 'IANA timezone (for example, Australia/Brisbane)' ), array( 'status', 'Status: active or inactive' ), array( 'reason_code', 'Reason code' ) ) ); self::table( 'Availability profiles', $repo->rows( 'teacher_availability_profiles' ) ); self::form( 'set_availability_rule', 'Recurring weekly rule', array( array( 'id', 'Rule ID (optional, for update)' ), array( 'teacher_id', 'Teacher ID' ), array( 'weekday', 'Weekday: 1 Monday to 7 Sunday' ), array( 'local_start_time', 'Local start: HH:MM:SS' ), array( 'local_end_time', 'Local end: HH:MM:SS' ), array( 'state', 'State: preferred, requestable, or blocked' ), array( 'timezone', 'IANA timezone (must match profile)' ), array( 'status', 'Status: active or inactive' ), array( 'reason_code', 'Reason code' ) ) ); self::table( 'Recurring rules', $repo->rows( 'teacher_availability_rules' ) ); self::form( 'set_availability_exception', 'Dated exception', array( array( 'id', 'Exception ID (optional, for update)' ), array( 'teacher_id', 'Teacher ID' ), array( 'local_date', 'Local date: YYYY-MM-DD' ), array( 'all_day', 'All day: 1 for full-day override' ), array( 'local_start_time', 'Local start: HH:MM:SS (blank only when all day)' ), array( 'local_end_time', 'Local end: HH:MM:SS (blank only when all day)' ), array( 'state', 'State: preferred, requestable, or blocked' ), array( 'timezone', 'IANA timezone (must match profile)' ), array( 'status', 'Status: active or inactive' ), array( 'reason_code', 'Reason code' ) ) ); self::table( 'Dated exceptions', $repo->rows( 'teacher_availability_exceptions' ) ); echo '</div>';
    }
    private static function form(string $action, string $title, array $fields): void { echo '<h2>' . esc_html( $title ) . '</h2><form method="post">'; wp_nonce_field( 'dzn_platform_' . $action ); echo '<input type="hidden" name="dzn_action" value="' . esc_attr( $action ) . '">'; foreach ( $fields as [ $name, $label ] ) echo '<p><label>' . esc_html( $label ) . '<br><input class="regular-text" name="' . esc_attr( $name ) . '"></label></p>'; submit_button( 'Save' ); echo '</form>'; }
    private static function table(string $title, array $rows): void { echo '<h3>' . esc_html( $title ) . '</h3>'; if ( ! $rows ) { echo '<p>No records.</p>'; return; } $fields = array_keys( get_object_vars( $rows[0] ) ); echo '<table class="widefat striped"><thead><tr>'; foreach ( $fields as $field ) echo '<th>' . esc_html( $field ) . '</th>'; echo '</tr></thead><tbody>'; foreach ( $rows as $row ) { echo '<tr>'; foreach ( $fields as $field ) { $value = property_exists( $row, $field ) ? $row->{$field} : ''; echo '<td>' . esc_html( (string) $value ) . '</td>'; } echo '</tr>'; } echo '</tbody></table>'; }
    private static function messages(): void { if ( ! isset( $_GET['dzn_notice'] ) ) return; echo '<div class="notice ' . esc_attr( ( ( $_GET['dzn_error'] ?? '' ) === '1' ) ? 'notice-error' : 'notice-success' ) . '">' . esc_html( sanitize_text_field( wp_unslash( $_GET['dzn_notice'] ) ) ) . '</div>'; }
    private static function redirect(string $notice, bool $error = false): never { $url = add_query_arg( array( 'page' => 'dzn-teacher-availability', 'dzn_notice' => $notice, 'dzn_error' => $error ? '1' : '0' ), admin_url( 'admin.php' ) ); nocache_headers(); if ( wp_safe_redirect( $url ) ) exit; wp_die( esc_html( $notice ), 'Delnavazan', array( 'response' => $error ? 500 : 200 ) ); }
}
