<?php
namespace Delnavazan\Platform\Portals;

abstract class PortalReadModel {
    public const VERSION='portal_lesson_v1';
    protected function field(array $row,string $key){if(!array_key_exists($key,$row))throw new \InvalidArgumentException('portal_upstream_aggregate_invalid');return$row[$key];}
}

final class PortalStudentLessonReadModel extends PortalReadModel {
    public function fromOwner(array $row):array { return array('version'=>self::VERSION,'lesson_uid'=>$this->field($row,'lesson_uid'),'reference_code'=>$this->field($row,'lesson_reference'),'lesson_kind'=>$this->field($row,'lesson_kind'),'lifecycle_state'=>$this->field($row,'lifecycle_state'),'enrolment_uid'=>$this->field($row,'enrolment_uid'),'course_reference'=>$this->field($row,'course_reference'),'term_reference'=>$this->field($row,'term_reference'),'starts_at_utc'=>$this->field($row,'starts_at_utc'),'ends_at_utc'=>$this->field($row,'ends_at_utc'),'schedule_timezone'=>$this->field($row,'schedule_timezone'),'schedule_version_uid'=>$this->field($row,'schedule_version_uid'),'delivery_state_summary'=>$this->field($row,'delivery_state_summary'),'attendance_state_summary'=>$this->field($row,'attendance_state_summary'),'join_available'=>(bool)$this->field($row,'join_available'),'join_refusal_reason'=>$this->field($row,'join_refusal_reason'),'absence_available'=>(bool)$this->field($row,'absence_available'),'absence_refusal_reason'=>$this->field($row,'absence_refusal_reason')); }
}

final class PortalTeacherLessonReadModel extends PortalReadModel {
    public function fromOwner(array $row):array { return array('version'=>self::VERSION,'lesson_uid'=>$this->field($row,'lesson_uid'),'reference_code'=>$this->field($row,'lesson_reference'),'lesson_kind'=>$this->field($row,'lesson_kind'),'lifecycle_state'=>$this->field($row,'lifecycle_state'),'enrolment_uid'=>$this->field($row,'enrolment_uid'),'course_reference'=>$this->field($row,'course_reference'),'term_reference'=>$this->field($row,'term_reference'),'starts_at_utc'=>$this->field($row,'starts_at_utc'),'ends_at_utc'=>$this->field($row,'ends_at_utc'),'schedule_timezone'=>$this->field($row,'schedule_timezone'),'schedule_version_uid'=>$this->field($row,'schedule_version_uid'),'delivery_state_summary'=>$this->field($row,'delivery_state_summary'),'attendance_state_summary'=>$this->field($row,'attendance_state_summary'),'join_available'=>(bool)$this->field($row,'join_available'),'join_refusal_reason'=>$this->field($row,'join_refusal_reason'),'absence_available'=>(bool)$this->field($row,'absence_available'),'absence_refusal_reason'=>$this->field($row,'absence_refusal_reason'),'assignment_state'=>$this->field($row,'assignment_state'),'student_display_reference'=>$this->field($row,'student_display_reference')); }
}

final class PortalStudentEnrolmentReadModel extends PortalReadModel {
    public const VERSION='portal_enrolment_v1';
    public function fromOwner(array $row):array { return array('version'=>self::VERSION,'enrolment_uid'=>$this->field($row,'enrolment_uid'),'reference_code'=>$this->field($row,'enrolment_reference'),'course_reference'=>$this->field($row,'course_reference'),'term_reference'=>$this->field($row,'term_reference'),'lifecycle_state'=>$this->field($row,'lifecycle_state'),'assigned_teacher_display_reference'=>$this->field($row,'assigned_teacher_display_reference'),'schedule_summary'=>$this->field($row,'schedule_summary')); }
}

final class PortalTeacherAssignmentReadModel extends PortalReadModel {
    public const VERSION='portal_enrolment_v1';
    public function fromOwner(array $row):array { return array('version'=>self::VERSION,'assignment_uid'=>$this->field($row,'assignment_uid'),'enrolment_uid'=>$this->field($row,'enrolment_uid'),'course_reference'=>$this->field($row,'course_reference'),'term_reference'=>$this->field($row,'term_reference'),'assignment_state'=>$this->field($row,'assignment_state'),'accepted_at'=>$this->field($row,'accepted_at'),'student_display_reference'=>$this->field($row,'student_display_reference')); }
}

final class PortalPrincipalReadModel {
    public const VERSION='portal_principal_v1';
    public function fromPrincipal(array $principal):array { foreach(array('kind','id','uid','display_reference','linked_at') as$key){if(!array_key_exists($key,$principal))throw new \InvalidArgumentException('portal_principal_unresolved');}$out=array('version'=>self::VERSION,'principal_kind'=>(string)$principal['kind'],'principal_id'=>(int)$principal['id'],'principal_uid'=>(string)$principal['uid'],'display_reference'=>(string)$principal['display_reference'],'linked_at'=>(string)$principal['linked_at']);if((string)$principal['kind']==='guardian'){foreach(array('grant_scope','grant_effective_from','grant_effective_until') as$key){if(!array_key_exists($key,$principal))throw new \InvalidArgumentException('portal_principal_unresolved');$out[$key]=$principal[$key];}}return$out; }
}

/** Internal composition seam only; controllers/routes remain deliberately absent in Phase W. */
final class PortalInternalReadSurface {
    public function studentLesson(AuthenticatedPortalReadSubject $subject,int $lessonId,?CanonicalLessonSchedulePortalReadPort $schedulePort=null):array { $schedule=($schedulePort??PortalOwnerPorts::schedule())->forSubject($subject,$lessonId);$delivery=PortalOwnerPorts::delivery()->summaryForSubject($subject,$lessonId);$attendance=PortalOwnerPorts::attendance()->summaryForSubject($subject,$lessonId,(int)$schedule['schedule_version_id']);return(new PortalStudentLessonReadModel())->fromOwner(array_merge($schedule,$delivery,$attendance,$this->capabilityAvailability($lessonId,(int)$schedule['schedule_version_id'],(int)$subject->principalId))); }
    public function teacherLesson(AuthenticatedPortalReadSubject $subject,int $lessonId,?CanonicalLessonSchedulePortalReadPort $schedulePort=null):array { $schedule=($schedulePort??PortalOwnerPorts::schedule())->forSubject($subject,$lessonId);$assignment=PortalOwnerPorts::assignment()->forSubject($subject,(int)$schedule['enrolment_id']);$delivery=PortalOwnerPorts::delivery()->summaryForSubject($subject,$lessonId);$attendance=PortalOwnerPorts::attendance()->summaryForSubject($subject,$lessonId,(int)$schedule['schedule_version_id']);return(new PortalTeacherLessonReadModel())->fromOwner(array_merge($schedule,$assignment,$delivery,$attendance,$this->capabilityAvailability($lessonId,(int)$schedule['schedule_version_id'],null))); }
    public function teacherAssignment(AuthenticatedPortalReadSubject $subject,int $enrolmentId,?TeacherAssignmentPortalReadPort $assignmentPort=null):array{return(new PortalTeacherAssignmentReadModel())->fromOwner(($assignmentPort??PortalOwnerPorts::assignment())->forSubject($subject,$enrolmentId));}
    public function studentEnrolment(AuthenticatedPortalReadSubject $subject,int $enrolmentId,?TeacherAssignmentPortalReadPort $assignmentPort=null):array{return(new PortalStudentEnrolmentReadModel())->fromOwner(($assignmentPort??PortalOwnerPorts::assignment())->forSubject($subject,$enrolmentId));}
    public function principal(array $principal):array{return(new PortalPrincipalReadModel())->fromPrincipal($principal);}
    private function capabilityAvailability(int $lessonId,int $scheduleVersionId,?int $studentId):array { $available=array(PortalRule::JOIN=>false,PortalRule::ABSENCE=>false);if($studentId===null)return array('join_available'=>false,'join_refusal_reason'=>'portal_capability_unknown','absence_available'=>false,'absence_refusal_reason'=>'portal_capability_unknown');global $wpdb;$p=$wpdb->prefix.'dzn_portal_public_capabilities';$where='lesson_id=%d AND schedule_version_id=%d AND state=\'active\' AND expires_at>UTC_TIMESTAMP() AND (subject_student_id IS NULL OR subject_student_id=%d)';$rows=$wpdb->get_results($wpdb->prepare("SELECT purpose FROM {$p} WHERE {$where}",array($lessonId,$scheduleVersionId,$studentId)));foreach((array)$rows as$row)if(isset($available[(string)$row->purpose]))$available[(string)$row->purpose]=true;return array('join_available'=>$available[PortalRule::JOIN],'join_refusal_reason'=>$available[PortalRule::JOIN]?null:'portal_capability_unknown','absence_available'=>$available[PortalRule::ABSENCE],'absence_refusal_reason'=>$available[PortalRule::ABSENCE]?null:'portal_capability_unknown'); }
}
