<?php
namespace Delnavazan\Platform\Portals;

final class PortalPublicActionService {
    private function table(string $name):string { global $wpdb; return $wpdb->prefix.'dzn_'.$name; }
    private function uid():string { return substr(hash('sha256',wp_generate_uuid4()),0,26); }
    private function digest(string $value):string { return hash('sha256',$value); }
    private function requestDigest():string { return hash_hmac('sha256','portal_public_request_v1|'.wp_json_encode($_REQUEST),wp_salt('dzn_portal_request_fingerprint')); }

    public function renderAbsenceConfirmation(string $handle,string $token):string {
        global $wpdb; $wpdb->query('START TRANSACTION'); try { $row=(new PortalCapabilityService())->verify($handle,$token,PortalRule::ABSENCE); $wpdb->get_row($wpdb->prepare("SELECT id FROM {$this->table('portal_lesson_capability_roots')} WHERE lesson_id=%d FOR UPDATE",$row->lesson_id)); $wpdb->get_row($wpdb->prepare("SELECT id FROM {$this->table('portal_public_capabilities')} WHERE id=%d FOR UPDATE",$row->id)); $confirmation=bin2hex(random_bytes(32)); $now=gmdate('Y-m-d H:i:s');
        $sequence=(int)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(MAX(action_sequence),0)+1 FROM {$this->table('portal_public_action_events')} WHERE capability_id=%d FOR UPDATE",$row->id));
        if(false===$wpdb->insert($this->table('portal_public_action_events'),array('uid'=>$this->uid(),'capability_id'=>(int)$row->id,'lesson_id'=>(int)$row->lesson_id,'purpose'=>PortalRule::ABSENCE,'action_sequence'=>$sequence,'action_state'=>'confirmation_rendered','resolved_student_id'=>(int)$row->subject_student_id,'confirmation_digest'=>$this->digest($confirmation),'redemption_key_digest'=>$this->digest($confirmation),'request_fingerprint_digest'=>$this->requestDigest(),'occurred_at'=>$now,'created_at'=>$now,'created_by'=>null)))throw new \RuntimeException('portal_action_evidence_persistence_failed'); $wpdb->query('COMMIT'); } catch(\Throwable $e){$wpdb->query('ROLLBACK');throw $e;}
        return '<!doctype html><html><head><meta charset="utf-8"><meta name="robots" content="noindex,noarchive"><title>Confirm absence</title></head><body><main><h1>Confirm absence</h1><p>Reference: <span>'.esc_html((string)$row->uid).'</span></p><form method="post" action="'.esc_attr(home_url('/wp-json/delnavazan-platform/v1/portal/absence/confirm')).'"><input type="hidden" name="handle" value="'.esc_attr($handle).'"><input type="hidden" name="token" value="'.esc_attr($token).'"><input type="hidden" name="confirmation" value="'.esc_attr($confirmation).'"><button type="submit">Confirm absence</button></form></main></body></html>';
    }

    public function confirmAbsence(string $handle,string $token,string $confirmation):array {
        if(!preg_match('/^[a-f0-9]{64}$/',$confirmation))throw new \InvalidArgumentException('portal_confirmation_invalid'); global $wpdb; $p=$wpdb->prefix.'dzn_'; $digest=$this->digest($confirmation);
        try{$proof=(new PortalCapabilityService())->verify($handle,$token,PortalRule::ABSENCE); $proofSubject=new PublicCapabilityReadSubject((int)$proof->id,PortalRule::ABSENCE,(int)$proof->lesson_id,(int)$proof->schedule_version_id,(int)$proof->generation,(int)$proof->subject_student_id,(string)$proof->expires_at); PortalOwnerPorts::attendance()->assertCapabilityClaimAdmissible($proofSubject);}catch(\InvalidArgumentException $e){if($e->getMessage()!=='portal_capability_consumed')throw $e;}
        $resume=false;
        $wpdb->query('START TRANSACTION');
        try{
            $hint=$wpdb->get_row($wpdb->prepare("SELECT id,lesson_id FROM {$p}portal_public_capabilities WHERE handle_digest=%s LIMIT 1",hash_hmac('sha256',$handle,wp_salt('dzn_portal_capability_public'))));if(!$hint)throw new \InvalidArgumentException('portal_capability_unknown');
            if(!$wpdb->get_row($wpdb->prepare("SELECT id FROM {$p}portal_lesson_capability_roots WHERE lesson_id=%d FOR UPDATE",$hint->lesson_id)))throw new \InvalidArgumentException('portal_capability_unknown');
            $row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}portal_public_capabilities WHERE id=%d FOR UPDATE",$hint->id));if(!$row)throw new \InvalidArgumentException('portal_capability_unknown');
            if((string)$row->state==='consumed'){
                $row=(new PortalCapabilityService())->verifyConsumed($handle,$token,PortalRule::ABSENCE,(int)$row->id);
                $bound=$wpdb->get_row($wpdb->prepare("SELECT id FROM {$p}portal_public_action_events WHERE id=%d AND capability_id=%d AND confirmation_digest=%s AND action_state='confirmed_submitting' FOR UPDATE",(int)$row->consumed_action_event_id,(int)$row->id,$digest));
                if(!$bound)throw new \InvalidArgumentException('portal_confirmation_invalid');
            }else{$row=(new PortalCapabilityService())->verify($handle,$token,PortalRule::ABSENCE);}
            $rendered=$wpdb->get_row($wpdb->prepare("SELECT id FROM {$p}portal_public_action_events WHERE capability_id=%d AND confirmation_digest=%s AND action_state='confirmation_rendered' LIMIT 1",$row->id,$digest));if(!$rendered)throw new \InvalidArgumentException('portal_confirmation_invalid');
            $existing=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}portal_public_action_events WHERE capability_id=%d AND confirmation_digest=%s AND action_state IN ('confirmed_submitting','submitted','refused') ORDER BY id DESC LIMIT 1",$row->id,$digest));
            if($existing){if($existing->action_state==='refused'){ $wpdb->query('COMMIT');throw new \InvalidArgumentException((string)$existing->outcome_reason_code); }if($existing->action_state==='submitted'){ $wpdb->query('COMMIT');return array('capability_id'=>(int)$row->id,'lesson_id'=>(int)$row->lesson_id,'attribution'=>'public_capability_on_behalf','state'=>'submitted','replayed'=>true); }$resume=true; $wpdb->query('COMMIT');}
            if($resume){ /* The durable claim is resumed below, outside this transaction. */ }
            else {
            $now=gmdate('Y-m-d H:i:s');$sequence=(int)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(MAX(action_sequence),0)+1 FROM {$p}portal_public_action_events WHERE capability_id=%d FOR UPDATE",$row->id));
            if(false===$wpdb->insert($p.'portal_public_action_events',array('uid'=>$this->uid(),'capability_id'=>(int)$row->id,'lesson_id'=>(int)$row->lesson_id,'purpose'=>PortalRule::ABSENCE,'action_sequence'=>$sequence,'action_state'=>'confirmed_submitting','resolved_student_id'=>(int)$row->subject_student_id,'confirmation_digest'=>$digest,'redemption_key_digest'=>$digest,'request_fingerprint_digest'=>$this->requestDigest(),'occurred_at'=>$now,'created_at'=>$now,'created_by'=>null)))throw new \RuntimeException('portal_action_evidence_persistence_failed');$claimId=(int)$wpdb->insert_id;
            $eventSequence=(int)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(MAX(event_sequence),0)+1 FROM {$p}portal_public_capability_events WHERE lesson_id=%d FOR UPDATE",$row->lesson_id));if(false===$wpdb->insert($p.'portal_public_capability_events',array('uid'=>$this->uid(),'lesson_id'=>(int)$row->lesson_id,'capability_id'=>(int)$row->id,'event_sequence'=>$eventSequence,'event_type'=>'consumed','purpose'=>PortalRule::ABSENCE,'generation'=>(int)$row->generation,'reason_code'=>'portal_confirmation_required','evidence_channel'=>'public_confirmation','evidence_reference_digest'=>$this->digest($confirmation),'recorded_at'=>$now,'created_at'=>$now,'created_by'=>0)))throw new \RuntimeException('portal_capability_persistence_failed');
            if(false===$wpdb->insert($p.'portal_public_capability_commands',array('uid'=>$this->uid(),'command_domain'=>'portal_capability','operation'=>'consume','command_key_digest'=>hash_hmac('sha256',$confirmation,wp_salt('dzn_portal_capability_public')),'command_payload_digest'=>$this->digest($confirmation.'|consume'),'lesson_id'=>(int)$row->lesson_id,'purpose'=>PortalRule::ABSENCE,'expected_capability_id'=>(int)$row->id,'expected_generation'=>(int)$row->generation,'expected_state'=>'active','reason_code'=>'portal_confirmation_required','result_capability_id'=>(int)$row->id,'result_state'=>'consumed','created_at'=>$now,'created_by'=>0)))throw new \RuntimeException('portal_capability_persistence_failed');
            if($wpdb->query($wpdb->prepare("UPDATE {$p}portal_public_capabilities SET state='consumed',active_slot=NULL,consumed_at=%s,consumed_action_event_id=%d WHERE id=%d AND state='active' AND active_slot=1",$now,$claimId,$row->id))!==1)throw new \RuntimeException('portal_capability_generation_conflict');$wpdb->query('COMMIT');
            }
        }catch(\Throwable $e){$wpdb->query('ROLLBACK');throw $e;}
        $subject=new PublicCapabilityReadSubject((int)$row->id,PortalRule::ABSENCE,(int)$row->lesson_id,(int)$row->schedule_version_id,(int)$row->generation,(int)$row->subject_student_id,(string)$row->expires_at);
        try{$result=PortalOwnerPorts::attendance()->submitCapabilityClaim($subject,$confirmation);$state='submitted';$reason=null;}catch(\Throwable $e){$result=array('capability_id'=>(int)$row->id,'lesson_id'=>(int)$row->lesson_id);$state='refused';$reason=in_array($e->getMessage(),PortalRule::EXCEPTION_REASON_CODES,true)?$e->getMessage():'portal_upstream_aggregate_invalid';}
        $wpdb->query('START TRANSACTION');try{$now=gmdate('Y-m-d H:i:s');$sequence=(int)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(MAX(action_sequence),0)+1 FROM {$p}portal_public_action_events WHERE capability_id=%d FOR UPDATE",$row->id));if(false===$wpdb->insert($p.'portal_public_action_events',array('uid'=>$this->uid(),'capability_id'=>(int)$row->id,'lesson_id'=>(int)$row->lesson_id,'purpose'=>PortalRule::ABSENCE,'action_sequence'=>$sequence,'action_state'=>$state,'resolved_student_id'=>(int)$row->subject_student_id,'confirmation_digest'=>$digest,'redemption_key_digest'=>$this->digest($confirmation.'|'.$state),'handoff_target'=>$state==='submitted'?'canonical_attendance_evidence':null,'handoff_reference_id'=>$state==='submitted'?(int)($result['evidence_id']??0):null,'outcome_reason_code'=>$reason,'request_fingerprint_digest'=>$this->requestDigest(),'occurred_at'=>$now,'created_at'=>$now,'created_by'=>null)))throw new \RuntimeException('portal_action_evidence_persistence_failed');$wpdb->query('COMMIT');if($state==='refused')throw new \InvalidArgumentException($reason);return array_merge($result,array('capability_id'=>(int)$row->id,'attribution'=>'public_capability_on_behalf','state'=>$state));}catch(\Throwable $e){$wpdb->query('ROLLBACK');throw $e;}
    }
}
