<?php
namespace Delnavazan\Platform\Portals;
final class PortalCapabilityService {
    private function table(string $name):string { global $wpdb; return $wpdb->prefix.'dzn_'.$name; }
    private function digest(string $value):string { return hash_hmac('sha256',$value,wp_salt('auth')); }
    private function uid():string { return substr(str_replace('-','',wp_generate_uuid4()),0,26); }
    private function seal(string $value):array { $key=hash('sha256',wp_salt('secure_auth').'dzn_portal_join_target',true);$iv=random_bytes(16);return array(base64_encode(openssl_encrypt($value,'aes-256-cbc',$key,OPENSSL_RAW_DATA,$iv)),base64_encode($iv)); }
    private function unseal(string $cipher,string $iv):string { $key=hash('sha256',wp_salt('secure_auth').'dzn_portal_join_target',true);$value=openssl_decrypt(base64_decode($cipher),'aes-256-cbc',$key,OPENSSL_RAW_DATA,base64_decode($iv));if(!is_string($value))throw new \RuntimeException('portal_join_target_seal_invalid');return $value; }
    public function mint(int $lessonId,int $scheduleVersionId,string $purpose,int $expiresAt,string $joinTarget='',?int $studentId=null):array {
        if(!current_user_can('dzn_manage_portal_capabilities'))throw new \RuntimeException('Unauthorized'); if(!in_array($purpose,array(PortalRule::JOIN,PortalRule::ABSENCE),true))throw new \InvalidArgumentException('portal_purpose_not_allowed'); if($purpose===PortalRule::ABSENCE)throw new \InvalidArgumentException('portal_parent_not_live'); if($expiresAt<=time()||$expiresAt>time()+PortalRule::MAX_CAPABILITY_TTL_SECONDS)throw new \InvalidArgumentException('portal_capability_expiry_invalid');
        $parts=parse_url($joinTarget);$host=strtolower((string)($parts['host']??''));if(!$parts||($parts['scheme']??'')!=='https'||!in_array($host,PortalRule::SAFE_JOIN_HOSTS,true))throw new \InvalidArgumentException('portal_join_target_not_allowlisted'); [$cipher,$nonce]=$this->seal($joinTarget);$token=bin2hex(random_bytes(32));$handle=bin2hex(random_bytes(32));global $wpdb;$root=$this->table('portal_lesson_capability_roots');$cap=$this->table('portal_public_capabilities');$now=gmdate('Y-m-d H:i:s');$wpdb->query('START TRANSACTION');try{$wpdb->query($wpdb->prepare("INSERT IGNORE INTO {$root} (lesson_id,created_at,created_by) VALUES (%d,%s,%d)",$lessonId,$now,get_current_user_id()));$live=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$cap} WHERE lesson_id=%d AND purpose=%s AND state='active' AND active_slot=1 FOR UPDATE",$lessonId,$purpose));if($live)throw new \InvalidArgumentException('portal_capability_rotation_required');$generation=(int)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(MAX(generation),0)+1 FROM {$cap} WHERE lesson_id=%d AND purpose=%s FOR UPDATE",$lessonId,$purpose));$ok=$wpdb->insert($cap,array('uid'=>$this->uid(),'lesson_id'=>$lessonId,'schedule_version_id'=>$scheduleVersionId,'subject_student_id'=>$studentId,'purpose'=>$purpose,'generation'=>$generation,'handle_digest'=>$this->digest($handle),'token_digest'=>$this->digest($token),'join_target_ciphertext'=>$cipher,'join_target_nonce'=>$nonce,'join_target_key_version'=>'auth','join_target_cipher_version'=>'v1','join_target_host'=>$host,'state'=>'active','active_slot'=>1,'issued_at'=>$now,'expires_at'=>gmdate('Y-m-d H:i:s',$expiresAt),'reason_code'=>'operator_issue','created_at'=>$now,'created_by'=>get_current_user_id()));if(!$ok)throw new \RuntimeException('portal_capability_persistence_failed');$id=(int)$wpdb->insert_id;$wpdb->insert($this->table('portal_public_capability_events'),array('uid'=>$this->uid(),'lesson_id'=>$lessonId,'capability_id'=>$id,'event_sequence'=>$generation,'event_type'=>'minted','purpose'=>$purpose,'generation'=>$generation,'reason_code'=>'operator_issue','evidence_channel'=>'admin','evidence_reference_digest'=>hash('sha256',$handle),'recorded_at'=>$now,'created_at'=>$now,'created_by'=>get_current_user_id()));$wpdb->query('COMMIT');return array('capability_id'=>$id,'handle'=>$handle,'token'=>$token,'url'=>home_url('/wp-json/delnavazan-platform/v1/portal/join?handle='.rawurlencode($handle).'&token='.rawurlencode($token)));}catch(\Throwable $e){$wpdb->query('ROLLBACK');throw $e;}
    }
    public function verify(string $handle,string $token):object { global $wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->table('portal_public_capabilities')} WHERE handle_digest=%s AND token_digest=%s LIMIT 1",$this->digest($handle),$this->digest($token)));if(!$row)throw new \InvalidArgumentException('portal_capability_unknown');if($row->state!=='active')throw new \InvalidArgumentException($row->state==='revoked'?'portal_capability_revoked':'portal_capability_superseded');if(strtotime($row->expires_at)<=time())throw new \InvalidArgumentException('portal_capability_expired');return $row; }
    public function join(string $handle,string $token):string { $row=$this->verify($handle,$token);if($row->purpose!==PortalRule::JOIN)throw new \InvalidArgumentException('portal_capability_purpose_mismatch');global $wpdb;$url=$this->unseal($row->join_target_ciphertext,$row->join_target_nonce);$wpdb->insert($this->table('portal_public_action_events'),array('uid'=>$this->uid(),'capability_id'=>$row->id,'lesson_id'=>$row->lesson_id,'purpose'=>$row->purpose,'action_sequence'=>1,'action_state'=>'redirected','redemption_key_digest'=>$this->digest($handle.':join'),'request_fingerprint_digest'=>hash('sha256',wp_json_encode($_REQUEST)),'occurred_at'=>gmdate('Y-m-d H:i:s'),'created_at'=>gmdate('Y-m-d H:i:s')));return $url; }
    public function revoke(int $capabilityId,string $reason):void { if(!current_user_can('dzn_manage_portal_capabilities'))throw new \RuntimeException('Unauthorized');PortalRule::reason($reason);global $wpdb;$wpdb->query($wpdb->prepare("UPDATE {$this->table('portal_public_capabilities')} SET state='revoked',active_slot=NULL,revoked_at=%s,revoked_by=%d,revocation_reason_code=%s WHERE id=%d AND state='active'",gmdate('Y-m-d H:i:s'),get_current_user_id(),$reason,$capabilityId)); }
    public function rotate(int $lessonId,int $scheduleVersionId,string $purpose,int $expiresAt,string $joinTarget,string $reason):array { if(!current_user_can('dzn_manage_portal_capabilities'))throw new \RuntimeException('Unauthorized');PortalRule::reason($reason);global $wpdb;$wpdb->query($wpdb->prepare("UPDATE {$this->table('portal_public_capabilities')} SET state='superseded',active_slot=NULL,revoked_at=%s,revoked_by=%d,revocation_reason_code=%s WHERE lesson_id=%d AND purpose=%s AND state='active' AND active_slot=1",gmdate('Y-m-d H:i:s'),get_current_user_id(),$reason,$lessonId,$purpose));return $this->mint($lessonId,$scheduleVersionId,$purpose,$expiresAt,$joinTarget); }
}
